module ModernTreasury
  module Resources
    class InternalAccounts
      class BalanceReports
        def create: (
          String internal_account_id,
          as_of_date: Date,
          as_of_time: String,
          balance_report_type: ModernTreasury::Models::InternalAccounts::BalanceReportCreateParams::balance_report_type,
          balances: ::Array[ModernTreasury::Models::InternalAccounts::BalanceReportCreateParams::Balance],
          ?request_options: ModernTreasury::request_opts
        ) -> ModernTreasury::Models::InternalAccounts::BalanceReport

        def retrieve: (
          String id,
          internal_account_id: String,
          ?request_options: ModernTreasury::request_opts
        ) -> ModernTreasury::Models::InternalAccounts::BalanceReport

        def list: (
          String internal_account_id,
          ?after_cursor: String?,
          ?as_of_date: Date,
          ?balance_report_type: ModernTreasury::Models::InternalAccounts::BalanceReportListParams::balance_report_type,
          ?per_page: Integer,
          ?request_options: ModernTreasury::request_opts
        ) -> ModernTreasury::Internal::Page[ModernTreasury::Models::InternalAccounts::BalanceReport]

        def delete: (
          String id,
          internal_account_id: String,
          ?request_options: ModernTreasury::request_opts
        ) -> nil

        def initialize: (client: ModernTreasury::Client) -> void
      end
    end
  end
end
