module ModernTreasury
  module Models
    module LedgerAccountSettlements
      type account_entry_delete_params =
        { ledger_entry_ids: Array[top] } & ModernTreasury::request_parameters

      class AccountEntryDeleteParams < ModernTreasury::BaseModel
        extend ModernTreasury::RequestParameters::Converter
        include ModernTreasury::RequestParameters

        attr_accessor ledger_entry_ids: Array[top]

        def initialize:
          (
            ledger_entry_ids: Array[top],
            request_options: ModernTreasury::request_opts
          ) -> void
          | (
            ?ModernTreasury::Models::LedgerAccountSettlements::account_entry_delete_params
            | ModernTreasury::BaseModel data
          ) -> void

        def to_h: -> ModernTreasury::Models::LedgerAccountSettlements::account_entry_delete_params
      end
    end
  end
end
