module ModernTreasury
  module Models
    module PaymentOrders
      type reversal_create_params =
        {
          reason: ModernTreasury::Models::PaymentOrders::ReversalCreateParams::reason,
          ledger_transaction: ModernTreasury::LedgerTransactionCreateRequest,
          metadata: ::Hash[Symbol, String]
        }
        & ModernTreasury::Internal::Type::request_parameters

      class ReversalCreateParams < ModernTreasury::Internal::Type::BaseModel
        extend ModernTreasury::Internal::Type::RequestParameters::Converter
        include ModernTreasury::Internal::Type::RequestParameters

        attr_accessor reason: ModernTreasury::Models::PaymentOrders::ReversalCreateParams::reason

        attr_reader ledger_transaction: ModernTreasury::LedgerTransactionCreateRequest?

        def ledger_transaction=: (
          ModernTreasury::LedgerTransactionCreateRequest
        ) -> ModernTreasury::LedgerTransactionCreateRequest

        attr_reader metadata: ::Hash[Symbol, String]?

        def metadata=: (::Hash[Symbol, String]) -> ::Hash[Symbol, String]

        def initialize: (
          reason: ModernTreasury::Models::PaymentOrders::ReversalCreateParams::reason,
          ?ledger_transaction: ModernTreasury::LedgerTransactionCreateRequest,
          ?metadata: ::Hash[Symbol, String],
          ?request_options: ModernTreasury::request_opts
        ) -> void

        def to_hash: -> {
          reason: ModernTreasury::Models::PaymentOrders::ReversalCreateParams::reason,
          ledger_transaction: ModernTreasury::LedgerTransactionCreateRequest,
          metadata: ::Hash[Symbol, String],
          request_options: ModernTreasury::RequestOptions
        }

        type reason =
          :duplicate
          | :incorrect_amount
          | :incorrect_receiving_account
          | :date_earlier_than_intended
          | :date_later_than_intended

        module Reason
          extend ModernTreasury::Internal::Type::Enum

          DUPLICATE: :duplicate
          INCORRECT_AMOUNT: :incorrect_amount
          INCORRECT_RECEIVING_ACCOUNT: :incorrect_receiving_account
          DATE_EARLIER_THAN_INTENDED: :date_earlier_than_intended
          DATE_LATER_THAN_INTENDED: :date_later_than_intended

          def self?.values: -> ::Array[ModernTreasury::Models::PaymentOrders::ReversalCreateParams::reason]
        end
      end
    end
  end
end
