module ModernTreasury
  module Resources
    class Invoices
      class LineItems
        def create: (
          String invoice_id,
          name: String,
          unit_amount: Integer,
          ?description: String,
          ?direction: String,
          ?metadata: ::Hash[Symbol, String],
          ?quantity: Integer,
          ?unit_amount_decimal: String,
          ?request_options: ModernTreasury::request_opts
        ) -> ModernTreasury::Invoices::InvoiceLineItem

        def retrieve: (
          String id,
          invoice_id: String,
          ?request_options: ModernTreasury::request_opts
        ) -> ModernTreasury::Invoices::InvoiceLineItem

        def update: (
          String id,
          invoice_id: String,
          ?description: String,
          ?direction: String,
          ?metadata: ::Hash[Symbol, String],
          ?name: String,
          ?quantity: Integer,
          ?unit_amount: Integer,
          ?unit_amount_decimal: String,
          ?request_options: ModernTreasury::request_opts
        ) -> ModernTreasury::Invoices::InvoiceLineItem

        def list: (
          String invoice_id,
          ?after_cursor: String?,
          ?per_page: Integer,
          ?request_options: ModernTreasury::request_opts
        ) -> ModernTreasury::Internal::Page[ModernTreasury::Invoices::InvoiceLineItem]

        def delete: (
          String id,
          invoice_id: String,
          ?request_options: ModernTreasury::request_opts
        ) -> ModernTreasury::Invoices::InvoiceLineItem

        def initialize: (client: ModernTreasury::Client) -> void
      end
    end
  end
end
