module ModernTreasury
  module Resources
    class AccountCollectionFlows
      def create: (
        counterparty_id: String,
        payment_types: ::Array[String],
        ?receiving_countries: ::Array[ModernTreasury::Models::AccountCollectionFlowCreateParams::receiving_country],
        ?request_options: ModernTreasury::request_opts
      ) -> ModernTreasury::Models::AccountCollectionFlow

      def retrieve: (
        String id,
        ?request_options: ModernTreasury::request_opts
      ) -> ModernTreasury::Models::AccountCollectionFlow

      def update: (
        String id,
        status: ModernTreasury::Models::AccountCollectionFlowUpdateParams::status,
        ?request_options: ModernTreasury::request_opts
      ) -> ModernTreasury::Models::AccountCollectionFlow

      def list: (
        ?after_cursor: String?,
        ?client_token: String,
        ?counterparty_id: String,
        ?external_account_id: String,
        ?per_page: Integer,
        ?status: String,
        ?request_options: ModernTreasury::request_opts
      ) -> ModernTreasury::Internal::Page[ModernTreasury::Models::AccountCollectionFlow]

      def initialize: (client: ModernTreasury::Client) -> void
    end
  end
end
