module ModernTreasury
  module Resources
    class BulkRequests
      def create: (
        action_type: ModernTreasury::Models::BulkRequestCreateParams::action_type,
        resource_type: ModernTreasury::Models::BulkRequestCreateParams::resource_type,
        resources: ::Array[ModernTreasury::Models::BulkRequestCreateParams::resource],
        ?metadata: ::Hash[Symbol, String],
        ?request_options: ModernTreasury::request_opts
      ) -> ModernTreasury::BulkRequest

      def retrieve: (
        String id,
        ?request_options: ModernTreasury::request_opts
      ) -> ModernTreasury::BulkRequest

      def list: (
        ?action_type: ModernTreasury::Models::BulkRequestListParams::action_type,
        ?after_cursor: String?,
        ?metadata: ::Hash[Symbol, String],
        ?per_page: Integer,
        ?resource_type: ModernTreasury::Models::BulkRequestListParams::resource_type,
        ?status: ModernTreasury::Models::BulkRequestListParams::status,
        ?request_options: ModernTreasury::request_opts
      ) -> ModernTreasury::Internal::Page[ModernTreasury::BulkRequest]

      def initialize: (client: ModernTreasury::Client) -> void
    end
  end
end
