module ModernTreasury
  module Resources
    class Counterparties
      def create: (
        name: String?,
        ?accounting: ModernTreasury::CounterpartyCreateParams::Accounting,
        ?accounts: ::Array[ModernTreasury::CounterpartyCreateParams::Account],
        ?email: String?,
        ?external_id: String?,
        ?ledger_type: ModernTreasury::Models::CounterpartyCreateParams::ledger_type,
        ?legal_entity: ModernTreasury::LegalEntityCreate,
        ?legal_entity_id: String?,
        ?metadata: ::Hash[Symbol, String],
        ?send_remittance_advice: bool,
        ?taxpayer_identifier: String,
        ?verification_status: String,
        ?request_options: ModernTreasury::request_opts
      ) -> ModernTreasury::Counterparty

      def retrieve: (
        String id,
        ?request_options: ModernTreasury::request_opts
      ) -> ModernTreasury::Counterparty

      def update: (
        String id,
        ?email: String,
        ?legal_entity_id: String?,
        ?metadata: ::Hash[Symbol, String],
        ?name: String,
        ?send_remittance_advice: bool,
        ?taxpayer_identifier: String,
        ?request_options: ModernTreasury::request_opts
      ) -> ModernTreasury::Counterparty

      def list: (
        ?after_cursor: String?,
        ?created_at_lower_bound: Time,
        ?created_at_upper_bound: Time,
        ?email: String,
        ?external_id: String,
        ?legal_entity_id: String,
        ?metadata: ::Hash[Symbol, String],
        ?name: String,
        ?per_page: Integer,
        ?request_options: ModernTreasury::request_opts
      ) -> ModernTreasury::Internal::Page[ModernTreasury::Counterparty]

      def delete: (
        String id,
        ?request_options: ModernTreasury::request_opts
      ) -> nil

      def collect_account: (
        String id,
        direction: ModernTreasury::Models::transaction_direction,
        ?custom_redirect: String,
        ?fields: ::Array[ModernTreasury::Models::CounterpartyCollectAccountParams::field],
        ?send_email: bool,
        ?request_options: ModernTreasury::request_opts
      ) -> ModernTreasury::CounterpartyCollectAccountResponse

      def initialize: (client: ModernTreasury::Client) -> void
    end
  end
end
