module ModernTreasury
  module Resources
    class Documents
      def create: (
        documentable_id: String,
        documentable_type: ModernTreasury::Models::DocumentCreate::documentable_type,
        file: ModernTreasury::Internal::file_input,
        ?document_type: String,
        ?request_options: ModernTreasury::request_opts
      ) -> ModernTreasury::Document

      def retrieve: (
        String id,
        ?request_options: ModernTreasury::request_opts
      ) -> ModernTreasury::Document

      def list: (
        ?after_cursor: String?,
        ?documentable_id: String,
        ?documentable_type: ModernTreasury::Models::DocumentListParams::documentable_type,
        ?per_page: Integer,
        ?request_options: ModernTreasury::request_opts
      ) -> ModernTreasury::Internal::Page[ModernTreasury::Document]

      def initialize: (client: ModernTreasury::Client) -> void
    end
  end
end
