module ModernTreasury
  module Resources
    class Events
      def retrieve: (
        String id,
        ?request_options: ModernTreasury::request_opts
      ) -> ModernTreasury::Event

      def list: (
        ?after_cursor: String?,
        ?entity_id: String,
        ?event_name: String,
        ?event_time_end: Time,
        ?event_time_start: Time,
        ?per_page: Integer,
        ?resource: String,
        ?request_options: ModernTreasury::request_opts
      ) -> ModernTreasury::Internal::Page[ModernTreasury::Event]

      def initialize: (client: ModernTreasury::Client) -> void
    end
  end
end
