module ModernTreasury
  module Resources
    class ExpectedPayments
      def create: (
        ?amount_lower_bound: Integer?,
        ?amount_upper_bound: Integer?,
        ?counterparty_id: String?,
        ?currency: ModernTreasury::Models::currency?,
        ?date_lower_bound: Date?,
        ?date_upper_bound: Date?,
        ?description: String?,
        ?direction: ModernTreasury::Models::ExpectedPaymentCreateParams::direction?,
        ?internal_account_id: String?,
        ?ledger_transaction: ModernTreasury::ExpectedPaymentCreateParams::LedgerTransaction,
        ?ledger_transaction_id: String,
        ?line_items: ::Array[ModernTreasury::ExpectedPaymentCreateParams::LineItem],
        ?metadata: ::Hash[Symbol, String],
        ?reconciliation_filters: top?,
        ?reconciliation_groups: top?,
        ?reconciliation_rule_variables: ::Array[ModernTreasury::ReconciliationRule]?,
        ?remittance_information: String?,
        ?statement_descriptor: String?,
        ?type: ModernTreasury::Models::expected_payment_type?,
        ?request_options: ModernTreasury::request_opts
      ) -> ModernTreasury::ExpectedPayment

      def retrieve: (
        String id,
        ?request_options: ModernTreasury::request_opts
      ) -> ModernTreasury::ExpectedPayment

      def update: (
        String id,
        ?amount_lower_bound: Integer?,
        ?amount_upper_bound: Integer?,
        ?counterparty_id: String?,
        ?currency: ModernTreasury::Models::currency?,
        ?date_lower_bound: Date?,
        ?date_upper_bound: Date?,
        ?description: String?,
        ?direction: ModernTreasury::Models::ExpectedPaymentUpdateParams::direction?,
        ?internal_account_id: String?,
        ?metadata: ::Hash[Symbol, String],
        ?reconciliation_filters: top?,
        ?reconciliation_groups: top?,
        ?reconciliation_rule_variables: ::Array[ModernTreasury::ReconciliationRule]?,
        ?remittance_information: String?,
        ?statement_descriptor: String?,
        ?status: ModernTreasury::Models::ExpectedPaymentUpdateParams::status?,
        ?type: ModernTreasury::Models::expected_payment_type?,
        ?request_options: ModernTreasury::request_opts
      ) -> ModernTreasury::ExpectedPayment

      def list: (
        ?after_cursor: String?,
        ?counterparty_id: String,
        ?created_at_lower_bound: Time,
        ?created_at_upper_bound: Time,
        ?direction: ModernTreasury::Models::transaction_direction,
        ?internal_account_id: String,
        ?metadata: ::Hash[Symbol, String],
        ?per_page: Integer,
        ?status: ModernTreasury::Models::ExpectedPaymentListParams::status,
        ?type: ModernTreasury::Models::ExpectedPaymentListParams::type_,
        ?request_options: ModernTreasury::request_opts
      ) -> ModernTreasury::Internal::Page[ModernTreasury::ExpectedPayment]

      def delete: (
        String id,
        ?request_options: ModernTreasury::request_opts
      ) -> ModernTreasury::ExpectedPayment

      def initialize: (client: ModernTreasury::Client) -> void
    end
  end
end
