module ModernTreasury
  module Resources
    class ExternalAccounts
      def create: (
        counterparty_id: String?,
        ?account_details: ::Array[ModernTreasury::ExternalAccountCreateParams::AccountDetail],
        ?account_type: ModernTreasury::Models::external_account_type,
        ?contact_details: ::Array[ModernTreasury::ExternalAccountCreateParams::ContactDetail],
        ?ledger_account: ModernTreasury::ExternalAccountCreateParams::LedgerAccount,
        ?metadata: ::Hash[Symbol, String],
        ?name: String?,
        ?party_address: ModernTreasury::ExternalAccountCreateParams::PartyAddress,
        ?party_identifier: String,
        ?party_name: String,
        ?party_type: ModernTreasury::Models::ExternalAccountCreateParams::party_type?,
        ?plaid_processor_token: String,
        ?routing_details: ::Array[ModernTreasury::ExternalAccountCreateParams::RoutingDetail],
        ?request_options: ModernTreasury::request_opts
      ) -> ModernTreasury::ExternalAccount

      def retrieve: (
        String id,
        ?request_options: ModernTreasury::request_opts
      ) -> ModernTreasury::ExternalAccount

      def update: (
        String id,
        ?account_type: ModernTreasury::Models::external_account_type,
        ?counterparty_id: String?,
        ?metadata: ::Hash[Symbol, String],
        ?name: String?,
        ?party_address: ModernTreasury::ExternalAccountUpdateParams::PartyAddress,
        ?party_name: String,
        ?party_type: ModernTreasury::Models::ExternalAccountUpdateParams::party_type?,
        ?request_options: ModernTreasury::request_opts
      ) -> ModernTreasury::ExternalAccount

      def list: (
        ?after_cursor: String?,
        ?counterparty_id: String,
        ?metadata: ::Hash[Symbol, String],
        ?party_name: String,
        ?per_page: Integer,
        ?request_options: ModernTreasury::request_opts
      ) -> ModernTreasury::Internal::Page[ModernTreasury::ExternalAccount]

      def delete: (
        String id,
        ?request_options: ModernTreasury::request_opts
      ) -> nil

      def complete_verification: (
        String id,
        ?amounts: ::Array[Integer],
        ?request_options: ModernTreasury::request_opts
      ) -> ModernTreasury::ExternalAccount

      def verify: (
        String id,
        originating_account_id: String,
        payment_type: ModernTreasury::Models::ExternalAccountVerifyParams::payment_type,
        ?currency: ModernTreasury::Models::currency,
        ?fallback_type: ModernTreasury::Models::ExternalAccountVerifyParams::fallback_type,
        ?priority: ModernTreasury::Models::ExternalAccountVerifyParams::priority,
        ?request_options: ModernTreasury::request_opts
      ) -> ModernTreasury::Models::external_account_verify_response

      def initialize: (client: ModernTreasury::Client) -> void
    end
  end
end
