module ModernTreasury
  module Resources
    class InternalAccounts
      attr_reader balance_reports: ModernTreasury::Resources::InternalAccounts::BalanceReports

      def create:
        (
          ModernTreasury::Models::InternalAccountCreateParams
          | Hash[Symbol, top] params
        ) -> ModernTreasury::Models::InternalAccount
        | (
          connection_id: String,
          currency: ModernTreasury::Models::InternalAccountCreateParams::currency,
          name: String,
          party_name: String,
          counterparty_id: String,
          legal_entity_id: String,
          parent_account_id: String,
          party_address: ModernTreasury::Models::InternalAccountCreateParams::PartyAddress,
          vendor_attributes: Hash[Symbol, String],
          request_options: ModernTreasury::request_opts
        ) -> ModernTreasury::Models::InternalAccount

      def retrieve:
        (
          String id,
          ?ModernTreasury::Models::InternalAccountRetrieveParams
          | Hash[Symbol, top] params
        ) -> ModernTreasury::Models::InternalAccount
        | (
          String id,
          request_options: ModernTreasury::request_opts
        ) -> ModernTreasury::Models::InternalAccount

      def update:
        (
          String id,
          ?ModernTreasury::Models::InternalAccountUpdateParams
          | Hash[Symbol, top] params
        ) -> ModernTreasury::Models::InternalAccount
        | (
          String id,
          counterparty_id: String,
          ledger_account_id: String,
          metadata: Hash[Symbol, String],
          name: String,
          parent_account_id: String,
          request_options: ModernTreasury::request_opts
        ) -> ModernTreasury::Models::InternalAccount

      def list:
        (
          ?ModernTreasury::Models::InternalAccountListParams
          | Hash[Symbol, top] params
        ) -> ModernTreasury::Page[ModernTreasury::Models::InternalAccount]
        | (
          after_cursor: String?,
          counterparty_id: String,
          currency: ModernTreasury::Models::currency,
          legal_entity_id: String,
          metadata: Hash[Symbol, String],
          payment_direction: ModernTreasury::Models::transaction_direction,
          payment_type: ModernTreasury::Models::InternalAccountListParams::payment_type,
          per_page: Integer,
          request_options: ModernTreasury::request_opts
        ) -> ModernTreasury::Page[ModernTreasury::Models::InternalAccount]

      def initialize: (client: ModernTreasury::Client) -> void
    end
  end
end
