module ModernTreasury
  module Resources
    class LedgerAccountBalanceMonitors
      def create: (
        alert_condition: ModernTreasury::LedgerAccountBalanceMonitorCreateParams::AlertCondition,
        ledger_account_id: String,
        ?description: String,
        ?metadata: ::Hash[Symbol, String],
        ?request_options: ModernTreasury::request_opts
      ) -> ModernTreasury::LedgerAccountBalanceMonitor

      def retrieve: (
        String id,
        ?request_options: ModernTreasury::request_opts
      ) -> ModernTreasury::LedgerAccountBalanceMonitor

      def update: (
        String id,
        ?description: String,
        ?metadata: ::Hash[Symbol, String],
        ?request_options: ModernTreasury::request_opts
      ) -> ModernTreasury::LedgerAccountBalanceMonitor

      def list: (
        ?id: ::Array[String],
        ?after_cursor: String?,
        ?ledger_account_id: String,
        ?metadata: ::Hash[Symbol, String],
        ?per_page: Integer,
        ?request_options: ModernTreasury::request_opts
      ) -> ModernTreasury::Internal::Page[ModernTreasury::LedgerAccountBalanceMonitor]

      def delete: (
        String id,
        ?request_options: ModernTreasury::request_opts
      ) -> ModernTreasury::LedgerAccountBalanceMonitor

      def initialize: (client: ModernTreasury::Client) -> void
    end
  end
end
