module ModernTreasury
  module Resources
    class LedgerAccountSettlements
      attr_reader account_entries: ModernTreasury::Resources::LedgerAccountSettlements::AccountEntries

      def create:
        (
          ModernTreasury::Models::LedgerAccountSettlementCreateParams
          | ::Hash[Symbol, top] params
        ) -> ModernTreasury::Models::LedgerAccountSettlement
        | (
          contra_ledger_account_id: String,
          settled_ledger_account_id: String,
          ?allow_either_direction: bool?,
          ?description: String?,
          ?effective_at_upper_bound: Time?,
          ?metadata: ::Hash[Symbol, String],
          ?skip_settlement_ledger_transaction: bool?,
          ?status: ModernTreasury::Models::LedgerAccountSettlementCreateParams::status?,
          ?request_options: ModernTreasury::request_opts
        ) -> ModernTreasury::Models::LedgerAccountSettlement

      def retrieve:
        (
          String id,
          ?ModernTreasury::Models::LedgerAccountSettlementRetrieveParams
          | ::Hash[Symbol, top] params
        ) -> ModernTreasury::Models::LedgerAccountSettlement
        | (
          String id,
          ?request_options: ModernTreasury::request_opts
        ) -> ModernTreasury::Models::LedgerAccountSettlement

      def update:
        (
          String id,
          ?ModernTreasury::Models::LedgerAccountSettlementUpdateParams
          | ::Hash[Symbol, top] params
        ) -> ModernTreasury::Models::LedgerAccountSettlement
        | (
          String id,
          ?description: String?,
          ?metadata: ::Hash[Symbol, String],
          ?status: ModernTreasury::Models::LedgerAccountSettlementUpdateParams::status,
          ?request_options: ModernTreasury::request_opts
        ) -> ModernTreasury::Models::LedgerAccountSettlement

      def list:
        (
          ?ModernTreasury::Models::LedgerAccountSettlementListParams
          | ::Hash[Symbol, top] params
        ) -> ModernTreasury::Page[ModernTreasury::Models::LedgerAccountSettlement]
        | (
          ?id: ::Array[String],
          ?after_cursor: String?,
          ?created_at: ::Hash[Symbol, Time],
          ?ledger_id: String,
          ?ledger_transaction_id: String,
          ?metadata: ::Hash[Symbol, String],
          ?per_page: Integer,
          ?settled_ledger_account_id: String,
          ?settlement_entry_direction: String,
          ?updated_at: ::Hash[Symbol, Time],
          ?request_options: ModernTreasury::request_opts
        ) -> ModernTreasury::Page[ModernTreasury::Models::LedgerAccountSettlement]

      def initialize: (client: ModernTreasury::Client) -> void
    end
  end
end
