module ModernTreasury
  module Resources
    class LedgerAccountStatements
      def create: (
        effective_at_lower_bound: Time,
        effective_at_upper_bound: Time,
        ledger_account_id: String,
        ?description: String?,
        ?metadata: ::Hash[Symbol, String],
        ?request_options: ModernTreasury::request_opts
      ) -> ModernTreasury::Models::LedgerAccountStatementCreateResponse

      def retrieve: (
        String id,
        ?request_options: ModernTreasury::request_opts
      ) -> ModernTreasury::Models::LedgerAccountStatementRetrieveResponse

      def initialize: (client: ModernTreasury::Client) -> void
    end
  end
end
