module ModernTreasury
  module Resources
    class LedgerTransactions
      attr_reader versions: ModernTreasury::Resources::LedgerTransactions::Versions

      def create: (
        ledger_entries: ::Array[ModernTreasury::LedgerEntryCreateRequest],
        ?description: String?,
        ?effective_at: Time,
        ?effective_date: Date,
        ?external_id: String,
        ?ledgerable_id: String,
        ?ledgerable_type: ModernTreasury::Models::LedgerTransactionCreateRequest::ledgerable_type,
        ?metadata: ::Hash[Symbol, String],
        ?status: ModernTreasury::Models::LedgerTransactionCreateRequest::status,
        ?request_options: ModernTreasury::request_opts
      ) -> ModernTreasury::LedgerTransaction

      def retrieve: (
        String id,
        ?request_options: ModernTreasury::request_opts
      ) -> ModernTreasury::LedgerTransaction

      def update: (
        String id,
        ?description: String?,
        ?effective_at: Time,
        ?external_id: String?,
        ?ledger_entries: ::Array[ModernTreasury::LedgerEntryCreateRequest],
        ?ledgerable_id: String,
        ?ledgerable_type: ModernTreasury::Models::LedgerTransactionUpdateParams::ledgerable_type,
        ?metadata: ::Hash[Symbol, String],
        ?status: ModernTreasury::Models::LedgerTransactionUpdateParams::status,
        ?request_options: ModernTreasury::request_opts
      ) -> ModernTreasury::LedgerTransaction

      def list: (
        ?id: ::Array[String],
        ?after_cursor: String?,
        ?amount: ModernTreasury::LedgerTransactionListParams::Amount,
        ?effective_at: ::Hash[Symbol, Time],
        ?effective_date: ::Hash[Symbol, Time],
        ?external_id: String,
        ?ledger_account_category_id: String,
        ?ledger_account_id: String,
        ?ledger_account_settlement_id: String,
        ?ledger_id: String,
        ?ledgerable_id: String,
        ?ledgerable_type: ModernTreasury::Models::LedgerTransactionListParams::ledgerable_type,
        ?metadata: ::Hash[Symbol, String],
        ?order_by: ModernTreasury::LedgerTransactionListParams::OrderBy,
        ?partially_posts_ledger_transaction_id: String,
        ?per_page: Integer,
        ?posted_at: ::Hash[Symbol, Time],
        ?reverses_ledger_transaction_id: String,
        ?status: ModernTreasury::Models::LedgerTransactionListParams::status,
        ?updated_at: ::Hash[Symbol, Time],
        ?request_options: ModernTreasury::request_opts
      ) -> ModernTreasury::Internal::Page[ModernTreasury::LedgerTransaction]

      def create_partial_post: (
        String id,
        posted_ledger_entries: ::Array[ModernTreasury::LedgerTransactionCreatePartialPostParams::PostedLedgerEntry],
        ?description: String,
        ?effective_at: Time,
        ?metadata: ::Hash[Symbol, String],
        ?request_options: ModernTreasury::request_opts
      ) -> ModernTreasury::LedgerTransaction

      def create_reversal: (
        String id,
        ?description: String,
        ?effective_at: Time?,
        ?external_id: String,
        ?ledgerable_id: String,
        ?ledgerable_type: ModernTreasury::Models::LedgerTransactionCreateReversalParams::ledgerable_type,
        ?metadata: ::Hash[Symbol, String],
        ?status: ModernTreasury::Models::LedgerTransactionCreateReversalParams::status,
        ?request_options: ModernTreasury::request_opts
      ) -> ModernTreasury::LedgerTransaction

      def initialize: (client: ModernTreasury::Client) -> void
    end
  end
end
