module ModernTreasury
  module Resources
    class LedgerAccountCategories
      def create: (
        currency: String,
        ledger_id: String,
        name: String,
        normal_balance: ModernTreasury::Models::transaction_direction,
        ?currency_exponent: Integer?,
        ?description: String?,
        ?external_id: String?,
        ?ledger_account_category_ids: ::Array[String],
        ?metadata: ::Hash[Symbol, String],
        ?request_options: ModernTreasury::request_opts
      ) -> ModernTreasury::LedgerAccountCategory

      def retrieve: (
        String id,
        ?balances: ModernTreasury::LedgerAccountCategoryRetrieveParams::Balances,
        ?request_options: ModernTreasury::request_opts
      ) -> ModernTreasury::LedgerAccountCategory

      def update: (
        String id,
        ?description: String?,
        ?metadata: ::Hash[Symbol, String],
        ?name: String,
        ?request_options: ModernTreasury::request_opts
      ) -> ModernTreasury::LedgerAccountCategory

      def list: (
        ?id: ::Array[String],
        ?after_cursor: String?,
        ?balances: ModernTreasury::LedgerAccountCategoryListParams::Balances,
        ?currency: String,
        ?external_id: String,
        ?ledger_account_id: String,
        ?ledger_id: String,
        ?metadata: ::Hash[Symbol, String],
        ?name: String,
        ?parent_ledger_account_category_id: String,
        ?per_page: Integer,
        ?request_options: ModernTreasury::request_opts
      ) -> ModernTreasury::Internal::Page[ModernTreasury::LedgerAccountCategory]

      def delete: (
        String id,
        ?request_options: ModernTreasury::request_opts
      ) -> ModernTreasury::LedgerAccountCategory

      def add_ledger_account: (
        String ledger_account_id,
        id: String,
        ?request_options: ModernTreasury::request_opts
      ) -> nil

      def add_nested_category: (
        String sub_category_id,
        id: String,
        ?request_options: ModernTreasury::request_opts
      ) -> nil

      def remove_ledger_account: (
        String ledger_account_id,
        id: String,
        ?request_options: ModernTreasury::request_opts
      ) -> nil

      def remove_nested_category: (
        String sub_category_id,
        id: String,
        ?request_options: ModernTreasury::request_opts
      ) -> nil

      def initialize: (client: ModernTreasury::Client) -> void
    end
  end
end
