module ModernTreasury
  module Resources
    class LedgerAccounts
      def create:
        (
          ModernTreasury::Models::LedgerAccountCreateParams
          | Hash[Symbol, top] params
        ) -> ModernTreasury::Models::LedgerAccount
        | (
          ModernTreasury::Models::LedgerAccountCreateParams
          | Hash[Symbol, top] params,
          currency: String,
          ledger_id: String,
          name: String,
          normal_balance: ModernTreasury::Models::transaction_direction,
          currency_exponent: Integer?,
          description: String?,
          ledger_account_category_ids: Array[String],
          ledgerable_id: String,
          ledgerable_type: ModernTreasury::Models::LedgerAccountCreateParams::ledgerable_type,
          metadata: Hash[Symbol, String],
          request_options: ModernTreasury::request_opts
        ) -> ModernTreasury::Models::LedgerAccount

      def retrieve:
        (
          String id,
          ?ModernTreasury::Models::LedgerAccountRetrieveParams
          | Hash[Symbol, top] params
        ) -> ModernTreasury::Models::LedgerAccount
        | (
          String id,
          balances: ModernTreasury::Models::LedgerAccountRetrieveParams::Balances,
          request_options: ModernTreasury::request_opts
        ) -> ModernTreasury::Models::LedgerAccount

      def update:
        (
          String id,
          ?ModernTreasury::Models::LedgerAccountUpdateParams
          | Hash[Symbol, top] params
        ) -> ModernTreasury::Models::LedgerAccount
        | (
          String id,
          description: String?,
          metadata: Hash[Symbol, String],
          name: String,
          request_options: ModernTreasury::request_opts
        ) -> ModernTreasury::Models::LedgerAccount

      def list:
        (
          ?ModernTreasury::Models::LedgerAccountListParams
          | Hash[Symbol, top] params
        ) -> ModernTreasury::Page[ModernTreasury::Models::LedgerAccount]
        | (
          id: Array[String],
          after_cursor: String?,
          available_balance_amount: ModernTreasury::Models::LedgerAccountListParams::AvailableBalanceAmount,
          balances: ModernTreasury::Models::LedgerAccountListParams::Balances,
          created_at: Hash[Symbol, Time],
          currency: String,
          ledger_account_category_id: String,
          ledger_id: String,
          metadata: Hash[Symbol, String],
          name: Array[String],
          pending_balance_amount: ModernTreasury::Models::LedgerAccountListParams::PendingBalanceAmount,
          per_page: Integer,
          posted_balance_amount: ModernTreasury::Models::LedgerAccountListParams::PostedBalanceAmount,
          updated_at: Hash[Symbol, Time],
          request_options: ModernTreasury::request_opts
        ) -> ModernTreasury::Page[ModernTreasury::Models::LedgerAccount]

      def delete:
        (
          String id,
          ?ModernTreasury::Models::LedgerAccountDeleteParams
          | Hash[Symbol, top] params
        ) -> ModernTreasury::Models::LedgerAccount
        | (
          String id,
          request_options: ModernTreasury::request_opts
        ) -> ModernTreasury::Models::LedgerAccount

      def initialize: (client: ModernTreasury::Client) -> void
    end
  end
end
