module ModernTreasury
  module Resources
    class LegalEntityAssociations
      def create:
        (
          ModernTreasury::Models::LegalEntityAssociationCreateParams
          | ::Hash[Symbol, top] params
        ) -> ModernTreasury::Models::LegalEntityAssociation
        | (
          parent_legal_entity_id: String,
          relationship_types: ::Array[ModernTreasury::Models::LegalEntityAssociationCreateParams::relationship_type],
          ?child_legal_entity: ModernTreasury::Models::LegalEntityAssociationCreateParams::ChildLegalEntity,
          ?child_legal_entity_id: String,
          ?ownership_percentage: Integer?,
          ?title: String?,
          ?request_options: ModernTreasury::request_opts
        ) -> ModernTreasury::Models::LegalEntityAssociation

      def initialize: (client: ModernTreasury::Client) -> void
    end
  end
end
