module ModernTreasury
  module Resources
    class LegalEntities
      def create: (
        legal_entity_type: ModernTreasury::Models::LegalEntityCreateParams::legal_entity_type,
        ?addresses: ::Array[ModernTreasury::LegalEntityAddressCreateRequest],
        ?bank_settings: ModernTreasury::LegalEntityBankSettings?,
        ?business_description: String?,
        ?business_name: String?,
        ?citizenship_country: String?,
        ?compliance_details: ModernTreasury::LegalEntityComplianceDetail?,
        ?connection_id: String?,
        ?country_of_incorporation: String?,
        ?date_formed: Date?,
        ?date_of_birth: Date?,
        ?doing_business_as_names: ::Array[String],
        ?email: String?,
        ?expected_activity_volume: Integer?,
        ?first_name: String?,
        ?identifications: ::Array[ModernTreasury::IdentificationCreateRequest],
        ?industry_classifications: ::Array[ModernTreasury::LegalEntityIndustryClassification],
        ?intended_use: String?,
        ?last_name: String?,
        ?legal_entity_associations: ::Array[ModernTreasury::LegalEntityAssociationInlineCreate]?,
        ?legal_structure: ModernTreasury::Models::LegalEntityCreateParams::legal_structure?,
        ?listed_exchange: String?,
        ?metadata: ::Hash[Symbol, String],
        ?middle_name: String?,
        ?operating_jurisdictions: ::Array[String],
        ?phone_numbers: ::Array[ModernTreasury::LegalEntityCreateParams::PhoneNumber],
        ?politically_exposed_person: bool?,
        ?preferred_name: String?,
        ?prefix: String?,
        ?primary_social_media_sites: ::Array[String],
        ?regulators: ::Array[ModernTreasury::LegalEntityCreateParams::Regulator]?,
        ?risk_rating: ModernTreasury::Models::LegalEntityCreateParams::risk_rating?,
        ?status: ModernTreasury::Models::LegalEntityCreateParams::status?,
        ?suffix: String?,
        ?third_party_verification: ModernTreasury::LegalEntityCreateParams::ThirdPartyVerification?,
        ?ticker_symbol: String?,
        ?wealth_and_employment_details: ModernTreasury::LegalEntityWealthEmploymentDetail?,
        ?website: String?,
        ?request_options: ModernTreasury::request_opts
      ) -> ModernTreasury::LegalEntity

      def retrieve: (
        String id,
        ?request_options: ModernTreasury::request_opts
      ) -> ModernTreasury::LegalEntity

      def update: (
        String id,
        ?addresses: ::Array[ModernTreasury::LegalEntityAddressCreateRequest],
        ?bank_settings: ModernTreasury::LegalEntityBankSettings?,
        ?business_description: String?,
        ?business_name: String?,
        ?citizenship_country: String?,
        ?compliance_details: ModernTreasury::LegalEntityComplianceDetail?,
        ?country_of_incorporation: String?,
        ?date_formed: Date?,
        ?date_of_birth: Date?,
        ?doing_business_as_names: ::Array[String],
        ?email: String?,
        ?expected_activity_volume: Integer?,
        ?first_name: String?,
        ?identifications: ::Array[ModernTreasury::IdentificationCreateRequest],
        ?industry_classifications: ::Array[ModernTreasury::LegalEntityIndustryClassification],
        ?intended_use: String?,
        ?last_name: String?,
        ?legal_structure: ModernTreasury::Models::LegalEntityUpdateParams::legal_structure?,
        ?listed_exchange: String?,
        ?metadata: ::Hash[Symbol, String],
        ?middle_name: String?,
        ?operating_jurisdictions: ::Array[String],
        ?phone_numbers: ::Array[ModernTreasury::LegalEntityUpdateParams::PhoneNumber],
        ?politically_exposed_person: bool?,
        ?preferred_name: String?,
        ?prefix: String?,
        ?primary_social_media_sites: ::Array[String],
        ?regulators: ::Array[ModernTreasury::LegalEntityUpdateParams::Regulator]?,
        ?risk_rating: ModernTreasury::Models::LegalEntityUpdateParams::risk_rating?,
        ?status: ModernTreasury::Models::LegalEntityUpdateParams::status?,
        ?suffix: String?,
        ?third_party_verification: ModernTreasury::LegalEntityUpdateParams::ThirdPartyVerification?,
        ?ticker_symbol: String?,
        ?wealth_and_employment_details: ModernTreasury::LegalEntityWealthEmploymentDetail?,
        ?website: String?,
        ?request_options: ModernTreasury::request_opts
      ) -> ModernTreasury::LegalEntity

      def list: (
        ?after_cursor: String?,
        ?legal_entity_type: ModernTreasury::Models::LegalEntityListParams::legal_entity_type,
        ?metadata: ::Hash[Symbol, String],
        ?per_page: Integer,
        ?show_deleted: String,
        ?status: ModernTreasury::Models::LegalEntityListParams::status,
        ?request_options: ModernTreasury::request_opts
      ) -> ModernTreasury::Internal::Page[ModernTreasury::LegalEntity]

      def initialize: (client: ModernTreasury::Client) -> void
    end
  end
end
