module ModernTreasury
  module Resources
    class LineItems
      def retrieve: (
        String id,
        itemizable_type: ModernTreasury::Models::LineItemRetrieveParams::itemizable_type,
        itemizable_id: String,
        ?request_options: ModernTreasury::request_opts
      ) -> ModernTreasury::Models::LineItem

      def update: (
        String id,
        itemizable_type: ModernTreasury::Models::LineItemUpdateParams::itemizable_type,
        itemizable_id: String,
        ?metadata: ::Hash[Symbol, String],
        ?request_options: ModernTreasury::request_opts
      ) -> ModernTreasury::Models::LineItem

      def list: (
        String itemizable_id,
        itemizable_type: ModernTreasury::Models::LineItemListParams::itemizable_type,
        ?after_cursor: String?,
        ?per_page: Integer,
        ?request_options: ModernTreasury::request_opts
      ) -> ModernTreasury::Page[ModernTreasury::Models::LineItem]

      def initialize: (client: ModernTreasury::Client) -> void
    end
  end
end
