module ModernTreasury
  module Resources
    class PaperItems
      def retrieve:
        (
          String id,
          ?ModernTreasury::Models::PaperItemRetrieveParams
          | Hash[Symbol, top] params
        ) -> ModernTreasury::Models::PaperItem
        | (
          String id,
          request_options: ModernTreasury::request_opts
        ) -> ModernTreasury::Models::PaperItem

      def list:
        (
          ?ModernTreasury::Models::PaperItemListParams
          | Hash[Symbol, top] params
        ) -> ModernTreasury::Page[ModernTreasury::Models::PaperItem]
        | (
          after_cursor: String?,
          deposit_date_end: Date,
          deposit_date_start: Date,
          lockbox_number: String,
          per_page: Integer,
          request_options: ModernTreasury::request_opts
        ) -> ModernTreasury::Page[ModernTreasury::Models::PaperItem]

      def initialize: (client: ModernTreasury::Client) -> void
    end
  end
end
