module ModernTreasury
  module Resources
    class PaymentOrders
      attr_reader reversals: ModernTreasury::Resources::PaymentOrders::Reversals

      def create: (
        amount: Integer,
        direction: ModernTreasury::Models::PaymentOrderCreateParams::direction,
        originating_account_id: String,
        type: ModernTreasury::Models::payment_order_type,
        ?accounting: ModernTreasury::PaymentOrderCreateParams::Accounting,
        ?accounting_category_id: String?,
        ?accounting_ledger_class_id: String?,
        ?charge_bearer: ModernTreasury::Models::PaymentOrderCreateParams::charge_bearer?,
        ?currency: ModernTreasury::Models::currency,
        ?description: String?,
        ?documents: ::Array[ModernTreasury::PaymentOrderCreateParams::Document],
        ?effective_date: Date,
        ?expires_at: Time?,
        ?fallback_type: ModernTreasury::Models::PaymentOrderCreateParams::fallback_type,
        ?foreign_exchange_contract: String?,
        ?foreign_exchange_indicator: ModernTreasury::Models::PaymentOrderCreateParams::foreign_exchange_indicator?,
        ?ledger_transaction: ModernTreasury::PaymentOrderCreateParams::LedgerTransaction,
        ?ledger_transaction_id: String,
        ?line_items: ::Array[ModernTreasury::PaymentOrderCreateParams::LineItem],
        ?metadata: ::Hash[Symbol, String],
        ?nsf_protected: bool,
        ?originating_party_name: String?,
        ?priority: ModernTreasury::Models::PaymentOrderCreateParams::priority,
        ?process_after: Time?,
        ?purpose: String?,
        ?receiving_account: ModernTreasury::PaymentOrderCreateParams::ReceivingAccount,
        ?receiving_account_id: String,
        ?remittance_information: String?,
        ?send_remittance_advice: bool?,
        ?statement_descriptor: String?,
        ?subtype: ModernTreasury::Models::payment_order_subtype?,
        ?transaction_monitoring_enabled: bool,
        ?ultimate_originating_party_identifier: String?,
        ?ultimate_originating_party_name: String?,
        ?ultimate_receiving_party_identifier: String?,
        ?ultimate_receiving_party_name: String?,
        ?request_options: ModernTreasury::request_opts
      ) -> ModernTreasury::PaymentOrder

      def retrieve: (
        String id,
        ?request_options: ModernTreasury::request_opts
      ) -> ModernTreasury::PaymentOrder

      def update: (
        String id,
        ?accounting: ModernTreasury::PaymentOrderUpdateParams::Accounting,
        ?accounting_category_id: String?,
        ?accounting_ledger_class_id: String?,
        ?amount: Integer,
        ?charge_bearer: ModernTreasury::Models::PaymentOrderUpdateParams::charge_bearer?,
        ?counterparty_id: String?,
        ?currency: ModernTreasury::Models::currency,
        ?description: String?,
        ?direction: ModernTreasury::Models::PaymentOrderUpdateParams::direction,
        ?effective_date: Date,
        ?expires_at: Time?,
        ?fallback_type: ModernTreasury::Models::PaymentOrderUpdateParams::fallback_type,
        ?foreign_exchange_contract: String?,
        ?foreign_exchange_indicator: ModernTreasury::Models::PaymentOrderUpdateParams::foreign_exchange_indicator?,
        ?line_items: ::Array[ModernTreasury::PaymentOrderUpdateParams::LineItem],
        ?metadata: ::Hash[Symbol, String],
        ?nsf_protected: bool,
        ?originating_account_id: String,
        ?originating_party_name: String?,
        ?priority: ModernTreasury::Models::PaymentOrderUpdateParams::priority,
        ?process_after: Time?,
        ?purpose: String?,
        ?receiving_account: ModernTreasury::PaymentOrderUpdateParams::ReceivingAccount,
        ?receiving_account_id: String,
        ?remittance_information: String?,
        ?send_remittance_advice: bool?,
        ?statement_descriptor: String?,
        ?status: ModernTreasury::Models::PaymentOrderUpdateParams::status,
        ?subtype: ModernTreasury::Models::payment_order_subtype?,
        ?type: ModernTreasury::Models::payment_order_type,
        ?ultimate_originating_party_identifier: String?,
        ?ultimate_originating_party_name: String?,
        ?ultimate_receiving_party_identifier: String?,
        ?ultimate_receiving_party_name: String?,
        ?request_options: ModernTreasury::request_opts
      ) -> ModernTreasury::PaymentOrder

      def list: (
        ?after_cursor: String?,
        ?counterparty_id: String,
        ?created_at_end: Date,
        ?created_at_start: Date,
        ?direction: ModernTreasury::Models::transaction_direction,
        ?effective_date_end: Date,
        ?effective_date_start: Date,
        ?external_id: String,
        ?metadata: ::Hash[Symbol, String],
        ?originating_account_id: String,
        ?per_page: Integer,
        ?priority: ModernTreasury::Models::PaymentOrderListParams::priority,
        ?process_after_end: Time,
        ?process_after_start: Time,
        ?reference_number: String,
        ?status: ModernTreasury::Models::PaymentOrderListParams::status,
        ?transaction_id: String,
        ?type: ModernTreasury::Models::PaymentOrderListParams::type_,
        ?request_options: ModernTreasury::request_opts
      ) -> ModernTreasury::Internal::Page[ModernTreasury::PaymentOrder]

      def create_async: (
        amount: Integer,
        direction: ModernTreasury::Models::PaymentOrderCreateAsyncParams::direction,
        originating_account_id: String,
        type: ModernTreasury::Models::payment_order_type,
        ?accounting: ModernTreasury::PaymentOrderCreateAsyncParams::Accounting,
        ?accounting_category_id: String?,
        ?accounting_ledger_class_id: String?,
        ?charge_bearer: ModernTreasury::Models::PaymentOrderCreateAsyncParams::charge_bearer?,
        ?currency: ModernTreasury::Models::currency,
        ?description: String?,
        ?effective_date: Date,
        ?expires_at: Time?,
        ?fallback_type: ModernTreasury::Models::PaymentOrderCreateAsyncParams::fallback_type,
        ?foreign_exchange_contract: String?,
        ?foreign_exchange_indicator: ModernTreasury::Models::PaymentOrderCreateAsyncParams::foreign_exchange_indicator?,
        ?ledger_transaction: ModernTreasury::PaymentOrderCreateAsyncParams::LedgerTransaction,
        ?ledger_transaction_id: String,
        ?line_items: ::Array[ModernTreasury::PaymentOrderCreateAsyncParams::LineItem],
        ?metadata: ::Hash[Symbol, String],
        ?nsf_protected: bool,
        ?originating_party_name: String?,
        ?priority: ModernTreasury::Models::PaymentOrderCreateAsyncParams::priority,
        ?process_after: Time?,
        ?purpose: String?,
        ?receiving_account: ModernTreasury::PaymentOrderCreateAsyncParams::ReceivingAccount,
        ?receiving_account_id: String,
        ?remittance_information: String?,
        ?send_remittance_advice: bool?,
        ?statement_descriptor: String?,
        ?subtype: ModernTreasury::Models::payment_order_subtype?,
        ?transaction_monitoring_enabled: bool,
        ?ultimate_originating_party_identifier: String?,
        ?ultimate_originating_party_name: String?,
        ?ultimate_receiving_party_identifier: String?,
        ?ultimate_receiving_party_name: String?,
        ?request_options: ModernTreasury::request_opts
      ) -> ModernTreasury::AsyncResponse

      def initialize: (client: ModernTreasury::Client) -> void
    end
  end
end
