module ModernTreasury
  module Resources
    class Returns
      def create: (
        returnable_id: String?,
        returnable_type: ModernTreasury::Models::ReturnCreateParams::returnable_type,
        ?additional_information: String?,
        ?code: ModernTreasury::Models::ReturnCreateParams::code?,
        ?data: top?,
        ?date_of_death: Date?,
        ?reason: String?,
        ?request_options: ModernTreasury::request_opts
      ) -> ModernTreasury::Models::ReturnObject

      def retrieve: (
        String id,
        ?request_options: ModernTreasury::request_opts
      ) -> ModernTreasury::Models::ReturnObject

      def list: (
        ?after_cursor: String?,
        ?counterparty_id: String,
        ?internal_account_id: String,
        ?per_page: Integer,
        ?returnable_id: String,
        ?returnable_type: ModernTreasury::Models::ReturnListParams::returnable_type,
        ?request_options: ModernTreasury::request_opts
      ) -> ModernTreasury::Internal::Page[ModernTreasury::Models::ReturnObject]

      def initialize: (client: ModernTreasury::Client) -> void
    end
  end
end
