module ModernTreasury
  module Models
    module Transactions
      type line_item_delete_params = {  } & ModernTreasury::request_parameters

      class LineItemDeleteParams < ModernTreasury::BaseModel
        extend ModernTreasury::RequestParameters::Converter
        include ModernTreasury::RequestParameters

        def initialize:
          (request_options: ModernTreasury::request_opts) -> void
          | (
            ?ModernTreasury::Models::Transactions::line_item_delete_params
            | ModernTreasury::BaseModel data
          ) -> void

        def to_h: -> ModernTreasury::Models::Transactions::line_item_delete_params
      end
    end
  end
end
