module ModernTreasury
  module Models
    module Transactions
      type line_item_delete_params =
        {  } & ModernTreasury::Internal::Type::request_parameters

      class LineItemDeleteParams < ModernTreasury::Internal::Type::BaseModel
        extend ModernTreasury::Internal::Type::RequestParameters::Converter
        include ModernTreasury::Internal::Type::RequestParameters

        def initialize: (?request_options: ModernTreasury::request_opts) -> void
      end
    end
  end
end
