module ModernTreasury
  module Models
    module Transactions
      type line_item_retrieve_params =
        {  } & ModernTreasury::Internal::Type::request_parameters

      class LineItemRetrieveParams < ModernTreasury::BaseModel
        extend ModernTreasury::Internal::Type::RequestParameters::Converter
        include ModernTreasury::Internal::Type::RequestParameters

        def initialize: (?request_options: ModernTreasury::request_opts) -> void

        def to_hash: -> ModernTreasury::Models::Transactions::line_item_retrieve_params
      end
    end
  end
end
