module ModernTreasury
  module Models
    module Transactions
      type line_item_retrieve_params = {  } & ModernTreasury::request_parameters

      class LineItemRetrieveParams < ModernTreasury::BaseModel
        extend ModernTreasury::RequestParameters::Converter
        include ModernTreasury::RequestParameters

        def initialize: (?request_options: ModernTreasury::request_opts) -> void

        def to_hash: -> ModernTreasury::Models::Transactions::line_item_retrieve_params
      end
    end
  end
end
