module ModernTreasury
  module Models
    type accounting = { account_id: String?, class_id: String? }

    class Accounting < ModernTreasury::Internal::Type::BaseModel
      attr_accessor account_id: String?

      attr_accessor class_id: String?

      def initialize: (?account_id: String?, ?class_id: String?) -> void

      def to_hash: -> { account_id: String?, class_id: String? }
    end
  end
end
