module ModernTreasury
  module Models
    type accounts_type = :external_accounts | :internal_accounts

    module AccountsType
      extend ModernTreasury::Internal::Type::Enum

      EXTERNAL_ACCOUNTS: :external_accounts
      INTERNAL_ACCOUNTS: :internal_accounts

      def self?.values: -> ::Array[ModernTreasury::Models::accounts_type]
    end
  end
end
