module ModernTreasury
  module Models
    type account_collection_flow_list_params =
      {
        after_cursor: String?,
        client_token: String,
        counterparty_id: String,
        external_account_id: String,
        per_page: Integer,
        status: String
      }
      & ModernTreasury::request_parameters

    class AccountCollectionFlowListParams < ModernTreasury::BaseModel
      extend ModernTreasury::RequestParameters::Converter
      include ModernTreasury::RequestParameters

      attr_accessor after_cursor: String?

      attr_reader client_token: String?

      def client_token=: (String) -> String

      attr_reader counterparty_id: String?

      def counterparty_id=: (String) -> String

      attr_reader external_account_id: String?

      def external_account_id=: (String) -> String

      attr_reader per_page: Integer?

      def per_page=: (Integer) -> Integer

      attr_reader status: String?

      def status=: (String) -> String

      def initialize:
        (
          ?after_cursor: String?,
          ?client_token: String,
          ?counterparty_id: String,
          ?external_account_id: String,
          ?per_page: Integer,
          ?status: String,
          ?request_options: ModernTreasury::request_opts
        ) -> void
        | (
          ?ModernTreasury::Models::account_collection_flow_list_params
          | ModernTreasury::BaseModel data
        ) -> void

      def to_hash: -> ModernTreasury::Models::account_collection_flow_list_params
    end
  end
end
