module ModernTreasury
  module Models
    type account_detail_retrieve_params =
      {
        accounts_type: ModernTreasury::Models::accounts_type,
        account_id: String
      }
      & ModernTreasury::Internal::Type::request_parameters

    class AccountDetailRetrieveParams < ModernTreasury::Internal::Type::BaseModel
      extend ModernTreasury::Internal::Type::RequestParameters::Converter
      include ModernTreasury::Internal::Type::RequestParameters

      attr_accessor accounts_type: ModernTreasury::Models::accounts_type

      attr_accessor account_id: String

      def initialize: (
        accounts_type: ModernTreasury::Models::accounts_type,
        account_id: String,
        ?request_options: ModernTreasury::request_opts
      ) -> void

      def to_hash: -> {
        accounts_type: ModernTreasury::Models::accounts_type,
        account_id: String,
        request_options: ModernTreasury::RequestOptions
      }
    end
  end
end
