module ModernTreasury
  module Models
    type account_collection_flow_create_params =
      {
        counterparty_id: String,
        payment_types: ::Array[String],
        receiving_countries: ::Array[ModernTreasury::Models::AccountCollectionFlowCreateParams::receiving_country]
      }
      & ModernTreasury::Internal::Type::request_parameters

    class AccountCollectionFlowCreateParams < ModernTreasury::Internal::Type::BaseModel
      extend ModernTreasury::Internal::Type::RequestParameters::Converter
      include ModernTreasury::Internal::Type::RequestParameters

      attr_accessor counterparty_id: String

      attr_accessor payment_types: ::Array[String]

      attr_reader receiving_countries: ::Array[ModernTreasury::Models::AccountCollectionFlowCreateParams::receiving_country]?

      def receiving_countries=: (
        ::Array[ModernTreasury::Models::AccountCollectionFlowCreateParams::receiving_country]
      ) -> ::Array[ModernTreasury::Models::AccountCollectionFlowCreateParams::receiving_country]

      def initialize: (
        counterparty_id: String,
        payment_types: ::Array[String],
        ?receiving_countries: ::Array[ModernTreasury::Models::AccountCollectionFlowCreateParams::receiving_country],
        ?request_options: ModernTreasury::request_opts
      ) -> void

      def to_hash: -> ModernTreasury::Models::account_collection_flow_create_params

      type receiving_country =
        :USA
        | :AUS
        | :BEL
        | :CAN
        | :CHL
        | :CHN
        | :COL
        | :FRA
        | :DEU
        | :HKG
        | :IND
        | :IRL
        | :ITA
        | :MEX
        | :NLD
        | :PER
        | :ESP
        | :GBR

      module ReceivingCountry
        extend ModernTreasury::Internal::Type::Enum

        USA: :USA
        AUS: :AUS
        BEL: :BEL
        CAN: :CAN
        CHL: :CHL
        CHN: :CHN
        COL: :COL
        FRA: :FRA
        DEU: :DEU
        HKG: :HKG
        IND: :IND
        IRL: :IRL
        ITA: :ITA
        MEX: :MEX
        NLD: :NLD
        PER: :PER
        ESP: :ESP
        GBR: :GBR

        def self?.values: -> ::Array[ModernTreasury::Models::AccountCollectionFlowCreateParams::receiving_country]
      end
    end
  end
end
