module ModernTreasury
  module Models
    type account_collection_flow_update_params =
      {
        status: ModernTreasury::Models::AccountCollectionFlowUpdateParams::status
      }
      & ModernTreasury::request_parameters

    class AccountCollectionFlowUpdateParams < ModernTreasury::BaseModel
      extend ModernTreasury::Type::RequestParameters::Converter
      include ModernTreasury::RequestParameters

      attr_accessor status: ModernTreasury::Models::AccountCollectionFlowUpdateParams::status

      def initialize: (
        status: ModernTreasury::Models::AccountCollectionFlowUpdateParams::status,
        ?request_options: ModernTreasury::request_opts
      ) -> void

      def to_hash: -> ModernTreasury::Models::account_collection_flow_update_params

      type status = :cancelled

      module Status
        extend ModernTreasury::Enum

        CANCELLED: :cancelled

        def self?.values: -> ::Array[ModernTreasury::Models::AccountCollectionFlowUpdateParams::status]
      end
    end
  end
end
