module ModernTreasury
  module Models
    type account_collection_flow_retrieve_params =
      {  } & ModernTreasury::request_parameters

    class AccountCollectionFlowRetrieveParams < ModernTreasury::BaseModel
      extend ModernTreasury::RequestParameters::Converter
      include ModernTreasury::RequestParameters

      def initialize:
        (?request_options: ModernTreasury::request_opts) -> void
        | (
          ?ModernTreasury::Models::account_collection_flow_retrieve_params
          | ModernTreasury::BaseModel data
        ) -> void

      def to_hash: -> ModernTreasury::Models::account_collection_flow_retrieve_params
    end
  end
end
