module ModernTreasury
  module Models
    type account_collection_flow_update_params =
      {
        status: ModernTreasury::Models::AccountCollectionFlowUpdateParams::status
      }
      & ModernTreasury::Internal::Type::request_parameters

    class AccountCollectionFlowUpdateParams < ModernTreasury::Internal::Type::BaseModel
      extend ModernTreasury::Internal::Type::RequestParameters::Converter
      include ModernTreasury::Internal::Type::RequestParameters

      attr_accessor status: ModernTreasury::Models::AccountCollectionFlowUpdateParams::status

      def initialize: (
        status: ModernTreasury::Models::AccountCollectionFlowUpdateParams::status,
        ?request_options: ModernTreasury::request_opts
      ) -> void

      type status = :cancelled

      module Status
        extend ModernTreasury::Internal::Type::Enum

        CANCELLED: :cancelled

        def self?.values: -> ::Array[ModernTreasury::Models::AccountCollectionFlowUpdateParams::status]
      end
    end
  end
end
