module ModernTreasury
  module Models
    type async_response = { id: String, object: String }

    class AsyncResponse < ModernTreasury::BaseModel
      attr_accessor id: String

      attr_accessor object: String

      def initialize: (id: String, object: String) -> void

      def to_hash: -> ModernTreasury::Models::async_response
    end
  end
end
