module ModernTreasury
  module Models
    type async_response = { id: String, object: String }

    class AsyncResponse < ModernTreasury::Internal::Type::BaseModel
      attr_accessor id: String

      attr_accessor object: String

      def initialize: (id: String, object: String) -> void

      def to_hash: -> { id: String, object: String }
    end
  end
end
