module ModernTreasury
  module Models
    type bulk_request_list_params =
      {
        action_type: ModernTreasury::Models::BulkRequestListParams::action_type,
        after_cursor: String?,
        metadata: ::Hash[Symbol, String],
        per_page: Integer,
        resource_type: ModernTreasury::Models::BulkRequestListParams::resource_type,
        status: ModernTreasury::Models::BulkRequestListParams::status
      }
      & ModernTreasury::Internal::Type::request_parameters

    class BulkRequestListParams < ModernTreasury::BaseModel
      extend ModernTreasury::Internal::Type::RequestParameters::Converter
      include ModernTreasury::Internal::Type::RequestParameters

      attr_reader action_type: ModernTreasury::Models::BulkRequestListParams::action_type?

      def action_type=: (
        ModernTreasury::Models::BulkRequestListParams::action_type
      ) -> ModernTreasury::Models::BulkRequestListParams::action_type

      attr_accessor after_cursor: String?

      attr_reader metadata: ::Hash[Symbol, String]?

      def metadata=: (::Hash[Symbol, String]) -> ::Hash[Symbol, String]

      attr_reader per_page: Integer?

      def per_page=: (Integer) -> Integer

      attr_reader resource_type: ModernTreasury::Models::BulkRequestListParams::resource_type?

      def resource_type=: (
        ModernTreasury::Models::BulkRequestListParams::resource_type
      ) -> ModernTreasury::Models::BulkRequestListParams::resource_type

      attr_reader status: ModernTreasury::Models::BulkRequestListParams::status?

      def status=: (
        ModernTreasury::Models::BulkRequestListParams::status
      ) -> ModernTreasury::Models::BulkRequestListParams::status

      def initialize: (
        ?action_type: ModernTreasury::Models::BulkRequestListParams::action_type,
        ?after_cursor: String?,
        ?metadata: ::Hash[Symbol, String],
        ?per_page: Integer,
        ?resource_type: ModernTreasury::Models::BulkRequestListParams::resource_type,
        ?status: ModernTreasury::Models::BulkRequestListParams::status,
        ?request_options: ModernTreasury::request_opts
      ) -> void

      def to_hash: -> ModernTreasury::Models::bulk_request_list_params

      type action_type = :create | :update | :delete

      module ActionType
        extend ModernTreasury::Enum

        CREATE: :create
        UPDATE: :update
        DELETE: :delete

        def self?.values: -> ::Array[ModernTreasury::Models::BulkRequestListParams::action_type]
      end

      type resource_type =
        :payment_order
        | :ledger_account
        | :ledger_transaction
        | :expected_payment
        | :transaction
        | :entity_link

      module ResourceType
        extend ModernTreasury::Enum

        PAYMENT_ORDER: :payment_order
        LEDGER_ACCOUNT: :ledger_account
        LEDGER_TRANSACTION: :ledger_transaction
        EXPECTED_PAYMENT: :expected_payment
        TRANSACTION: :transaction
        ENTITY_LINK: :entity_link

        def self?.values: -> ::Array[ModernTreasury::Models::BulkRequestListParams::resource_type]
      end

      type status = :pending | :processing | :completed

      module Status
        extend ModernTreasury::Enum

        PENDING: :pending
        PROCESSING: :processing
        COMPLETED: :completed

        def self?.values: -> ::Array[ModernTreasury::Models::BulkRequestListParams::status]
      end
    end
  end
end
