module ModernTreasury
  module Models
    type bulk_request_create_params =
      {
        action_type: ModernTreasury::Models::BulkRequestCreateParams::action_type,
        resource_type: ModernTreasury::Models::BulkRequestCreateParams::resource_type,
        resources: ::Array[ModernTreasury::Models::BulkRequestCreateParams::resource],
        metadata: ::Hash[Symbol, String]
      }
      & ModernTreasury::Internal::Type::request_parameters

    class BulkRequestCreateParams < ModernTreasury::Internal::Type::BaseModel
      extend ModernTreasury::Internal::Type::RequestParameters::Converter
      include ModernTreasury::Internal::Type::RequestParameters

      attr_accessor action_type: ModernTreasury::Models::BulkRequestCreateParams::action_type

      attr_accessor resource_type: ModernTreasury::Models::BulkRequestCreateParams::resource_type

      attr_accessor resources: ::Array[ModernTreasury::Models::BulkRequestCreateParams::resource]

      attr_reader metadata: ::Hash[Symbol, String]?

      def metadata=: (::Hash[Symbol, String]) -> ::Hash[Symbol, String]

      def initialize: (
        action_type: ModernTreasury::Models::BulkRequestCreateParams::action_type,
        resource_type: ModernTreasury::Models::BulkRequestCreateParams::resource_type,
        resources: ::Array[ModernTreasury::Models::BulkRequestCreateParams::resource],
        ?metadata: ::Hash[Symbol, String],
        ?request_options: ModernTreasury::request_opts
      ) -> void

      def to_hash: -> {
        action_type: ModernTreasury::Models::BulkRequestCreateParams::action_type,
        resource_type: ModernTreasury::Models::BulkRequestCreateParams::resource_type,
        resources: ::Array[ModernTreasury::Models::BulkRequestCreateParams::resource],
        metadata: ::Hash[Symbol, String],
        request_options: ModernTreasury::RequestOptions
      }

      type action_type = :create | :update | :delete

      module ActionType
        extend ModernTreasury::Internal::Type::Enum

        CREATE: :create
        UPDATE: :update
        DELETE: :delete

        def self?.values: -> ::Array[ModernTreasury::Models::BulkRequestCreateParams::action_type]
      end

      type resource_type =
        :payment_order
        | :ledger_account
        | :ledger_transaction
        | :expected_payment
        | :transaction
        | :transaction_line_item
        | :entity_link

      module ResourceType
        extend ModernTreasury::Internal::Type::Enum

        PAYMENT_ORDER: :payment_order
        LEDGER_ACCOUNT: :ledger_account
        LEDGER_TRANSACTION: :ledger_transaction
        EXPECTED_PAYMENT: :expected_payment
        TRANSACTION: :transaction
        TRANSACTION_LINE_ITEM: :transaction_line_item
        ENTITY_LINK: :entity_link

        def self?.values: -> ::Array[ModernTreasury::Models::BulkRequestCreateParams::resource_type]
      end

      type resource =
        ModernTreasury::PaymentOrderAsyncCreate
        | ModernTreasury::ExpectedPaymentCreate
        | ModernTreasury::LedgerTransactionCreateRequest
        | ModernTreasury::LedgerAccountCreateRequest
        | ModernTreasury::TransactionCreate
        | ModernTreasury::BulkRequestCreateParams::Resource::ID
        | ModernTreasury::BulkRequestCreateParams::Resource::PaymentOrderUpdateRequestWithID
        | ModernTreasury::BulkRequestCreateParams::Resource::ExpectedPaymentUpdateRequestWithID
        | ModernTreasury::BulkRequestCreateParams::Resource::TransactionUpdateRequestWithID
        | ModernTreasury::BulkRequestCreateParams::Resource::LedgerTransactionUpdateRequestWithID

      module Resource
        extend ModernTreasury::Internal::Type::Union

        type id = { id: String }

        class ID < ModernTreasury::Internal::Type::BaseModel
          attr_reader id: String?

          def id=: (String) -> String

          def initialize: (?id: String) -> void

          def to_hash: -> { id: String }
        end

        type payment_order_update_request_with_id = { id: String }

        class PaymentOrderUpdateRequestWithID < ModernTreasury::Models::PaymentOrderUpdate
          def id: -> String?

          def id=: (String _) -> String

          def initialize: (?id: String) -> void

          def to_hash: -> { id: String }
        end

        type expected_payment_update_request_with_id = { id: String }

        class ExpectedPaymentUpdateRequestWithID < ModernTreasury::Models::ExpectedPaymentUpdate
          def id: -> String?

          def id=: (String _) -> String

          def initialize: (?id: String) -> void

          def to_hash: -> { id: String }
        end

        type transaction_update_request_with_id = { id: String }

        class TransactionUpdateRequestWithID < ModernTreasury::Models::TransactionUpdate
          def id: -> String?

          def id=: (String _) -> String

          def initialize: (?id: String) -> void

          def to_hash: -> { id: String }
        end

        type ledger_transaction_update_request_with_id = { id: String }

        class LedgerTransactionUpdateRequestWithID < ModernTreasury::Models::LedgerTransactionUpdate
          def id: -> String?

          def id=: (String _) -> String

          def initialize: (?id: String) -> void

          def to_hash: -> { id: String }
        end

        def self?.variants: -> ::Array[ModernTreasury::Models::BulkRequestCreateParams::resource]
      end
    end
  end
end
