module ModernTreasury
  module Models
    type connection_list_params =
      {
        after_cursor: String?,
        entity: String,
        per_page: Integer,
        vendor_customer_id: String
      }
      & ModernTreasury::Internal::Type::request_parameters

    class ConnectionListParams < ModernTreasury::Internal::Type::BaseModel
      extend ModernTreasury::Internal::Type::RequestParameters::Converter
      include ModernTreasury::Internal::Type::RequestParameters

      attr_accessor after_cursor: String?

      attr_reader entity: String?

      def entity=: (String) -> String

      attr_reader per_page: Integer?

      def per_page=: (Integer) -> Integer

      attr_reader vendor_customer_id: String?

      def vendor_customer_id=: (String) -> String

      def initialize: (
        ?after_cursor: String?,
        ?entity: String,
        ?per_page: Integer,
        ?vendor_customer_id: String,
        ?request_options: ModernTreasury::request_opts
      ) -> void

      def to_hash: -> {
        after_cursor: String?,
        entity: String,
        per_page: Integer,
        vendor_customer_id: String,
        request_options: ModernTreasury::RequestOptions
      }
    end
  end
end
