module ModernTreasury
  module Models
    type connection_legal_entity_retrieve_params =
      {  } & ModernTreasury::request_parameters

    class ConnectionLegalEntityRetrieveParams < ModernTreasury::BaseModel
      extend ModernTreasury::RequestParameters::Converter
      include ModernTreasury::RequestParameters

      def initialize: (?request_options: ModernTreasury::request_opts) -> void

      def to_hash: -> ModernTreasury::Models::connection_legal_entity_retrieve_params
    end
  end
end
