module ModernTreasury
  module Models
    type connection_legal_entity_update_params =
      {
        status: ModernTreasury::Models::ConnectionLegalEntityUpdateParams::status
      }
      & ModernTreasury::Internal::Type::request_parameters

    class ConnectionLegalEntityUpdateParams < ModernTreasury::Internal::Type::BaseModel
      extend ModernTreasury::Internal::Type::RequestParameters::Converter
      include ModernTreasury::Internal::Type::RequestParameters

      attr_reader status: ModernTreasury::Models::ConnectionLegalEntityUpdateParams::status?

      def status=: (
        ModernTreasury::Models::ConnectionLegalEntityUpdateParams::status
      ) -> ModernTreasury::Models::ConnectionLegalEntityUpdateParams::status

      def initialize: (
        ?status: ModernTreasury::Models::ConnectionLegalEntityUpdateParams::status,
        ?request_options: ModernTreasury::request_opts
      ) -> void

      type status = :processing

      module Status
        extend ModernTreasury::Internal::Type::Enum

        PROCESSING: :processing

        def self?.values: -> ::Array[ModernTreasury::Models::ConnectionLegalEntityUpdateParams::status]
      end
    end
  end
end
