module ModernTreasury
  module Models
    type contact_detail_create_request =
      {
        contact_identifier: String,
        contact_identifier_type: ModernTreasury::Models::ContactDetailCreateRequest::contact_identifier_type
      }

    class ContactDetailCreateRequest < ModernTreasury::Internal::Type::BaseModel
      attr_reader contact_identifier: String?

      def contact_identifier=: (String) -> String

      attr_reader contact_identifier_type: ModernTreasury::Models::ContactDetailCreateRequest::contact_identifier_type?

      def contact_identifier_type=: (
        ModernTreasury::Models::ContactDetailCreateRequest::contact_identifier_type
      ) -> ModernTreasury::Models::ContactDetailCreateRequest::contact_identifier_type

      def initialize: (
        ?contact_identifier: String,
        ?contact_identifier_type: ModernTreasury::Models::ContactDetailCreateRequest::contact_identifier_type
      ) -> void

      def to_hash: -> {
        contact_identifier: String,
        contact_identifier_type: ModernTreasury::Models::ContactDetailCreateRequest::contact_identifier_type
      }

      type contact_identifier_type = :email | :phone_number | :website

      module ContactIdentifierType
        extend ModernTreasury::Internal::Type::Enum

        EMAIL: :email
        PHONE_NUMBER: :phone_number
        WEBSITE: :website

        def self?.values: -> ::Array[ModernTreasury::Models::ContactDetailCreateRequest::contact_identifier_type]
      end
    end
  end
end
