module ModernTreasury
  module Models
    type document_retrieve_params =
      {  } & ModernTreasury::Internal::Type::request_parameters

    class DocumentRetrieveParams < ModernTreasury::Internal::Type::BaseModel
      extend ModernTreasury::Internal::Type::RequestParameters::Converter
      include ModernTreasury::Internal::Type::RequestParameters

      def initialize: (?request_options: ModernTreasury::request_opts) -> void

      def to_hash: -> ModernTreasury::Models::document_retrieve_params
    end
  end
end
