module ModernTreasury
  module Models
    type document_list_params =
      {
        after_cursor: String?,
        documentable_id: String,
        documentable_type: ModernTreasury::Models::DocumentListParams::documentable_type,
        per_page: Integer
      }
      & ModernTreasury::Internal::Type::request_parameters

    class DocumentListParams < ModernTreasury::Internal::Type::BaseModel
      extend ModernTreasury::Internal::Type::RequestParameters::Converter
      include ModernTreasury::Internal::Type::RequestParameters

      attr_accessor after_cursor: String?

      attr_reader documentable_id: String?

      def documentable_id=: (String) -> String

      attr_reader documentable_type: ModernTreasury::Models::DocumentListParams::documentable_type?

      def documentable_type=: (
        ModernTreasury::Models::DocumentListParams::documentable_type
      ) -> ModernTreasury::Models::DocumentListParams::documentable_type

      attr_reader per_page: Integer?

      def per_page=: (Integer) -> Integer

      def initialize: (
        ?after_cursor: String?,
        ?documentable_id: String,
        ?documentable_type: ModernTreasury::Models::DocumentListParams::documentable_type,
        ?per_page: Integer,
        ?request_options: ModernTreasury::request_opts
      ) -> void

      def to_hash: -> {
        after_cursor: String?,
        documentable_id: String,
        documentable_type: ModernTreasury::Models::DocumentListParams::documentable_type,
        per_page: Integer,
        request_options: ModernTreasury::RequestOptions
      }

      type documentable_type =
        :connection
        | :counterparty
        | :expected_payment
        | :external_account
        | :identification
        | :incoming_payment_detail
        | :internal_account
        | :legal_entity
        | :organization
        | :payment_order
        | :transaction

      module DocumentableType
        extend ModernTreasury::Internal::Type::Enum

        CONNECTION: :connection
        COUNTERPARTY: :counterparty
        EXPECTED_PAYMENT: :expected_payment
        EXTERNAL_ACCOUNT: :external_account
        IDENTIFICATION: :identification
        INCOMING_PAYMENT_DETAIL: :incoming_payment_detail
        INTERNAL_ACCOUNT: :internal_account
        LEGAL_ENTITY: :legal_entity
        ORGANIZATION: :organization
        PAYMENT_ORDER: :payment_order
        TRANSACTION: :transaction

        def self?.values: -> ::Array[ModernTreasury::Models::DocumentListParams::documentable_type]
      end
    end
  end
end
