module ModernTreasury
  module Models
    type event_list_params =
      {
        after_cursor: String?,
        entity_id: String,
        event_name: String,
        event_time_end: Time,
        event_time_start: Time,
        per_page: Integer,
        resource: String
      }
      & ModernTreasury::Internal::Type::request_parameters

    class EventListParams < ModernTreasury::Internal::Type::BaseModel
      extend ModernTreasury::Internal::Type::RequestParameters::Converter
      include ModernTreasury::Internal::Type::RequestParameters

      attr_accessor after_cursor: String?

      attr_reader entity_id: String?

      def entity_id=: (String) -> String

      attr_reader event_name: String?

      def event_name=: (String) -> String

      attr_reader event_time_end: Time?

      def event_time_end=: (Time) -> Time

      attr_reader event_time_start: Time?

      def event_time_start=: (Time) -> Time

      attr_reader per_page: Integer?

      def per_page=: (Integer) -> Integer

      attr_reader resource: String?

      def resource=: (String) -> String

      def initialize: (
        ?after_cursor: String?,
        ?entity_id: String,
        ?event_name: String,
        ?event_time_end: Time,
        ?event_time_start: Time,
        ?per_page: Integer,
        ?resource: String,
        ?request_options: ModernTreasury::request_opts
      ) -> void

      def to_hash: -> {
        after_cursor: String?,
        entity_id: String,
        event_name: String,
        event_time_end: Time,
        event_time_start: Time,
        per_page: Integer,
        resource: String,
        request_options: ModernTreasury::RequestOptions
      }
    end
  end
end
