module ModernTreasury
  module Models
    type expected_payment_create_params =
      {
        amount_lower_bound: Integer?,
        amount_reconciled: Integer?,
        amount_reconciled_direction: ModernTreasury::Models::ExpectedPaymentCreateParams::amount_reconciled_direction?,
        amount_unreconciled: Integer?,
        amount_unreconciled_direction: ModernTreasury::Models::ExpectedPaymentCreateParams::amount_unreconciled_direction?,
        amount_upper_bound: Integer?,
        counterparty_id: String?,
        currency: ModernTreasury::Models::ExpectedPaymentCreateParams::currency?,
        date_lower_bound: Date?,
        date_upper_bound: Date?,
        description: String?,
        direction: ModernTreasury::Models::ExpectedPaymentCreateParams::direction?,
        external_id: String?,
        internal_account_id: String?,
        ledger_transaction: ModernTreasury::LedgerTransactionCreateRequest,
        ledger_transaction_id: String,
        line_items: ::Array[ModernTreasury::ExpectedPaymentCreateParams::LineItem],
        metadata: ::Hash[Symbol, String],
        reconciliation_filters: top?,
        reconciliation_groups: top?,
        reconciliation_rule_variables: ::Array[ModernTreasury::ReconciliationRule],
        remittance_information: String?,
        statement_descriptor: String?,
        type: ModernTreasury::Models::expected_payment_type?
      }
      & ModernTreasury::Internal::Type::request_parameters

    class ExpectedPaymentCreateParams < ModernTreasury::Internal::Type::BaseModel
      extend ModernTreasury::Internal::Type::RequestParameters::Converter
      include ModernTreasury::Internal::Type::RequestParameters

      attr_accessor amount_lower_bound: Integer?

      attr_accessor amount_reconciled: Integer?

      attr_accessor amount_reconciled_direction: ModernTreasury::Models::ExpectedPaymentCreateParams::amount_reconciled_direction?

      attr_accessor amount_unreconciled: Integer?

      attr_accessor amount_unreconciled_direction: ModernTreasury::Models::ExpectedPaymentCreateParams::amount_unreconciled_direction?

      attr_accessor amount_upper_bound: Integer?

      attr_accessor counterparty_id: String?

      attr_accessor currency: ModernTreasury::Models::ExpectedPaymentCreateParams::currency?

      attr_accessor date_lower_bound: Date?

      attr_accessor date_upper_bound: Date?

      attr_accessor description: String?

      attr_accessor direction: ModernTreasury::Models::ExpectedPaymentCreateParams::direction?

      attr_accessor external_id: String?

      attr_accessor internal_account_id: String?

      attr_reader ledger_transaction: ModernTreasury::LedgerTransactionCreateRequest?

      def ledger_transaction=: (
        ModernTreasury::LedgerTransactionCreateRequest
      ) -> ModernTreasury::LedgerTransactionCreateRequest

      attr_reader ledger_transaction_id: String?

      def ledger_transaction_id=: (String) -> String

      attr_reader line_items: ::Array[ModernTreasury::ExpectedPaymentCreateParams::LineItem]?

      def line_items=: (
        ::Array[ModernTreasury::ExpectedPaymentCreateParams::LineItem]
      ) -> ::Array[ModernTreasury::ExpectedPaymentCreateParams::LineItem]

      attr_reader metadata: ::Hash[Symbol, String]?

      def metadata=: (::Hash[Symbol, String]) -> ::Hash[Symbol, String]

      attr_accessor reconciliation_filters: top?

      attr_accessor reconciliation_groups: top?

      attr_reader reconciliation_rule_variables: ::Array[ModernTreasury::ReconciliationRule]?

      def reconciliation_rule_variables=: (
        ::Array[ModernTreasury::ReconciliationRule]
      ) -> ::Array[ModernTreasury::ReconciliationRule]

      attr_accessor remittance_information: String?

      attr_accessor statement_descriptor: String?

      attr_accessor type: ModernTreasury::Models::expected_payment_type?

      def initialize: (
        ?amount_lower_bound: Integer?,
        ?amount_reconciled: Integer?,
        ?amount_reconciled_direction: ModernTreasury::Models::ExpectedPaymentCreateParams::amount_reconciled_direction?,
        ?amount_unreconciled: Integer?,
        ?amount_unreconciled_direction: ModernTreasury::Models::ExpectedPaymentCreateParams::amount_unreconciled_direction?,
        ?amount_upper_bound: Integer?,
        ?counterparty_id: String?,
        ?currency: ModernTreasury::Models::ExpectedPaymentCreateParams::currency?,
        ?date_lower_bound: Date?,
        ?date_upper_bound: Date?,
        ?description: String?,
        ?direction: ModernTreasury::Models::ExpectedPaymentCreateParams::direction?,
        ?external_id: String?,
        ?internal_account_id: String?,
        ?ledger_transaction: ModernTreasury::LedgerTransactionCreateRequest,
        ?ledger_transaction_id: String,
        ?line_items: ::Array[ModernTreasury::ExpectedPaymentCreateParams::LineItem],
        ?metadata: ::Hash[Symbol, String],
        ?reconciliation_filters: top?,
        ?reconciliation_groups: top?,
        ?reconciliation_rule_variables: ::Array[ModernTreasury::ReconciliationRule],
        ?remittance_information: String?,
        ?statement_descriptor: String?,
        ?type: ModernTreasury::Models::expected_payment_type?,
        ?request_options: ModernTreasury::request_opts
      ) -> void

      def to_hash: -> {
        amount_lower_bound: Integer?,
        amount_reconciled: Integer?,
        amount_reconciled_direction: ModernTreasury::Models::ExpectedPaymentCreateParams::amount_reconciled_direction?,
        amount_unreconciled: Integer?,
        amount_unreconciled_direction: ModernTreasury::Models::ExpectedPaymentCreateParams::amount_unreconciled_direction?,
        amount_upper_bound: Integer?,
        counterparty_id: String?,
        currency: ModernTreasury::Models::ExpectedPaymentCreateParams::currency?,
        date_lower_bound: Date?,
        date_upper_bound: Date?,
        description: String?,
        direction: ModernTreasury::Models::ExpectedPaymentCreateParams::direction?,
        external_id: String?,
        internal_account_id: String?,
        ledger_transaction: ModernTreasury::LedgerTransactionCreateRequest,
        ledger_transaction_id: String,
        line_items: ::Array[ModernTreasury::ExpectedPaymentCreateParams::LineItem],
        metadata: ::Hash[Symbol, String],
        reconciliation_filters: top?,
        reconciliation_groups: top?,
        reconciliation_rule_variables: ::Array[ModernTreasury::ReconciliationRule],
        remittance_information: String?,
        statement_descriptor: String?,
        type: ModernTreasury::Models::expected_payment_type?,
        request_options: ModernTreasury::RequestOptions
      }

      type amount_reconciled_direction = :credit | :debit

      module AmountReconciledDirection
        extend ModernTreasury::Internal::Type::Enum

        CREDIT: :credit
        DEBIT: :debit

        def self?.values: -> ::Array[ModernTreasury::Models::ExpectedPaymentCreateParams::amount_reconciled_direction]
      end

      type amount_unreconciled_direction = :credit | :debit

      module AmountUnreconciledDirection
        extend ModernTreasury::Internal::Type::Enum

        CREDIT: :credit
        DEBIT: :debit

        def self?.values: -> ::Array[ModernTreasury::Models::ExpectedPaymentCreateParams::amount_unreconciled_direction]
      end

      type currency =
        :AED
        | :AFN
        | :ALL
        | :AMD
        | :ANG
        | :AOA
        | :ARS
        | :AUD
        | :AWG
        | :AZN
        | :BAM
        | :BBD
        | :BCH
        | :BDT
        | :BGN
        | :BHD
        | :BIF
        | :BMD
        | :BND
        | :BOB
        | :BRL
        | :BSD
        | :BTC
        | :BTN
        | :BWP
        | :BYN
        | :BYR
        | :BZD
        | :CAD
        | :CDF
        | :CHF
        | :CLF
        | :CLP
        | :CNH
        | :CNY
        | :COP
        | :CRC
        | :CUC
        | :CUP
        | :CVE
        | :CZK
        | :DJF
        | :DKK
        | :DOP
        | :DZD
        | :EEK
        | :EGP
        | :ERN
        | :ETB
        | :ETH
        | :EUR
        | :EURC
        | :FJD
        | :FKP
        | :GBP
        | :GBX
        | :GEL
        | :GGP
        | :GHS
        | :GIP
        | :GMD
        | :GNF
        | :GTQ
        | :GYD
        | :HKD
        | :HNL
        | :HRK
        | :HTG
        | :HUF
        | :IDR
        | :ILS
        | :IMP
        | :INR
        | :IQD
        | :IRR
        | :ISK
        | :JEP
        | :JMD
        | :JOD
        | :JPY
        | :KES
        | :KGS
        | :KHR
        | :KMF
        | :KPW
        | :KRW
        | :KWD
        | :KYD
        | :KZT
        | :LAK
        | :LBP
        | :LKR
        | :LRD
        | :LSL
        | :LTL
        | :LVL
        | :LYD
        | :MAD
        | :MDL
        | :MGA
        | :MKD
        | :MMK
        | :MNT
        | :MOP
        | :MRO
        | :MRU
        | :MTL
        | :MUR
        | :MVR
        | :MWK
        | :MXN
        | :MYR
        | :MZN
        | :NAD
        | :NGN
        | :NIO
        | :NOK
        | :NPR
        | :NZD
        | :OMR
        | :OP
        | :PAB
        | :PEN
        | :PGK
        | :PHP
        | :PKR
        | :PLN
        | :PYG
        | :PYUSD
        | :QAR
        | :RON
        | :RSD
        | :RUB
        | :RWF
        | :SAR
        | :SBD
        | :SCR
        | :SDG
        | :SEK
        | :SGD
        | :SHP
        | :SKK
        | :SLE
        | :SLL
        | :SOS
        | :SRD
        | :SSP
        | :STD
        | :STN
        | :SVC
        | :SYP
        | :SZL
        | :THB
        | :TJS
        | :TMM
        | :TMT
        | :TND
        | :TOP
        | :TRY
        | :TTD
        | :TWD
        | :TZS
        | :UAH
        | :UGX
        | :USD
        | :USDC
        | :USDG
        | :USDT
        | :UYU
        | :UZS
        | :VEF
        | :VES
        | :VND
        | :VUV
        | :WST
        | :XAF
        | :XAG
        | :XAU
        | :XBA
        | :XBB
        | :XBC
        | :XBD
        | :XCD
        | :XCG
        | :XDR
        | :XFU
        | :XOF
        | :XPD
        | :XPF
        | :XPT
        | :XTS
        | :YER
        | :ZAR
        | :ZMK
        | :ZMW
        | :ZWD
        | :ZWG
        | :ZWL
        | :ZWN
        | :ZWR

      module Currency
        extend ModernTreasury::Internal::Type::Enum

        AED: :AED
        AFN: :AFN
        ALL: :ALL
        AMD: :AMD
        ANG: :ANG
        AOA: :AOA
        ARS: :ARS
        AUD: :AUD
        AWG: :AWG
        AZN: :AZN
        BAM: :BAM
        BBD: :BBD
        BCH: :BCH
        BDT: :BDT
        BGN: :BGN
        BHD: :BHD
        BIF: :BIF
        BMD: :BMD
        BND: :BND
        BOB: :BOB
        BRL: :BRL
        BSD: :BSD
        BTC: :BTC
        BTN: :BTN
        BWP: :BWP
        BYN: :BYN
        BYR: :BYR
        BZD: :BZD
        CAD: :CAD
        CDF: :CDF
        CHF: :CHF
        CLF: :CLF
        CLP: :CLP
        CNH: :CNH
        CNY: :CNY
        COP: :COP
        CRC: :CRC
        CUC: :CUC
        CUP: :CUP
        CVE: :CVE
        CZK: :CZK
        DJF: :DJF
        DKK: :DKK
        DOP: :DOP
        DZD: :DZD
        EEK: :EEK
        EGP: :EGP
        ERN: :ERN
        ETB: :ETB
        ETH: :ETH
        EUR: :EUR
        EURC: :EURC
        FJD: :FJD
        FKP: :FKP
        GBP: :GBP
        GBX: :GBX
        GEL: :GEL
        GGP: :GGP
        GHS: :GHS
        GIP: :GIP
        GMD: :GMD
        GNF: :GNF
        GTQ: :GTQ
        GYD: :GYD
        HKD: :HKD
        HNL: :HNL
        HRK: :HRK
        HTG: :HTG
        HUF: :HUF
        IDR: :IDR
        ILS: :ILS
        IMP: :IMP
        INR: :INR
        IQD: :IQD
        IRR: :IRR
        ISK: :ISK
        JEP: :JEP
        JMD: :JMD
        JOD: :JOD
        JPY: :JPY
        KES: :KES
        KGS: :KGS
        KHR: :KHR
        KMF: :KMF
        KPW: :KPW
        KRW: :KRW
        KWD: :KWD
        KYD: :KYD
        KZT: :KZT
        LAK: :LAK
        LBP: :LBP
        LKR: :LKR
        LRD: :LRD
        LSL: :LSL
        LTL: :LTL
        LVL: :LVL
        LYD: :LYD
        MAD: :MAD
        MDL: :MDL
        MGA: :MGA
        MKD: :MKD
        MMK: :MMK
        MNT: :MNT
        MOP: :MOP
        MRO: :MRO
        MRU: :MRU
        MTL: :MTL
        MUR: :MUR
        MVR: :MVR
        MWK: :MWK
        MXN: :MXN
        MYR: :MYR
        MZN: :MZN
        NAD: :NAD
        NGN: :NGN
        NIO: :NIO
        NOK: :NOK
        NPR: :NPR
        NZD: :NZD
        OMR: :OMR
        OP: :OP
        PAB: :PAB
        PEN: :PEN
        PGK: :PGK
        PHP: :PHP
        PKR: :PKR
        PLN: :PLN
        PYG: :PYG
        PYUSD: :PYUSD
        QAR: :QAR
        RON: :RON
        RSD: :RSD
        RUB: :RUB
        RWF: :RWF
        SAR: :SAR
        SBD: :SBD
        SCR: :SCR
        SDG: :SDG
        SEK: :SEK
        SGD: :SGD
        SHP: :SHP
        SKK: :SKK
        SLE: :SLE
        SLL: :SLL
        SOS: :SOS
        SRD: :SRD
        SSP: :SSP
        STD: :STD
        STN: :STN
        SVC: :SVC
        SYP: :SYP
        SZL: :SZL
        THB: :THB
        TJS: :TJS
        TMM: :TMM
        TMT: :TMT
        TND: :TND
        TOP: :TOP
        TRY: :TRY
        TTD: :TTD
        TWD: :TWD
        TZS: :TZS
        UAH: :UAH
        UGX: :UGX
        USD: :USD
        USDC: :USDC
        USDG: :USDG
        USDT: :USDT
        UYU: :UYU
        UZS: :UZS
        VEF: :VEF
        VES: :VES
        VND: :VND
        VUV: :VUV
        WST: :WST
        XAF: :XAF
        XAG: :XAG
        XAU: :XAU
        XBA: :XBA
        XBB: :XBB
        XBC: :XBC
        XBD: :XBD
        XCD: :XCD
        XCG: :XCG
        XDR: :XDR
        XFU: :XFU
        XOF: :XOF
        XPD: :XPD
        XPF: :XPF
        XPT: :XPT
        XTS: :XTS
        YER: :YER
        ZAR: :ZAR
        ZMK: :ZMK
        ZMW: :ZMW
        ZWD: :ZWD
        ZWG: :ZWG
        ZWL: :ZWL
        ZWN: :ZWN
        ZWR: :ZWR

        def self?.values: -> ::Array[ModernTreasury::Models::ExpectedPaymentCreateParams::currency]
      end

      type direction = :credit | :debit

      module Direction
        extend ModernTreasury::Internal::Type::Enum

        CREDIT: :credit
        DEBIT: :debit

        def self?.values: -> ::Array[ModernTreasury::Models::ExpectedPaymentCreateParams::direction]
      end

      type line_item =
        {
          amount: Integer,
          accounting_category_id: String?,
          description: String?,
          metadata: ::Hash[Symbol, String]
        }

      class LineItem < ModernTreasury::Internal::Type::BaseModel
        attr_accessor amount: Integer

        attr_accessor accounting_category_id: String?

        attr_accessor description: String?

        attr_reader metadata: ::Hash[Symbol, String]?

        def metadata=: (::Hash[Symbol, String]) -> ::Hash[Symbol, String]

        def initialize: (
          amount: Integer,
          ?accounting_category_id: String?,
          ?description: String?,
          ?metadata: ::Hash[Symbol, String]
        ) -> void

        def to_hash: -> {
          amount: Integer,
          accounting_category_id: String?,
          description: String?,
          metadata: ::Hash[Symbol, String]
        }
      end
    end
  end
end
