module ModernTreasury
  module Models
    type external_account_complete_verification_params =
      { amounts: ::Array[Integer] }
      & ModernTreasury::Internal::Type::request_parameters

    class ExternalAccountCompleteVerificationParams < ModernTreasury::Internal::Type::BaseModel
      extend ModernTreasury::Internal::Type::RequestParameters::Converter
      include ModernTreasury::Internal::Type::RequestParameters

      attr_reader amounts: ::Array[Integer]?

      def amounts=: (::Array[Integer]) -> ::Array[Integer]

      def initialize: (
        ?amounts: ::Array[Integer],
        ?request_options: ModernTreasury::request_opts
      ) -> void
    end
  end
end
