module ModernTreasury
  module Models
    type external_account_list_params =
      {
        after_cursor: String?,
        counterparty_id: String,
        metadata: ::Hash[Symbol, String],
        party_name: String,
        per_page: Integer
      }
      & ModernTreasury::Internal::Type::request_parameters

    class ExternalAccountListParams < ModernTreasury::Internal::Type::BaseModel
      extend ModernTreasury::Internal::Type::RequestParameters::Converter
      include ModernTreasury::Internal::Type::RequestParameters

      attr_accessor after_cursor: String?

      attr_reader counterparty_id: String?

      def counterparty_id=: (String) -> String

      attr_reader metadata: ::Hash[Symbol, String]?

      def metadata=: (::Hash[Symbol, String]) -> ::Hash[Symbol, String]

      attr_reader party_name: String?

      def party_name=: (String) -> String

      attr_reader per_page: Integer?

      def per_page=: (Integer) -> Integer

      def initialize: (
        ?after_cursor: String?,
        ?counterparty_id: String,
        ?metadata: ::Hash[Symbol, String],
        ?party_name: String,
        ?per_page: Integer,
        ?request_options: ModernTreasury::request_opts
      ) -> void
    end
  end
end
