module ModernTreasury
  module Models
    type foreign_exchange_quote_retrieve_params =
      { id: String } & ModernTreasury::Internal::Type::request_parameters

    class ForeignExchangeQuoteRetrieveParams < ModernTreasury::Internal::Type::BaseModel
      extend ModernTreasury::Internal::Type::RequestParameters::Converter
      include ModernTreasury::Internal::Type::RequestParameters

      attr_accessor id: String

      def initialize: (
        id: String,
        ?request_options: ModernTreasury::request_opts
      ) -> void

      def to_hash: -> {
        id: String,
        request_options: ModernTreasury::RequestOptions
      }
    end
  end
end
