module ModernTreasury
  module Models
    type incoming_payment_detail_list_params =
      {
        after_cursor: String?,
        as_of_date_end: Date,
        as_of_date_start: Date,
        direction: ModernTreasury::Models::transaction_direction,
        metadata: ::Hash[Symbol, String],
        per_page: Integer,
        status: ModernTreasury::Models::IncomingPaymentDetailListParams::status,
        type: ModernTreasury::Models::IncomingPaymentDetailListParams::type_,
        virtual_account_id: String
      }
      & ModernTreasury::request_parameters

    class IncomingPaymentDetailListParams < ModernTreasury::BaseModel
      extend ModernTreasury::Type::RequestParameters::Converter
      include ModernTreasury::RequestParameters

      attr_accessor after_cursor: String?

      attr_reader as_of_date_end: Date?

      def as_of_date_end=: (Date) -> Date

      attr_reader as_of_date_start: Date?

      def as_of_date_start=: (Date) -> Date

      attr_reader direction: ModernTreasury::Models::transaction_direction?

      def direction=: (
        ModernTreasury::Models::transaction_direction
      ) -> ModernTreasury::Models::transaction_direction

      attr_reader metadata: ::Hash[Symbol, String]?

      def metadata=: (::Hash[Symbol, String]) -> ::Hash[Symbol, String]

      attr_reader per_page: Integer?

      def per_page=: (Integer) -> Integer

      attr_reader status: ModernTreasury::Models::IncomingPaymentDetailListParams::status?

      def status=: (
        ModernTreasury::Models::IncomingPaymentDetailListParams::status
      ) -> ModernTreasury::Models::IncomingPaymentDetailListParams::status

      attr_reader type: ModernTreasury::Models::IncomingPaymentDetailListParams::type_?

      def type=: (
        ModernTreasury::Models::IncomingPaymentDetailListParams::type_
      ) -> ModernTreasury::Models::IncomingPaymentDetailListParams::type_

      attr_reader virtual_account_id: String?

      def virtual_account_id=: (String) -> String

      def initialize: (
        ?after_cursor: String?,
        ?as_of_date_end: Date,
        ?as_of_date_start: Date,
        ?direction: ModernTreasury::Models::transaction_direction,
        ?metadata: ::Hash[Symbol, String],
        ?per_page: Integer,
        ?status: ModernTreasury::Models::IncomingPaymentDetailListParams::status,
        ?type: ModernTreasury::Models::IncomingPaymentDetailListParams::type_,
        ?virtual_account_id: String,
        ?request_options: ModernTreasury::request_opts
      ) -> void

      def to_hash: -> ModernTreasury::Models::incoming_payment_detail_list_params

      type status = :completed | :pending | :returned

      module Status
        extend ModernTreasury::Enum

        COMPLETED: :completed
        PENDING: :pending
        RETURNED: :returned

        def self?.values: -> ::Array[ModernTreasury::Models::IncomingPaymentDetailListParams::status]
      end

      type type_ =
        :ach
        | :au_becs
        | :bacs
        | :book
        | :check
        | :eft
        | :interac
        | :neft
        | :nz_becs
        | :rtp
        | :sepa
        | :signet
        | :wire

      module Type
        extend ModernTreasury::Enum

        ACH: :ach
        AU_BECS: :au_becs
        BACS: :bacs
        BOOK: :book
        CHECK: :check
        EFT: :eft
        INTERAC: :interac
        NEFT: :neft
        NZ_BECS: :nz_becs
        RTP: :rtp
        SEPA: :sepa
        SIGNET: :signet
        WIRE: :wire

        def self?.values: -> ::Array[ModernTreasury::Models::IncomingPaymentDetailListParams::type_]
      end
    end
  end
end
