module ModernTreasury
  module Models
    type incoming_payment_detail_retrieve_params =
      {  } & ModernTreasury::request_parameters

    class IncomingPaymentDetailRetrieveParams < ModernTreasury::BaseModel
      extend ModernTreasury::Type::RequestParameters::Converter
      include ModernTreasury::RequestParameters

      def initialize: (?request_options: ModernTreasury::request_opts) -> void

      def to_hash: -> ModernTreasury::Models::incoming_payment_detail_retrieve_params
    end
  end
end
