module ModernTreasury
  module Models
    type incoming_payment_detail_create_async_params =
      {
        amount: Integer,
        as_of_date: Date?,
        currency: ModernTreasury::Models::currency?,
        data: top?,
        description: String?,
        direction: ModernTreasury::Models::IncomingPaymentDetailCreateAsyncParams::direction,
        internal_account_id: String,
        type: ModernTreasury::Models::IncomingPaymentDetailCreateAsyncParams::type_,
        virtual_account_id: String?
      }
      & ModernTreasury::Internal::Type::request_parameters

    class IncomingPaymentDetailCreateAsyncParams < ModernTreasury::Internal::Type::BaseModel
      extend ModernTreasury::Internal::Type::RequestParameters::Converter
      include ModernTreasury::Internal::Type::RequestParameters

      attr_reader amount: Integer?

      def amount=: (Integer) -> Integer

      attr_accessor as_of_date: Date?

      attr_accessor currency: ModernTreasury::Models::currency?

      attr_accessor data: top?

      attr_accessor description: String?

      attr_reader direction: ModernTreasury::Models::IncomingPaymentDetailCreateAsyncParams::direction?

      def direction=: (
        ModernTreasury::Models::IncomingPaymentDetailCreateAsyncParams::direction
      ) -> ModernTreasury::Models::IncomingPaymentDetailCreateAsyncParams::direction

      attr_reader internal_account_id: String?

      def internal_account_id=: (String) -> String

      attr_reader type: ModernTreasury::Models::IncomingPaymentDetailCreateAsyncParams::type_?

      def type=: (
        ModernTreasury::Models::IncomingPaymentDetailCreateAsyncParams::type_
      ) -> ModernTreasury::Models::IncomingPaymentDetailCreateAsyncParams::type_

      attr_accessor virtual_account_id: String?

      def initialize: (
        ?amount: Integer,
        ?as_of_date: Date?,
        ?currency: ModernTreasury::Models::currency?,
        ?data: top?,
        ?description: String?,
        ?direction: ModernTreasury::Models::IncomingPaymentDetailCreateAsyncParams::direction,
        ?internal_account_id: String,
        ?type: ModernTreasury::Models::IncomingPaymentDetailCreateAsyncParams::type_,
        ?virtual_account_id: String?,
        ?request_options: ModernTreasury::request_opts
      ) -> void

      def to_hash: -> {
        amount: Integer,
        as_of_date: Date?,
        currency: ModernTreasury::Models::currency?,
        data: top?,
        description: String?,
        direction: ModernTreasury::Models::IncomingPaymentDetailCreateAsyncParams::direction,
        internal_account_id: String,
        type: ModernTreasury::Models::IncomingPaymentDetailCreateAsyncParams::type_,
        virtual_account_id: String?,
        request_options: ModernTreasury::RequestOptions
      }

      type direction = :credit | :debit

      module Direction
        extend ModernTreasury::Internal::Type::Enum

        CREDIT: :credit
        DEBIT: :debit

        def self?.values: -> ::Array[ModernTreasury::Models::IncomingPaymentDetailCreateAsyncParams::direction]
      end

      type type_ =
        :ach
        | :au_becs
        | :bacs
        | :base
        | :book
        | :check
        | :eft
        | :ethereum
        | :interac
        | :neft
        | :nz_becs
        | :polygon
        | :rtp
        | :sepa
        | :signet
        | :solana
        | :wire
        | :zengin

      module Type
        extend ModernTreasury::Internal::Type::Enum

        ACH: :ach
        AU_BECS: :au_becs
        BACS: :bacs
        BASE: :base
        BOOK: :book
        CHECK: :check
        EFT: :eft
        ETHEREUM: :ethereum
        INTERAC: :interac
        NEFT: :neft
        NZ_BECS: :nz_becs
        POLYGON: :polygon
        RTP: :rtp
        SEPA: :sepa
        SIGNET: :signet
        SOLANA: :solana
        WIRE: :wire
        ZENGIN: :zengin

        def self?.values: -> ::Array[ModernTreasury::Models::IncomingPaymentDetailCreateAsyncParams::type_]
      end
    end
  end
end
