module ModernTreasury
  module Models
    type internal_account_update_params =
      {
        contra_ledger_account_id: String,
        counterparty_id: String,
        external_id: String?,
        ledger_account_id: String,
        metadata: ::Hash[Symbol, String],
        name: String,
        parent_account_id: String
      }
      & ModernTreasury::Internal::Type::request_parameters

    class InternalAccountUpdateParams < ModernTreasury::Internal::Type::BaseModel
      extend ModernTreasury::Internal::Type::RequestParameters::Converter
      include ModernTreasury::Internal::Type::RequestParameters

      attr_reader contra_ledger_account_id: String?

      def contra_ledger_account_id=: (String) -> String

      attr_reader counterparty_id: String?

      def counterparty_id=: (String) -> String

      attr_accessor external_id: String?

      attr_reader ledger_account_id: String?

      def ledger_account_id=: (String) -> String

      attr_reader metadata: ::Hash[Symbol, String]?

      def metadata=: (::Hash[Symbol, String]) -> ::Hash[Symbol, String]

      attr_reader name: String?

      def name=: (String) -> String

      attr_reader parent_account_id: String?

      def parent_account_id=: (String) -> String

      def initialize: (
        ?contra_ledger_account_id: String,
        ?counterparty_id: String,
        ?external_id: String?,
        ?ledger_account_id: String,
        ?metadata: ::Hash[Symbol, String],
        ?name: String,
        ?parent_account_id: String,
        ?request_options: ModernTreasury::request_opts
      ) -> void

      def to_hash: -> {
        contra_ledger_account_id: String,
        counterparty_id: String,
        external_id: String?,
        ledger_account_id: String,
        metadata: ::Hash[Symbol, String],
        name: String,
        parent_account_id: String,
        request_options: ModernTreasury::RequestOptions
      }
    end
  end
end
