module ModernTreasury
  module Models
    type invoice_list_params =
      {
        after_cursor: String?,
        counterparty_id: String,
        due_date_end: Date,
        due_date_start: Date,
        expected_payment_id: String,
        metadata: ::Hash[Symbol, String],
        number: String,
        originating_account_id: String,
        payment_order_id: String,
        per_page: Integer,
        status: ModernTreasury::Models::InvoiceListParams::status
      }
      & ModernTreasury::request_parameters

    class InvoiceListParams < ModernTreasury::BaseModel
      extend ModernTreasury::Type::RequestParameters::Converter
      include ModernTreasury::RequestParameters

      attr_accessor after_cursor: String?

      attr_reader counterparty_id: String?

      def counterparty_id=: (String) -> String

      attr_reader due_date_end: Date?

      def due_date_end=: (Date) -> Date

      attr_reader due_date_start: Date?

      def due_date_start=: (Date) -> Date

      attr_reader expected_payment_id: String?

      def expected_payment_id=: (String) -> String

      attr_reader metadata: ::Hash[Symbol, String]?

      def metadata=: (::Hash[Symbol, String]) -> ::Hash[Symbol, String]

      attr_reader number: String?

      def number=: (String) -> String

      attr_reader originating_account_id: String?

      def originating_account_id=: (String) -> String

      attr_reader payment_order_id: String?

      def payment_order_id=: (String) -> String

      attr_reader per_page: Integer?

      def per_page=: (Integer) -> Integer

      attr_reader status: ModernTreasury::Models::InvoiceListParams::status?

      def status=: (
        ModernTreasury::Models::InvoiceListParams::status
      ) -> ModernTreasury::Models::InvoiceListParams::status

      def initialize: (
        ?after_cursor: String?,
        ?counterparty_id: String,
        ?due_date_end: Date,
        ?due_date_start: Date,
        ?expected_payment_id: String,
        ?metadata: ::Hash[Symbol, String],
        ?number: String,
        ?originating_account_id: String,
        ?payment_order_id: String,
        ?per_page: Integer,
        ?status: ModernTreasury::Models::InvoiceListParams::status,
        ?request_options: ModernTreasury::request_opts
      ) -> void

      def to_hash: -> ModernTreasury::Models::invoice_list_params

      type status =
        :draft | :paid | :partially_paid | :payment_pending | :unpaid | :voided

      module Status
        extend ModernTreasury::Enum

        DRAFT: :draft
        PAID: :paid
        PARTIALLY_PAID: :partially_paid
        PAYMENT_PENDING: :payment_pending
        UNPAID: :unpaid
        VOIDED: :voided

        def self?.values: -> ::Array[ModernTreasury::Models::InvoiceListParams::status]
      end
    end
  end
end
