module ModernTreasury
  module Models
    type journal_report_update_params =
      { id: String, metadata: top, status: String }
      & ModernTreasury::Internal::Type::request_parameters

    class JournalReportUpdateParams < ModernTreasury::Internal::Type::BaseModel
      extend ModernTreasury::Internal::Type::RequestParameters::Converter
      include ModernTreasury::Internal::Type::RequestParameters

      attr_accessor id: String

      attr_reader metadata: top?

      def metadata=: (top) -> top

      attr_reader status: String?

      def status=: (String) -> String

      def initialize: (
        id: String,
        ?metadata: top,
        ?status: String,
        ?request_options: ModernTreasury::request_opts
      ) -> void

      def to_hash: -> {
        id: String,
        metadata: top,
        status: String,
        request_options: ModernTreasury::RequestOptions
      }
    end
  end
end
