module ModernTreasury
  module Models
    type ledger_account_update_params =
      {
        description: String?,
        external_id: String?,
        metadata: ::Hash[Symbol, String],
        name: String
      }
      & ModernTreasury::Internal::Type::request_parameters

    class LedgerAccountUpdateParams < ModernTreasury::Internal::Type::BaseModel
      extend ModernTreasury::Internal::Type::RequestParameters::Converter
      include ModernTreasury::Internal::Type::RequestParameters

      attr_accessor description: String?

      attr_accessor external_id: String?

      attr_reader metadata: ::Hash[Symbol, String]?

      def metadata=: (::Hash[Symbol, String]) -> ::Hash[Symbol, String]

      attr_reader name: String?

      def name=: (String) -> String

      def initialize: (
        ?description: String?,
        ?external_id: String?,
        ?metadata: ::Hash[Symbol, String],
        ?name: String,
        ?request_options: ModernTreasury::request_opts
      ) -> void

      def to_hash: -> {
        description: String?,
        external_id: String?,
        metadata: ::Hash[Symbol, String],
        name: String,
        request_options: ModernTreasury::RequestOptions
      }
    end
  end
end
