module ModernTreasury
  module Models
    type ledger_entry_update_params =
      { metadata: ::Hash[Symbol, String] }
      & ModernTreasury::Internal::Type::request_parameters

    class LedgerEntryUpdateParams < ModernTreasury::BaseModel
      extend ModernTreasury::Internal::Type::RequestParameters::Converter
      include ModernTreasury::Internal::Type::RequestParameters

      attr_reader metadata: ::Hash[Symbol, String]?

      def metadata=: (::Hash[Symbol, String]) -> ::Hash[Symbol, String]

      def initialize: (
        ?metadata: ::Hash[Symbol, String],
        ?request_options: ModernTreasury::request_opts
      ) -> void

      def to_hash: -> ModernTreasury::Models::ledger_entry_update_params
    end
  end
end
