module ModernTreasury
  module Models
    type ledger_account_statement_create_params =
      {
        effective_at_lower_bound: Time,
        effective_at_upper_bound: Time,
        ledger_account_id: String,
        description: String?,
        metadata: Hash[Symbol, String]
      }
      & ModernTreasury::request_parameters

    class LedgerAccountStatementCreateParams < ModernTreasury::BaseModel
      extend ModernTreasury::RequestParameters::Converter
      include ModernTreasury::RequestParameters

      attr_accessor effective_at_lower_bound: Time

      attr_accessor effective_at_upper_bound: Time

      attr_accessor ledger_account_id: String

      attr_accessor description: String?

      attr_reader metadata: Hash[Symbol, String]?

      def metadata=: (Hash[Symbol, String]) -> void

      def initialize:
        (
          effective_at_lower_bound: Time,
          effective_at_upper_bound: Time,
          ledger_account_id: String,
          description: String?,
          metadata: Hash[Symbol, String],
          request_options: ModernTreasury::request_opts
        ) -> void
        | (
          ?ModernTreasury::Models::ledger_account_statement_create_params
          | ModernTreasury::BaseModel data
        ) -> void

      def to_hash: -> ModernTreasury::Models::ledger_account_statement_create_params
    end
  end
end
