module ModernTreasury
  module Models
    type ledger_entry_retrieve_params =
      { show_balances: bool } & ModernTreasury::request_parameters

    class LedgerEntryRetrieveParams < ModernTreasury::BaseModel
      extend ModernTreasury::RequestParameters::Converter
      include ModernTreasury::RequestParameters

      attr_reader show_balances: bool?

      def show_balances=: (bool) -> void

      def initialize:
        (
          show_balances: bool,
          request_options: ModernTreasury::request_opts
        ) -> void
        | (
          ?ModernTreasury::Models::ledger_entry_retrieve_params
          | ModernTreasury::BaseModel data
        ) -> void

      def to_h: -> ModernTreasury::Models::ledger_entry_retrieve_params
    end
  end
end
