module ModernTreasury
  module Models
    type ledger_account_category_retrieve_params =
      {
        balances: ModernTreasury::Models::LedgerAccountCategoryRetrieveParams::Balances
      }
      & ModernTreasury::request_parameters

    class LedgerAccountCategoryRetrieveParams < ModernTreasury::BaseModel
      extend ModernTreasury::RequestParameters::Converter
      include ModernTreasury::RequestParameters

      attr_reader balances: ModernTreasury::Models::LedgerAccountCategoryRetrieveParams::Balances?

      def balances=: (
        ModernTreasury::Models::LedgerAccountCategoryRetrieveParams::Balances
      ) -> ModernTreasury::Models::LedgerAccountCategoryRetrieveParams::Balances

      def initialize: (
        ?balances: ModernTreasury::Models::LedgerAccountCategoryRetrieveParams::Balances,
        ?request_options: ModernTreasury::request_opts
      ) -> void

      def to_hash: -> ModernTreasury::Models::ledger_account_category_retrieve_params

      type balances = { as_of_date: Date, effective_at: Time }

      class Balances < ModernTreasury::BaseModel
        attr_reader as_of_date: Date?

        def as_of_date=: (Date) -> Date

        attr_reader effective_at: Time?

        def effective_at=: (Time) -> Time

        def initialize: (?as_of_date: Date, ?effective_at: Time) -> void

        def to_hash: -> ModernTreasury::Models::LedgerAccountCategoryRetrieveParams::balances
      end
    end
  end
end
