module ModernTreasury
  module Models
    type ledger_entry_retrieve_params =
      { show_balances: bool }
      & ModernTreasury::Internal::Type::request_parameters

    class LedgerEntryRetrieveParams < ModernTreasury::Internal::Type::BaseModel
      extend ModernTreasury::Internal::Type::RequestParameters::Converter
      include ModernTreasury::Internal::Type::RequestParameters

      attr_reader show_balances: bool?

      def show_balances=: (bool) -> bool

      def initialize: (
        ?show_balances: bool,
        ?request_options: ModernTreasury::request_opts
      ) -> void
    end
  end
end
