module ModernTreasury
  module Models
    type ledger_delete_params = {  } & ModernTreasury::request_parameters

    class LedgerDeleteParams < ModernTreasury::BaseModel
      extend ModernTreasury::RequestParameters::Converter
      include ModernTreasury::RequestParameters

      def initialize:
        (request_options: ModernTreasury::request_opts) -> void
        | (
          ?ModernTreasury::Models::ledger_delete_params
          | ModernTreasury::BaseModel data
        ) -> void

      def to_hash: -> ModernTreasury::Models::ledger_delete_params
    end
  end
end
