module ModernTreasury
  module Models
    type ledger_list_params =
      {
        id: ::Array[String],
        after_cursor: String?,
        metadata: ::Hash[Symbol, String],
        per_page: Integer,
        updated_at: ::Hash[Symbol, Time]
      }
      & ModernTreasury::request_parameters

    class LedgerListParams < ModernTreasury::BaseModel
      extend ModernTreasury::RequestParameters::Converter
      include ModernTreasury::RequestParameters

      attr_reader id: ::Array[String]?

      def id=: (::Array[String]) -> ::Array[String]

      attr_accessor after_cursor: String?

      attr_reader metadata: ::Hash[Symbol, String]?

      def metadata=: (::Hash[Symbol, String]) -> ::Hash[Symbol, String]

      attr_reader per_page: Integer?

      def per_page=: (Integer) -> Integer

      attr_reader updated_at: ::Hash[Symbol, Time]?

      def updated_at=: (::Hash[Symbol, Time]) -> ::Hash[Symbol, Time]

      def initialize:
        (
          id: ::Array[String],
          after_cursor: String?,
          metadata: ::Hash[Symbol, String],
          per_page: Integer,
          updated_at: ::Hash[Symbol, Time],
          request_options: ModernTreasury::request_opts
        ) -> void
        | (
          ?ModernTreasury::Models::ledger_list_params
          | ModernTreasury::BaseModel data
        ) -> void

      def to_hash: -> ModernTreasury::Models::ledger_list_params
    end
  end
end
