module ModernTreasury
  module Models
    type ledger_account_category_remove_nested_category_params =
      { id: String } & ModernTreasury::Internal::Type::request_parameters

    class LedgerAccountCategoryRemoveNestedCategoryParams < ModernTreasury::Internal::Type::BaseModel
      extend ModernTreasury::Internal::Type::RequestParameters::Converter
      include ModernTreasury::Internal::Type::RequestParameters

      attr_accessor id: String

      def initialize: (
        id: String,
        ?request_options: ModernTreasury::request_opts
      ) -> void
    end
  end
end
