module ModernTreasury
  module Models
    type ledger_account_balance_monitor_update_params =
      { description: String, metadata: ::Hash[Symbol, String] }
      & ModernTreasury::request_parameters

    class LedgerAccountBalanceMonitorUpdateParams < ModernTreasury::BaseModel
      extend ModernTreasury::RequestParameters::Converter
      include ModernTreasury::RequestParameters

      attr_reader description: String?

      def description=: (String) -> String

      attr_reader metadata: ::Hash[Symbol, String]?

      def metadata=: (::Hash[Symbol, String]) -> ::Hash[Symbol, String]

      def initialize: (
        ?description: String,
        ?metadata: ::Hash[Symbol, String],
        ?request_options: ModernTreasury::request_opts
      ) -> void

      def to_hash: -> ModernTreasury::Models::ledger_account_balance_monitor_update_params
    end
  end
end
