module ModernTreasury
  module Models
    type ledger_account_category_list_params =
      {
        id: ::Array[String],
        after_cursor: String?,
        balances: ModernTreasury::Models::LedgerAccountCategoryListParams::Balances,
        currency: String,
        ledger_account_id: String,
        ledger_id: String,
        metadata: ::Hash[Symbol, String],
        name: String,
        parent_ledger_account_category_id: String,
        per_page: Integer
      }
      & ModernTreasury::request_parameters

    class LedgerAccountCategoryListParams < ModernTreasury::BaseModel
      extend ModernTreasury::RequestParameters::Converter
      include ModernTreasury::RequestParameters

      attr_reader id: ::Array[String]?

      def id=: (::Array[String]) -> ::Array[String]

      attr_accessor after_cursor: String?

      attr_reader balances: ModernTreasury::Models::LedgerAccountCategoryListParams::Balances?

      def balances=: (
        ModernTreasury::Models::LedgerAccountCategoryListParams::Balances
      ) -> ModernTreasury::Models::LedgerAccountCategoryListParams::Balances

      attr_reader currency: String?

      def currency=: (String) -> String

      attr_reader ledger_account_id: String?

      def ledger_account_id=: (String) -> String

      attr_reader ledger_id: String?

      def ledger_id=: (String) -> String

      attr_reader metadata: ::Hash[Symbol, String]?

      def metadata=: (::Hash[Symbol, String]) -> ::Hash[Symbol, String]

      attr_reader name: String?

      def name=: (String) -> String

      attr_reader parent_ledger_account_category_id: String?

      def parent_ledger_account_category_id=: (String) -> String

      attr_reader per_page: Integer?

      def per_page=: (Integer) -> Integer

      def initialize:
        (
          id: ::Array[String],
          after_cursor: String?,
          balances: ModernTreasury::Models::LedgerAccountCategoryListParams::Balances,
          currency: String,
          ledger_account_id: String,
          ledger_id: String,
          metadata: ::Hash[Symbol, String],
          name: String,
          parent_ledger_account_category_id: String,
          per_page: Integer,
          request_options: ModernTreasury::request_opts
        ) -> void
        | (
          ?ModernTreasury::Models::ledger_account_category_list_params
          | ModernTreasury::BaseModel data
        ) -> void

      def to_hash: -> ModernTreasury::Models::ledger_account_category_list_params

      type balances = { effective_at: Time }

      class Balances < ModernTreasury::BaseModel
        attr_reader effective_at: Time?

        def effective_at=: (Time) -> Time

        def initialize:
          (effective_at: Time) -> void
          | (
            ?ModernTreasury::Models::LedgerAccountCategoryListParams::balances
            | ModernTreasury::BaseModel data
          ) -> void

        def to_hash: -> ModernTreasury::Models::LedgerAccountCategoryListParams::balances
      end
    end
  end
end
