module ModernTreasury
  module Models
    type ledger_account_category_delete_params =
      {  } & ModernTreasury::request_parameters

    class LedgerAccountCategoryDeleteParams < ModernTreasury::BaseModel
      extend ModernTreasury::RequestParameters::Converter
      include ModernTreasury::RequestParameters

      def initialize: (?request_options: ModernTreasury::request_opts) -> void

      def to_hash: -> ModernTreasury::Models::ledger_account_category_delete_params
    end
  end
end
