module ModernTreasury
  module Models
    type ledger_account_statement_create_params =
      {
        effective_at_lower_bound: Time,
        effective_at_upper_bound: Time,
        ledger_account_id: String,
        description: String?,
        metadata: ::Hash[Symbol, String]
      }
      & ModernTreasury::Internal::Type::request_parameters

    class LedgerAccountStatementCreateParams < ModernTreasury::Internal::Type::BaseModel
      extend ModernTreasury::Internal::Type::RequestParameters::Converter
      include ModernTreasury::Internal::Type::RequestParameters

      attr_accessor effective_at_lower_bound: Time

      attr_accessor effective_at_upper_bound: Time

      attr_accessor ledger_account_id: String

      attr_accessor description: String?

      attr_reader metadata: ::Hash[Symbol, String]?

      def metadata=: (::Hash[Symbol, String]) -> ::Hash[Symbol, String]

      def initialize: (
        effective_at_lower_bound: Time,
        effective_at_upper_bound: Time,
        ledger_account_id: String,
        ?description: String?,
        ?metadata: ::Hash[Symbol, String],
        ?request_options: ModernTreasury::request_opts
      ) -> void

      def to_hash: -> ModernTreasury::Models::ledger_account_statement_create_params
    end
  end
end
