module ModernTreasury
  module Models
    type ledger_account_category_remove_ledger_account_params =
      { id: String } & ModernTreasury::Internal::Type::request_parameters

    class LedgerAccountCategoryRemoveLedgerAccountParams < ModernTreasury::Internal::Type::BaseModel
      extend ModernTreasury::Internal::Type::RequestParameters::Converter
      include ModernTreasury::Internal::Type::RequestParameters

      attr_accessor id: String

      def initialize: (
        id: String,
        ?request_options: ModernTreasury::request_opts
      ) -> void

      def to_hash: -> ModernTreasury::Models::ledger_account_category_remove_ledger_account_params
    end
  end
end
