module ModernTreasury
  module Models
    type ledger_retrieve_params =
      {  } & ModernTreasury::Internal::Type::request_parameters

    class LedgerRetrieveParams < ModernTreasury::Internal::Type::BaseModel
      extend ModernTreasury::Internal::Type::RequestParameters::Converter
      include ModernTreasury::Internal::Type::RequestParameters

      def initialize: (?request_options: ModernTreasury::request_opts) -> void
    end
  end
end
