module ModernTreasury
  module Models
    type ledger_account_balance_monitor_delete_params =
      {  } & ModernTreasury::request_parameters

    class LedgerAccountBalanceMonitorDeleteParams < ModernTreasury::BaseModel
      extend ModernTreasury::RequestParameters::Converter
      include ModernTreasury::RequestParameters

      def initialize:
        (?request_options: ModernTreasury::request_opts) -> void
        | (
          ?ModernTreasury::Models::ledger_account_balance_monitor_delete_params
          | ModernTreasury::BaseModel data
        ) -> void

      def to_hash: -> ModernTreasury::Models::ledger_account_balance_monitor_delete_params
    end
  end
end
