module ModernTreasury
  module Models
    type ledger_account_category =
      {
        id: String,
        balances: ModernTreasury::LedgerAccountCategory::Balances,
        created_at: Time,
        description: String?,
        discarded_at: Time?,
        external_id: String?,
        ledger_id: String,
        live_mode: bool,
        metadata: ::Hash[Symbol, String],
        name: String,
        normal_balance: ModernTreasury::Models::transaction_direction,
        object: String,
        updated_at: Time
      }

    class LedgerAccountCategory < ModernTreasury::Internal::Type::BaseModel
      attr_accessor id: String

      attr_accessor balances: ModernTreasury::LedgerAccountCategory::Balances

      attr_accessor created_at: Time

      attr_accessor description: String?

      attr_accessor discarded_at: Time?

      attr_accessor external_id: String?

      attr_accessor ledger_id: String

      attr_accessor live_mode: bool

      attr_accessor metadata: ::Hash[Symbol, String]

      attr_accessor name: String

      attr_accessor normal_balance: ModernTreasury::Models::transaction_direction

      attr_accessor object: String

      attr_accessor updated_at: Time

      def initialize: (
        id: String,
        balances: ModernTreasury::LedgerAccountCategory::Balances,
        created_at: Time,
        description: String?,
        discarded_at: Time?,
        external_id: String?,
        ledger_id: String,
        live_mode: bool,
        metadata: ::Hash[Symbol, String],
        name: String,
        normal_balance: ModernTreasury::Models::transaction_direction,
        object: String,
        updated_at: Time
      ) -> void

      def to_hash: -> {
        id: String,
        balances: ModernTreasury::LedgerAccountCategory::Balances,
        created_at: Time,
        description: String?,
        discarded_at: Time?,
        external_id: String?,
        ledger_id: String,
        live_mode: bool,
        metadata: ::Hash[Symbol, String],
        name: String,
        normal_balance: ModernTreasury::Models::transaction_direction,
        object: String,
        updated_at: Time
      }

      type balances =
        {
          available_balance: ModernTreasury::LedgerAccountCategory::Balances::AvailableBalance,
          pending_balance: ModernTreasury::LedgerAccountCategory::Balances::PendingBalance,
          posted_balance: ModernTreasury::LedgerAccountCategory::Balances::PostedBalance
        }

      class Balances < ModernTreasury::Internal::Type::BaseModel
        attr_accessor available_balance: ModernTreasury::LedgerAccountCategory::Balances::AvailableBalance

        attr_accessor pending_balance: ModernTreasury::LedgerAccountCategory::Balances::PendingBalance

        attr_accessor posted_balance: ModernTreasury::LedgerAccountCategory::Balances::PostedBalance

        def initialize: (
          available_balance: ModernTreasury::LedgerAccountCategory::Balances::AvailableBalance,
          pending_balance: ModernTreasury::LedgerAccountCategory::Balances::PendingBalance,
          posted_balance: ModernTreasury::LedgerAccountCategory::Balances::PostedBalance
        ) -> void

        def to_hash: -> {
          available_balance: ModernTreasury::LedgerAccountCategory::Balances::AvailableBalance,
          pending_balance: ModernTreasury::LedgerAccountCategory::Balances::PendingBalance,
          posted_balance: ModernTreasury::LedgerAccountCategory::Balances::PostedBalance
        }

        type available_balance =
          {
            amount: Integer,
            credits: Integer,
            currency: String,
            currency_exponent: Integer,
            debits: Integer
          }

        class AvailableBalance < ModernTreasury::Internal::Type::BaseModel
          attr_accessor amount: Integer

          attr_accessor credits: Integer

          attr_accessor currency: String

          attr_accessor currency_exponent: Integer

          attr_accessor debits: Integer

          def initialize: (
            amount: Integer,
            credits: Integer,
            currency: String,
            currency_exponent: Integer,
            debits: Integer
          ) -> void

          def to_hash: -> {
            amount: Integer,
            credits: Integer,
            currency: String,
            currency_exponent: Integer,
            debits: Integer
          }
        end

        type pending_balance =
          {
            amount: Integer,
            credits: Integer,
            currency: String,
            currency_exponent: Integer,
            debits: Integer
          }

        class PendingBalance < ModernTreasury::Internal::Type::BaseModel
          attr_accessor amount: Integer

          attr_accessor credits: Integer

          attr_accessor currency: String

          attr_accessor currency_exponent: Integer

          attr_accessor debits: Integer

          def initialize: (
            amount: Integer,
            credits: Integer,
            currency: String,
            currency_exponent: Integer,
            debits: Integer
          ) -> void

          def to_hash: -> {
            amount: Integer,
            credits: Integer,
            currency: String,
            currency_exponent: Integer,
            debits: Integer
          }
        end

        type posted_balance =
          {
            amount: Integer,
            credits: Integer,
            currency: String,
            currency_exponent: Integer,
            debits: Integer
          }

        class PostedBalance < ModernTreasury::Internal::Type::BaseModel
          attr_accessor amount: Integer

          attr_accessor credits: Integer

          attr_accessor currency: String

          attr_accessor currency_exponent: Integer

          attr_accessor debits: Integer

          def initialize: (
            amount: Integer,
            credits: Integer,
            currency: String,
            currency_exponent: Integer,
            debits: Integer
          ) -> void

          def to_hash: -> {
            amount: Integer,
            credits: Integer,
            currency: String,
            currency_exponent: Integer,
            debits: Integer
          }
        end
      end
    end
  end
end
