module ModernTreasury
  module Models
    type ledger_transaction_create_partial_post_params =
      {
        posted_ledger_entries: ::Array[ModernTreasury::LedgerTransactionCreatePartialPostParams::PostedLedgerEntry],
        description: String,
        effective_at: Time,
        metadata: ::Hash[Symbol, String]
      }
      & ModernTreasury::Internal::Type::request_parameters

    class LedgerTransactionCreatePartialPostParams < ModernTreasury::Internal::Type::BaseModel
      extend ModernTreasury::Internal::Type::RequestParameters::Converter
      include ModernTreasury::Internal::Type::RequestParameters

      attr_accessor posted_ledger_entries: ::Array[ModernTreasury::LedgerTransactionCreatePartialPostParams::PostedLedgerEntry]

      attr_reader description: String?

      def description=: (String) -> String

      attr_reader effective_at: Time?

      def effective_at=: (Time) -> Time

      attr_reader metadata: ::Hash[Symbol, String]?

      def metadata=: (::Hash[Symbol, String]) -> ::Hash[Symbol, String]

      def initialize: (
        posted_ledger_entries: ::Array[ModernTreasury::LedgerTransactionCreatePartialPostParams::PostedLedgerEntry],
        ?description: String,
        ?effective_at: Time,
        ?metadata: ::Hash[Symbol, String],
        ?request_options: ModernTreasury::request_opts
      ) -> void

      type posted_ledger_entry =
        {
          amount: Integer,
          direction: ModernTreasury::LedgerTransactionCreatePartialPostParams::PostedLedgerEntry::direction,
          ledger_account_id: String,
          metadata: ::Hash[Symbol, String]
        }

      class PostedLedgerEntry < ModernTreasury::Internal::Type::BaseModel
        attr_accessor amount: Integer

        attr_accessor direction: ModernTreasury::LedgerTransactionCreatePartialPostParams::PostedLedgerEntry::direction

        attr_accessor ledger_account_id: String

        attr_reader metadata: ::Hash[Symbol, String]?

        def metadata=: (::Hash[Symbol, String]) -> ::Hash[Symbol, String]

        def initialize: (
          amount: Integer,
          direction: ModernTreasury::LedgerTransactionCreatePartialPostParams::PostedLedgerEntry::direction,
          ledger_account_id: String,
          ?metadata: ::Hash[Symbol, String]
        ) -> void

        type direction = :credit | :debit

        module Direction
          extend ModernTreasury::Internal::Type::Enum

          CREDIT: :credit
          DEBIT: :debit

          def self?.values: -> ::Array[ModernTreasury::LedgerTransactionCreatePartialPostParams::PostedLedgerEntry::direction]
        end
      end
    end
  end
end
