module ModernTreasury
  module Models
    type legal_entity_bank_setting =
      {
        id: String,
        backup_withholding_percentage: Integer?,
        created_at: Time,
        discarded_at: Time?,
        enable_backup_withholding: bool?,
        live_mode: bool,
        object: String,
        privacy_opt_out: bool?,
        regulation_o: bool?,
        updated_at: Time
      }

    class LegalEntityBankSetting < ModernTreasury::Internal::Type::BaseModel
      attr_accessor id: String

      attr_accessor backup_withholding_percentage: Integer?

      attr_accessor created_at: Time

      attr_accessor discarded_at: Time?

      attr_accessor enable_backup_withholding: bool?

      attr_accessor live_mode: bool

      attr_accessor object: String

      attr_accessor privacy_opt_out: bool?

      attr_accessor regulation_o: bool?

      attr_accessor updated_at: Time

      def initialize: (
        id: String,
        backup_withholding_percentage: Integer?,
        created_at: Time,
        discarded_at: Time?,
        enable_backup_withholding: bool?,
        live_mode: bool,
        object: String,
        privacy_opt_out: bool?,
        regulation_o: bool?,
        updated_at: Time
      ) -> void

      def to_hash: -> {
        id: String,
        backup_withholding_percentage: Integer?,
        created_at: Time,
        discarded_at: Time?,
        enable_backup_withholding: bool?,
        live_mode: bool,
        object: String,
        privacy_opt_out: bool?,
        regulation_o: bool?,
        updated_at: Time
      }
    end
  end
end
