module ModernTreasury
  module Models
    type legal_entity_list_params =
      {
        after_cursor: String?,
        external_id: String,
        legal_entity_type: ModernTreasury::Models::LegalEntityListParams::legal_entity_type,
        metadata: ::Hash[Symbol, String],
        per_page: Integer,
        show_deleted: String,
        status: ModernTreasury::Models::LegalEntityListParams::status
      }
      & ModernTreasury::Internal::Type::request_parameters

    class LegalEntityListParams < ModernTreasury::Internal::Type::BaseModel
      extend ModernTreasury::Internal::Type::RequestParameters::Converter
      include ModernTreasury::Internal::Type::RequestParameters

      attr_accessor after_cursor: String?

      attr_reader external_id: String?

      def external_id=: (String) -> String

      attr_reader legal_entity_type: ModernTreasury::Models::LegalEntityListParams::legal_entity_type?

      def legal_entity_type=: (
        ModernTreasury::Models::LegalEntityListParams::legal_entity_type
      ) -> ModernTreasury::Models::LegalEntityListParams::legal_entity_type

      attr_reader metadata: ::Hash[Symbol, String]?

      def metadata=: (::Hash[Symbol, String]) -> ::Hash[Symbol, String]

      attr_reader per_page: Integer?

      def per_page=: (Integer) -> Integer

      attr_reader show_deleted: String?

      def show_deleted=: (String) -> String

      attr_reader status: ModernTreasury::Models::LegalEntityListParams::status?

      def status=: (
        ModernTreasury::Models::LegalEntityListParams::status
      ) -> ModernTreasury::Models::LegalEntityListParams::status

      def initialize: (
        ?after_cursor: String?,
        ?external_id: String,
        ?legal_entity_type: ModernTreasury::Models::LegalEntityListParams::legal_entity_type,
        ?metadata: ::Hash[Symbol, String],
        ?per_page: Integer,
        ?show_deleted: String,
        ?status: ModernTreasury::Models::LegalEntityListParams::status,
        ?request_options: ModernTreasury::request_opts
      ) -> void

      def to_hash: -> {
        after_cursor: String?,
        external_id: String,
        legal_entity_type: ModernTreasury::Models::LegalEntityListParams::legal_entity_type,
        metadata: ::Hash[Symbol, String],
        per_page: Integer,
        show_deleted: String,
        status: ModernTreasury::Models::LegalEntityListParams::status,
        request_options: ModernTreasury::RequestOptions
      }

      type legal_entity_type = :business | :individual

      module LegalEntityType
        extend ModernTreasury::Internal::Type::Enum

        BUSINESS: :business
        INDIVIDUAL: :individual

        def self?.values: -> ::Array[ModernTreasury::Models::LegalEntityListParams::legal_entity_type]
      end

      type status = :pending | :active | :suspended | :closed

      module Status
        extend ModernTreasury::Internal::Type::Enum

        PENDING: :pending
        ACTIVE: :active
        SUSPENDED: :suspended
        CLOSED: :closed

        def self?.values: -> ::Array[ModernTreasury::Models::LegalEntityListParams::status]
      end
    end
  end
end
