module ModernTreasury
  module Models
    type legal_entity_association_create_params =
      {
        parent_legal_entity_id: String,
        relationship_types: ::Array[ModernTreasury::Models::LegalEntityAssociationCreateParams::relationship_type],
        child_legal_entity: ModernTreasury::ChildLegalEntityCreate,
        child_legal_entity_id: String,
        ownership_percentage: Integer?,
        title: String?
      }
      & ModernTreasury::Internal::Type::request_parameters

    class LegalEntityAssociationCreateParams < ModernTreasury::Internal::Type::BaseModel
      extend ModernTreasury::Internal::Type::RequestParameters::Converter
      include ModernTreasury::Internal::Type::RequestParameters

      attr_accessor parent_legal_entity_id: String

      attr_accessor relationship_types: ::Array[ModernTreasury::Models::LegalEntityAssociationCreateParams::relationship_type]

      attr_reader child_legal_entity: ModernTreasury::ChildLegalEntityCreate?

      def child_legal_entity=: (
        ModernTreasury::ChildLegalEntityCreate
      ) -> ModernTreasury::ChildLegalEntityCreate

      attr_reader child_legal_entity_id: String?

      def child_legal_entity_id=: (String) -> String

      attr_accessor ownership_percentage: Integer?

      attr_accessor title: String?

      def initialize: (
        parent_legal_entity_id: String,
        relationship_types: ::Array[ModernTreasury::Models::LegalEntityAssociationCreateParams::relationship_type],
        ?child_legal_entity: ModernTreasury::ChildLegalEntityCreate,
        ?child_legal_entity_id: String,
        ?ownership_percentage: Integer?,
        ?title: String?,
        ?request_options: ModernTreasury::request_opts
      ) -> void

      def to_hash: -> {
        parent_legal_entity_id: String,
        relationship_types: ::Array[ModernTreasury::Models::LegalEntityAssociationCreateParams::relationship_type],
        child_legal_entity: ModernTreasury::ChildLegalEntityCreate,
        child_legal_entity_id: String,
        ownership_percentage: Integer?,
        title: String?,
        request_options: ModernTreasury::RequestOptions
      }

      type relationship_type =
        :authorized_signer | :beneficial_owner | :control_person

      module RelationshipType
        extend ModernTreasury::Internal::Type::Enum

        AUTHORIZED_SIGNER: :authorized_signer
        BENEFICIAL_OWNER: :beneficial_owner
        CONTROL_PERSON: :control_person

        def self?.values: -> ::Array[ModernTreasury::Models::LegalEntityAssociationCreateParams::relationship_type]
      end
    end
  end
end
