module ModernTreasury
  module Models
    type legal_entity_wealth_employment_detail =
      {
        id: String,
        annual_income: Integer?,
        created_at: Time,
        discarded_at: Time?,
        employer_country: String?,
        employer_name: String?,
        employer_state: String?,
        employment_status: ModernTreasury::Models::LegalEntityWealthEmploymentDetail::employment_status?,
        income_country: String?,
        income_source: ModernTreasury::Models::LegalEntityWealthEmploymentDetail::income_source?,
        income_state: String?,
        industry: ModernTreasury::Models::LegalEntityWealthEmploymentDetail::industry?,
        live_mode: bool,
        object: String,
        occupation: ModernTreasury::Models::LegalEntityWealthEmploymentDetail::occupation?,
        source_of_funds: ModernTreasury::Models::LegalEntityWealthEmploymentDetail::source_of_funds?,
        updated_at: Time,
        wealth_source: ModernTreasury::Models::LegalEntityWealthEmploymentDetail::wealth_source?
      }

    class LegalEntityWealthEmploymentDetail < ModernTreasury::Internal::Type::BaseModel
      attr_accessor id: String

      attr_accessor annual_income: Integer?

      attr_accessor created_at: Time

      attr_accessor discarded_at: Time?

      attr_accessor employer_country: String?

      attr_accessor employer_name: String?

      attr_accessor employer_state: String?

      attr_accessor employment_status: ModernTreasury::Models::LegalEntityWealthEmploymentDetail::employment_status?

      attr_accessor income_country: String?

      attr_accessor income_source: ModernTreasury::Models::LegalEntityWealthEmploymentDetail::income_source?

      attr_accessor income_state: String?

      attr_accessor industry: ModernTreasury::Models::LegalEntityWealthEmploymentDetail::industry?

      attr_accessor live_mode: bool

      attr_accessor object: String

      attr_accessor occupation: ModernTreasury::Models::LegalEntityWealthEmploymentDetail::occupation?

      attr_accessor source_of_funds: ModernTreasury::Models::LegalEntityWealthEmploymentDetail::source_of_funds?

      attr_accessor updated_at: Time

      attr_accessor wealth_source: ModernTreasury::Models::LegalEntityWealthEmploymentDetail::wealth_source?

      def initialize: (
        id: String,
        annual_income: Integer?,
        created_at: Time,
        discarded_at: Time?,
        employer_country: String?,
        employer_name: String?,
        employer_state: String?,
        employment_status: ModernTreasury::Models::LegalEntityWealthEmploymentDetail::employment_status?,
        income_country: String?,
        income_source: ModernTreasury::Models::LegalEntityWealthEmploymentDetail::income_source?,
        income_state: String?,
        industry: ModernTreasury::Models::LegalEntityWealthEmploymentDetail::industry?,
        live_mode: bool,
        object: String,
        occupation: ModernTreasury::Models::LegalEntityWealthEmploymentDetail::occupation?,
        source_of_funds: ModernTreasury::Models::LegalEntityWealthEmploymentDetail::source_of_funds?,
        updated_at: Time,
        wealth_source: ModernTreasury::Models::LegalEntityWealthEmploymentDetail::wealth_source?
      ) -> void

      def to_hash: -> {
        id: String,
        annual_income: Integer?,
        created_at: Time,
        discarded_at: Time?,
        employer_country: String?,
        employer_name: String?,
        employer_state: String?,
        employment_status: ModernTreasury::Models::LegalEntityWealthEmploymentDetail::employment_status?,
        income_country: String?,
        income_source: ModernTreasury::Models::LegalEntityWealthEmploymentDetail::income_source?,
        income_state: String?,
        industry: ModernTreasury::Models::LegalEntityWealthEmploymentDetail::industry?,
        live_mode: bool,
        object: String,
        occupation: ModernTreasury::Models::LegalEntityWealthEmploymentDetail::occupation?,
        source_of_funds: ModernTreasury::Models::LegalEntityWealthEmploymentDetail::source_of_funds?,
        updated_at: Time,
        wealth_source: ModernTreasury::Models::LegalEntityWealthEmploymentDetail::wealth_source?
      }

      type employment_status =
        :employed | :retired | :self_employed | :student | :unemployed

      module EmploymentStatus
        extend ModernTreasury::Internal::Type::Enum

        EMPLOYED: :employed
        RETIRED: :retired
        SELF_EMPLOYED: :self_employed
        STUDENT: :student
        UNEMPLOYED: :unemployed

        def self?.values: -> ::Array[ModernTreasury::Models::LegalEntityWealthEmploymentDetail::employment_status]
      end

      type income_source =
        :family_support
        | :government_benefits
        | :inheritance
        | :investments
        | :rental_income
        | :retirement
        | :salary
        | :self_employed

      module IncomeSource
        extend ModernTreasury::Internal::Type::Enum

        FAMILY_SUPPORT: :family_support
        GOVERNMENT_BENEFITS: :government_benefits
        INHERITANCE: :inheritance
        INVESTMENTS: :investments
        RENTAL_INCOME: :rental_income
        RETIREMENT: :retirement
        SALARY: :salary
        SELF_EMPLOYED: :self_employed

        def self?.values: -> ::Array[ModernTreasury::Models::LegalEntityWealthEmploymentDetail::income_source]
      end

      type industry =
        :accounting
        | :agriculture
        | :automotive
        | :chemical_manufacturing
        | :construction
        | :educational_medical
        | :food_service
        | :finance
        | :gasoline
        | :health_stores
        | :laundry
        | :maintenance
        | :manufacturing
        | :merchant_wholesale
        | :mining
        | :performing_arts
        | :professional_non_legal
        | :public_administration
        | :publishing
        | :real_estate
        | :recreation_gambling
        | :religious_charity
        | :rental_services
        | :retail_clothing
        | :retail_electronics
        | :retail_food
        | :retail_furnishing
        | :retail_home
        | :retail_non_store
        | :retail_sporting
        | :transportation
        | :travel
        | :utilities

      module Industry
        extend ModernTreasury::Internal::Type::Enum

        ACCOUNTING: :accounting
        AGRICULTURE: :agriculture
        AUTOMOTIVE: :automotive
        CHEMICAL_MANUFACTURING: :chemical_manufacturing
        CONSTRUCTION: :construction
        EDUCATIONAL_MEDICAL: :educational_medical
        FOOD_SERVICE: :food_service
        FINANCE: :finance
        GASOLINE: :gasoline
        HEALTH_STORES: :health_stores
        LAUNDRY: :laundry
        MAINTENANCE: :maintenance
        MANUFACTURING: :manufacturing
        MERCHANT_WHOLESALE: :merchant_wholesale
        MINING: :mining
        PERFORMING_ARTS: :performing_arts
        PROFESSIONAL_NON_LEGAL: :professional_non_legal
        PUBLIC_ADMINISTRATION: :public_administration
        PUBLISHING: :publishing
        REAL_ESTATE: :real_estate
        RECREATION_GAMBLING: :recreation_gambling
        RELIGIOUS_CHARITY: :religious_charity
        RENTAL_SERVICES: :rental_services
        RETAIL_CLOTHING: :retail_clothing
        RETAIL_ELECTRONICS: :retail_electronics
        RETAIL_FOOD: :retail_food
        RETAIL_FURNISHING: :retail_furnishing
        RETAIL_HOME: :retail_home
        RETAIL_NON_STORE: :retail_non_store
        RETAIL_SPORTING: :retail_sporting
        TRANSPORTATION: :transportation
        TRAVEL: :travel
        UTILITIES: :utilities

        def self?.values: -> ::Array[ModernTreasury::Models::LegalEntityWealthEmploymentDetail::industry]
      end

      type occupation =
        :consulting
        | :executive
        | :finance_accounting
        | :food_services
        | :government
        | :healthcare
        | :legal_services
        | :manufacturing
        | :other
        | :sales
        | :science_engineering
        | :technology

      module Occupation
        extend ModernTreasury::Internal::Type::Enum

        CONSULTING: :consulting
        EXECUTIVE: :executive
        FINANCE_ACCOUNTING: :finance_accounting
        FOOD_SERVICES: :food_services
        GOVERNMENT: :government
        HEALTHCARE: :healthcare
        LEGAL_SERVICES: :legal_services
        MANUFACTURING: :manufacturing
        OTHER: :other
        SALES: :sales
        SCIENCE_ENGINEERING: :science_engineering
        TECHNOLOGY: :technology

        def self?.values: -> ::Array[ModernTreasury::Models::LegalEntityWealthEmploymentDetail::occupation]
      end

      type source_of_funds =
        :alimony
        | :annuity
        | :business_owner
        | :business_revenue
        | :debt_financing
        | :general_employee
        | :government_benefits
        | :homemaker
        | :inheritance_gift
        | :intercompany_loan
        | :investment
        | :investor_funding
        | :legal_settlement
        | :lottery
        | :real_estate
        | :retained_earnings_or_savings
        | :retired
        | :retirement
        | :salary
        | :sale_of_business_assets
        | :sale_of_real_estate
        | :self_employed
        | :senior_executive
        | :trust_income

      module SourceOfFunds
        extend ModernTreasury::Internal::Type::Enum

        ALIMONY: :alimony
        ANNUITY: :annuity
        BUSINESS_OWNER: :business_owner
        BUSINESS_REVENUE: :business_revenue
        DEBT_FINANCING: :debt_financing
        GENERAL_EMPLOYEE: :general_employee
        GOVERNMENT_BENEFITS: :government_benefits
        HOMEMAKER: :homemaker
        INHERITANCE_GIFT: :inheritance_gift
        INTERCOMPANY_LOAN: :intercompany_loan
        INVESTMENT: :investment
        INVESTOR_FUNDING: :investor_funding
        LEGAL_SETTLEMENT: :legal_settlement
        LOTTERY: :lottery
        REAL_ESTATE: :real_estate
        RETAINED_EARNINGS_OR_SAVINGS: :retained_earnings_or_savings
        RETIRED: :retired
        RETIREMENT: :retirement
        SALARY: :salary
        SALE_OF_BUSINESS_ASSETS: :sale_of_business_assets
        SALE_OF_REAL_ESTATE: :sale_of_real_estate
        SELF_EMPLOYED: :self_employed
        SENIOR_EXECUTIVE: :senior_executive
        TRUST_INCOME: :trust_income

        def self?.values: -> ::Array[ModernTreasury::Models::LegalEntityWealthEmploymentDetail::source_of_funds]
      end

      type wealth_source =
        :business_sale
        | :family_support
        | :government_benefits
        | :inheritance
        | :investments
        | :other
        | :rental_income
        | :retirement
        | :salary
        | :self_employed

      module WealthSource
        extend ModernTreasury::Internal::Type::Enum

        BUSINESS_SALE: :business_sale
        FAMILY_SUPPORT: :family_support
        GOVERNMENT_BENEFITS: :government_benefits
        INHERITANCE: :inheritance
        INVESTMENTS: :investments
        OTHER: :other
        RENTAL_INCOME: :rental_income
        RETIREMENT: :retirement
        SALARY: :salary
        SELF_EMPLOYED: :self_employed

        def self?.values: -> ::Array[ModernTreasury::Models::LegalEntityWealthEmploymentDetail::wealth_source]
      end
    end
  end
end
