module ModernTreasury
  module Models
    type legal_entity_update_status_params =
      {
        id: String,
        status: ModernTreasury::Models::LegalEntityUpdateStatusParams::status
      }
      & ModernTreasury::Internal::Type::request_parameters

    class LegalEntityUpdateStatusParams < ModernTreasury::Internal::Type::BaseModel
      extend ModernTreasury::Internal::Type::RequestParameters::Converter
      include ModernTreasury::Internal::Type::RequestParameters

      attr_accessor id: String

      attr_accessor status: ModernTreasury::Models::LegalEntityUpdateStatusParams::status

      def initialize: (
        id: String,
        status: ModernTreasury::Models::LegalEntityUpdateStatusParams::status,
        ?request_options: ModernTreasury::request_opts
      ) -> void

      def to_hash: -> {
        id: String,
        status: ModernTreasury::Models::LegalEntityUpdateStatusParams::status,
        request_options: ModernTreasury::RequestOptions
      }

      type status = :active | :suspended | :denied

      module Status
        extend ModernTreasury::Internal::Type::Enum

        ACTIVE: :active
        SUSPENDED: :suspended
        DENIED: :denied

        def self?.values: -> ::Array[ModernTreasury::Models::LegalEntityUpdateStatusParams::status]
      end
    end
  end
end
