module ModernTreasury
  module Models
    type line_item_retrieve_params =
      {
        itemizable_type: ModernTreasury::Models::LineItemRetrieveParams::itemizable_type,
        itemizable_id: String
      }
      & ModernTreasury::request_parameters

    class LineItemRetrieveParams < ModernTreasury::BaseModel
      extend ModernTreasury::RequestParameters::Converter
      include ModernTreasury::RequestParameters

      attr_accessor itemizable_type: ModernTreasury::Models::LineItemRetrieveParams::itemizable_type

      attr_accessor itemizable_id: String

      def initialize:
        (
          itemizable_type: ModernTreasury::Models::LineItemRetrieveParams::itemizable_type,
          itemizable_id: String,
          ?request_options: ModernTreasury::request_opts
        ) -> void
        | (
          ?ModernTreasury::Models::line_item_retrieve_params
          | ModernTreasury::BaseModel data
        ) -> void

      def to_hash: -> ModernTreasury::Models::line_item_retrieve_params

      type itemizable_type = :expected_payments | :payment_orders

      class ItemizableType < ModernTreasury::Enum
        EXPECTED_PAYMENTS: :expected_payments
        PAYMENT_ORDERS: :payment_orders

        def self.values: -> ::Array[ModernTreasury::Models::LineItemRetrieveParams::itemizable_type]
      end
    end
  end
end
