module ModernTreasury
  module Models
    type paper_item =
      {
        id: String,
        account_number: String?,
        account_number_safe: String?,
        amount: Integer,
        check_number: String?,
        created_at: Time,
        currency: ModernTreasury::Models::currency,
        deposit_date: Date,
        live_mode: bool,
        lockbox_number: String,
        memo_field: String?,
        metadata: top,
        object: String,
        remitter_name: String?,
        routing_number: String?,
        status: ModernTreasury::Models::PaperItem::status,
        transaction_id: String?,
        transaction_line_item_id: String?,
        updated_at: Time
      }

    class PaperItem < ModernTreasury::Internal::Type::BaseModel
      attr_accessor id: String

      attr_accessor account_number: String?

      attr_accessor account_number_safe: String?

      attr_accessor amount: Integer

      attr_accessor check_number: String?

      attr_accessor created_at: Time

      attr_accessor currency: ModernTreasury::Models::currency

      attr_accessor deposit_date: Date

      attr_accessor live_mode: bool

      attr_accessor lockbox_number: String

      attr_accessor memo_field: String?

      attr_accessor metadata: top

      attr_accessor object: String

      attr_accessor remitter_name: String?

      attr_accessor routing_number: String?

      attr_accessor status: ModernTreasury::Models::PaperItem::status

      attr_accessor transaction_id: String?

      attr_accessor transaction_line_item_id: String?

      attr_accessor updated_at: Time

      def initialize: (
        id: String,
        account_number: String?,
        account_number_safe: String?,
        amount: Integer,
        check_number: String?,
        created_at: Time,
        currency: ModernTreasury::Models::currency,
        deposit_date: Date,
        live_mode: bool,
        lockbox_number: String,
        memo_field: String?,
        metadata: top,
        object: String,
        remitter_name: String?,
        routing_number: String?,
        status: ModernTreasury::Models::PaperItem::status,
        transaction_id: String?,
        transaction_line_item_id: String?,
        updated_at: Time
      ) -> void

      def to_hash: -> {
        id: String,
        account_number: String?,
        account_number_safe: String?,
        amount: Integer,
        check_number: String?,
        created_at: Time,
        currency: ModernTreasury::Models::currency,
        deposit_date: Date,
        live_mode: bool,
        lockbox_number: String,
        memo_field: String?,
        metadata: top,
        object: String,
        remitter_name: String?,
        routing_number: String?,
        status: ModernTreasury::Models::PaperItem::status,
        transaction_id: String?,
        transaction_line_item_id: String?,
        updated_at: Time
      }

      type status = :completed | :pending | :returned

      module Status
        extend ModernTreasury::Internal::Type::Enum

        COMPLETED: :completed
        PENDING: :pending
        RETURNED: :returned

        def self?.values: -> ::Array[ModernTreasury::Models::PaperItem::status]
      end
    end
  end
end
