module ModernTreasury
  module Models
    type payment_reference_retrieve_params =
      {  } & ModernTreasury::request_parameters

    class PaymentReferenceRetrieveParams < ModernTreasury::BaseModel
      extend ModernTreasury::RequestParameters::Converter
      include ModernTreasury::RequestParameters

      def initialize:
        (request_options: ModernTreasury::request_opts) -> void
        | (
          ?ModernTreasury::Models::payment_reference_retrieve_params
          | ModernTreasury::BaseModel data
        ) -> void

      def to_h: -> ModernTreasury::Models::payment_reference_retrieve_params
    end
  end
end
