module ModernTreasury
  module Models
    type payment_action_list_response =
      {
        id: String,
        actionable_id: String?,
        actionable_type: String?,
        created_at: Time,
        details: top,
        internal_account_id: String,
        live_mode: bool,
        object: String,
        status: String,
        type: String,
        updated_at: Time
      }

    class PaymentActionListResponse < ModernTreasury::Internal::Type::BaseModel
      attr_accessor id: String

      attr_accessor actionable_id: String?

      attr_accessor actionable_type: String?

      attr_accessor created_at: Time

      attr_accessor details: top

      attr_accessor internal_account_id: String

      attr_accessor live_mode: bool

      attr_accessor object: String

      attr_accessor status: String

      attr_accessor type: String

      attr_accessor updated_at: Time

      def initialize: (
        id: String,
        actionable_id: String?,
        actionable_type: String?,
        created_at: Time,
        details: top,
        internal_account_id: String,
        live_mode: bool,
        object: String,
        status: String,
        type: String,
        updated_at: Time
      ) -> void

      def to_hash: -> {
        id: String,
        actionable_id: String?,
        actionable_type: String?,
        created_at: Time,
        details: top,
        internal_account_id: String,
        live_mode: bool,
        object: String,
        status: String,
        type: String,
        updated_at: Time
      }
    end
  end
end
