module ModernTreasury
  module Models
    type payment_flow_update_params =
      { status: ModernTreasury::Models::PaymentFlowUpdateParams::status }
      & ModernTreasury::Internal::Type::request_parameters

    class PaymentFlowUpdateParams < ModernTreasury::Internal::Type::BaseModel
      extend ModernTreasury::Internal::Type::RequestParameters::Converter
      include ModernTreasury::Internal::Type::RequestParameters

      attr_accessor status: ModernTreasury::Models::PaymentFlowUpdateParams::status

      def initialize: (
        status: ModernTreasury::Models::PaymentFlowUpdateParams::status,
        ?request_options: ModernTreasury::request_opts
      ) -> void

      type status = :cancelled

      module Status
        extend ModernTreasury::Internal::Type::Enum

        CANCELLED: :cancelled

        def self?.values: -> ::Array[ModernTreasury::Models::PaymentFlowUpdateParams::status]
      end
    end
  end
end
