module ModernTreasury
  module Models
    type payment_reference_list_params =
      {
        after_cursor: String?,
        per_page: Integer,
        reference_number: String,
        referenceable_id: String,
        referenceable_type: ModernTreasury::Models::PaymentReferenceListParams::referenceable_type
      }
      & ModernTreasury::Internal::Type::request_parameters

    class PaymentReferenceListParams < ModernTreasury::Internal::Type::BaseModel
      extend ModernTreasury::Internal::Type::RequestParameters::Converter
      include ModernTreasury::Internal::Type::RequestParameters

      attr_accessor after_cursor: String?

      attr_reader per_page: Integer?

      def per_page=: (Integer) -> Integer

      attr_reader reference_number: String?

      def reference_number=: (String) -> String

      attr_reader referenceable_id: String?

      def referenceable_id=: (String) -> String

      attr_reader referenceable_type: ModernTreasury::Models::PaymentReferenceListParams::referenceable_type?

      def referenceable_type=: (
        ModernTreasury::Models::PaymentReferenceListParams::referenceable_type
      ) -> ModernTreasury::Models::PaymentReferenceListParams::referenceable_type

      def initialize: (
        ?after_cursor: String?,
        ?per_page: Integer,
        ?reference_number: String,
        ?referenceable_id: String,
        ?referenceable_type: ModernTreasury::Models::PaymentReferenceListParams::referenceable_type,
        ?request_options: ModernTreasury::request_opts
      ) -> void

      type referenceable_type = :payment_order | :return | :reversal

      module ReferenceableType
        extend ModernTreasury::Internal::Type::Enum

        PAYMENT_ORDER: :payment_order
        RETURN: :return
        REVERSAL: :reversal

        def self?.values: -> ::Array[ModernTreasury::Models::PaymentReferenceListParams::referenceable_type]
      end
    end
  end
end
