module ModernTreasury
  module Models
    type payment_order_update_params =
      {
        accounting: ModernTreasury::PaymentOrderUpdateParams::Accounting,
        accounting_category_id: String?,
        accounting_ledger_class_id: String?,
        amount: Integer,
        charge_bearer: ModernTreasury::Models::PaymentOrderUpdateParams::charge_bearer?,
        counterparty_id: String?,
        currency: ModernTreasury::Models::currency,
        description: String?,
        direction: ModernTreasury::Models::PaymentOrderUpdateParams::direction,
        effective_date: Date,
        expires_at: Time?,
        fallback_type: ModernTreasury::Models::PaymentOrderUpdateParams::fallback_type,
        foreign_exchange_contract: String?,
        foreign_exchange_indicator: ModernTreasury::Models::PaymentOrderUpdateParams::foreign_exchange_indicator?,
        line_items: ::Array[ModernTreasury::PaymentOrderUpdateParams::LineItem],
        metadata: ::Hash[Symbol, String],
        nsf_protected: bool,
        originating_account_id: String,
        originating_party_name: String?,
        priority: ModernTreasury::Models::PaymentOrderUpdateParams::priority,
        process_after: Time?,
        purpose: String?,
        receiving_account: ModernTreasury::PaymentOrderUpdateParams::ReceivingAccount,
        receiving_account_id: String,
        reconciliation_status: ModernTreasury::Models::PaymentOrderUpdateParams::reconciliation_status,
        remittance_information: String?,
        send_remittance_advice: bool?,
        statement_descriptor: String?,
        status: ModernTreasury::Models::PaymentOrderUpdateParams::status,
        subtype: ModernTreasury::Models::payment_order_subtype?,
        type: ModernTreasury::Models::payment_order_type,
        ultimate_originating_party_identifier: String?,
        ultimate_originating_party_name: String?,
        ultimate_receiving_party_identifier: String?,
        ultimate_receiving_party_name: String?
      }
      & ModernTreasury::Internal::Type::request_parameters

    class PaymentOrderUpdateParams < ModernTreasury::Internal::Type::BaseModel
      extend ModernTreasury::Internal::Type::RequestParameters::Converter
      include ModernTreasury::Internal::Type::RequestParameters

      attr_reader accounting: ModernTreasury::PaymentOrderUpdateParams::Accounting?

      def accounting=: (
        ModernTreasury::PaymentOrderUpdateParams::Accounting
      ) -> ModernTreasury::PaymentOrderUpdateParams::Accounting

      attr_accessor accounting_category_id: String?

      attr_accessor accounting_ledger_class_id: String?

      attr_reader amount: Integer?

      def amount=: (Integer) -> Integer

      attr_accessor charge_bearer: ModernTreasury::Models::PaymentOrderUpdateParams::charge_bearer?

      attr_accessor counterparty_id: String?

      attr_reader currency: ModernTreasury::Models::currency?

      def currency=: (
        ModernTreasury::Models::currency
      ) -> ModernTreasury::Models::currency

      attr_accessor description: String?

      attr_reader direction: ModernTreasury::Models::PaymentOrderUpdateParams::direction?

      def direction=: (
        ModernTreasury::Models::PaymentOrderUpdateParams::direction
      ) -> ModernTreasury::Models::PaymentOrderUpdateParams::direction

      attr_reader effective_date: Date?

      def effective_date=: (Date) -> Date

      attr_accessor expires_at: Time?

      attr_reader fallback_type: ModernTreasury::Models::PaymentOrderUpdateParams::fallback_type?

      def fallback_type=: (
        ModernTreasury::Models::PaymentOrderUpdateParams::fallback_type
      ) -> ModernTreasury::Models::PaymentOrderUpdateParams::fallback_type

      attr_accessor foreign_exchange_contract: String?

      attr_accessor foreign_exchange_indicator: ModernTreasury::Models::PaymentOrderUpdateParams::foreign_exchange_indicator?

      attr_reader line_items: ::Array[ModernTreasury::PaymentOrderUpdateParams::LineItem]?

      def line_items=: (
        ::Array[ModernTreasury::PaymentOrderUpdateParams::LineItem]
      ) -> ::Array[ModernTreasury::PaymentOrderUpdateParams::LineItem]

      attr_reader metadata: ::Hash[Symbol, String]?

      def metadata=: (::Hash[Symbol, String]) -> ::Hash[Symbol, String]

      attr_reader nsf_protected: bool?

      def nsf_protected=: (bool) -> bool

      attr_reader originating_account_id: String?

      def originating_account_id=: (String) -> String

      attr_accessor originating_party_name: String?

      attr_reader priority: ModernTreasury::Models::PaymentOrderUpdateParams::priority?

      def priority=: (
        ModernTreasury::Models::PaymentOrderUpdateParams::priority
      ) -> ModernTreasury::Models::PaymentOrderUpdateParams::priority

      attr_accessor process_after: Time?

      attr_accessor purpose: String?

      attr_reader receiving_account: ModernTreasury::PaymentOrderUpdateParams::ReceivingAccount?

      def receiving_account=: (
        ModernTreasury::PaymentOrderUpdateParams::ReceivingAccount
      ) -> ModernTreasury::PaymentOrderUpdateParams::ReceivingAccount

      attr_reader receiving_account_id: String?

      def receiving_account_id=: (String) -> String

      attr_reader reconciliation_status: ModernTreasury::Models::PaymentOrderUpdateParams::reconciliation_status?

      def reconciliation_status=: (
        ModernTreasury::Models::PaymentOrderUpdateParams::reconciliation_status
      ) -> ModernTreasury::Models::PaymentOrderUpdateParams::reconciliation_status

      attr_accessor remittance_information: String?

      attr_accessor send_remittance_advice: bool?

      attr_accessor statement_descriptor: String?

      attr_reader status: ModernTreasury::Models::PaymentOrderUpdateParams::status?

      def status=: (
        ModernTreasury::Models::PaymentOrderUpdateParams::status
      ) -> ModernTreasury::Models::PaymentOrderUpdateParams::status

      attr_accessor subtype: ModernTreasury::Models::payment_order_subtype?

      attr_reader type: ModernTreasury::Models::payment_order_type?

      def type=: (
        ModernTreasury::Models::payment_order_type
      ) -> ModernTreasury::Models::payment_order_type

      attr_accessor ultimate_originating_party_identifier: String?

      attr_accessor ultimate_originating_party_name: String?

      attr_accessor ultimate_receiving_party_identifier: String?

      attr_accessor ultimate_receiving_party_name: String?

      def initialize: (
        ?accounting: ModernTreasury::PaymentOrderUpdateParams::Accounting,
        ?accounting_category_id: String?,
        ?accounting_ledger_class_id: String?,
        ?amount: Integer,
        ?charge_bearer: ModernTreasury::Models::PaymentOrderUpdateParams::charge_bearer?,
        ?counterparty_id: String?,
        ?currency: ModernTreasury::Models::currency,
        ?description: String?,
        ?direction: ModernTreasury::Models::PaymentOrderUpdateParams::direction,
        ?effective_date: Date,
        ?expires_at: Time?,
        ?fallback_type: ModernTreasury::Models::PaymentOrderUpdateParams::fallback_type,
        ?foreign_exchange_contract: String?,
        ?foreign_exchange_indicator: ModernTreasury::Models::PaymentOrderUpdateParams::foreign_exchange_indicator?,
        ?line_items: ::Array[ModernTreasury::PaymentOrderUpdateParams::LineItem],
        ?metadata: ::Hash[Symbol, String],
        ?nsf_protected: bool,
        ?originating_account_id: String,
        ?originating_party_name: String?,
        ?priority: ModernTreasury::Models::PaymentOrderUpdateParams::priority,
        ?process_after: Time?,
        ?purpose: String?,
        ?receiving_account: ModernTreasury::PaymentOrderUpdateParams::ReceivingAccount,
        ?receiving_account_id: String,
        ?reconciliation_status: ModernTreasury::Models::PaymentOrderUpdateParams::reconciliation_status,
        ?remittance_information: String?,
        ?send_remittance_advice: bool?,
        ?statement_descriptor: String?,
        ?status: ModernTreasury::Models::PaymentOrderUpdateParams::status,
        ?subtype: ModernTreasury::Models::payment_order_subtype?,
        ?type: ModernTreasury::Models::payment_order_type,
        ?ultimate_originating_party_identifier: String?,
        ?ultimate_originating_party_name: String?,
        ?ultimate_receiving_party_identifier: String?,
        ?ultimate_receiving_party_name: String?,
        ?request_options: ModernTreasury::request_opts
      ) -> void

      def to_hash: -> {
        accounting: ModernTreasury::PaymentOrderUpdateParams::Accounting,
        accounting_category_id: String?,
        accounting_ledger_class_id: String?,
        amount: Integer,
        charge_bearer: ModernTreasury::Models::PaymentOrderUpdateParams::charge_bearer?,
        counterparty_id: String?,
        currency: ModernTreasury::Models::currency,
        description: String?,
        direction: ModernTreasury::Models::PaymentOrderUpdateParams::direction,
        effective_date: Date,
        expires_at: Time?,
        fallback_type: ModernTreasury::Models::PaymentOrderUpdateParams::fallback_type,
        foreign_exchange_contract: String?,
        foreign_exchange_indicator: ModernTreasury::Models::PaymentOrderUpdateParams::foreign_exchange_indicator?,
        line_items: ::Array[ModernTreasury::PaymentOrderUpdateParams::LineItem],
        metadata: ::Hash[Symbol, String],
        nsf_protected: bool,
        originating_account_id: String,
        originating_party_name: String?,
        priority: ModernTreasury::Models::PaymentOrderUpdateParams::priority,
        process_after: Time?,
        purpose: String?,
        receiving_account: ModernTreasury::PaymentOrderUpdateParams::ReceivingAccount,
        receiving_account_id: String,
        reconciliation_status: ModernTreasury::Models::PaymentOrderUpdateParams::reconciliation_status,
        remittance_information: String?,
        send_remittance_advice: bool?,
        statement_descriptor: String?,
        status: ModernTreasury::Models::PaymentOrderUpdateParams::status,
        subtype: ModernTreasury::Models::payment_order_subtype?,
        type: ModernTreasury::Models::payment_order_type,
        ultimate_originating_party_identifier: String?,
        ultimate_originating_party_name: String?,
        ultimate_receiving_party_identifier: String?,
        ultimate_receiving_party_name: String?,
        request_options: ModernTreasury::RequestOptions
      }

      type accounting = { account_id: String?, class_id: String? }

      class Accounting < ModernTreasury::Internal::Type::BaseModel
        attr_accessor account_id: String?

        attr_accessor class_id: String?

        def initialize: (?account_id: String?, ?class_id: String?) -> void

        def to_hash: -> { account_id: String?, class_id: String? }
      end

      type charge_bearer = :shared | :sender | :receiver

      module ChargeBearer
        extend ModernTreasury::Internal::Type::Enum

        SHARED: :shared
        SENDER: :sender
        RECEIVER: :receiver

        def self?.values: -> ::Array[ModernTreasury::Models::PaymentOrderUpdateParams::charge_bearer]
      end

      type direction = :credit | :debit

      module Direction
        extend ModernTreasury::Internal::Type::Enum

        CREDIT: :credit
        DEBIT: :debit

        def self?.values: -> ::Array[ModernTreasury::Models::PaymentOrderUpdateParams::direction]
      end

      type fallback_type = :ach

      module FallbackType
        extend ModernTreasury::Internal::Type::Enum

        ACH: :ach

        def self?.values: -> ::Array[ModernTreasury::Models::PaymentOrderUpdateParams::fallback_type]
      end

      type foreign_exchange_indicator = :fixed_to_variable | :variable_to_fixed

      module ForeignExchangeIndicator
        extend ModernTreasury::Internal::Type::Enum

        FIXED_TO_VARIABLE: :fixed_to_variable
        VARIABLE_TO_FIXED: :variable_to_fixed

        def self?.values: -> ::Array[ModernTreasury::Models::PaymentOrderUpdateParams::foreign_exchange_indicator]
      end

      type line_item =
        {
          amount: Integer,
          accounting_category_id: String?,
          description: String?,
          metadata: ::Hash[Symbol, String]
        }

      class LineItem < ModernTreasury::Internal::Type::BaseModel
        attr_accessor amount: Integer

        attr_accessor accounting_category_id: String?

        attr_accessor description: String?

        attr_reader metadata: ::Hash[Symbol, String]?

        def metadata=: (::Hash[Symbol, String]) -> ::Hash[Symbol, String]

        def initialize: (
          amount: Integer,
          ?accounting_category_id: String?,
          ?description: String?,
          ?metadata: ::Hash[Symbol, String]
        ) -> void

        def to_hash: -> {
          amount: Integer,
          accounting_category_id: String?,
          description: String?,
          metadata: ::Hash[Symbol, String]
        }
      end

      type priority = :high | :normal

      module Priority
        extend ModernTreasury::Internal::Type::Enum

        HIGH: :high
        NORMAL: :normal

        def self?.values: -> ::Array[ModernTreasury::Models::PaymentOrderUpdateParams::priority]
      end

      type receiving_account =
        {
          account_details: ::Array[ModernTreasury::PaymentOrderUpdateParams::ReceivingAccount::AccountDetail],
          account_type: ModernTreasury::Models::external_account_type,
          contact_details: ::Array[ModernTreasury::ContactDetailCreateRequest],
          external_id: String?,
          ledger_account: ModernTreasury::LedgerAccountCreateRequest,
          metadata: ::Hash[Symbol, String],
          name: String?,
          party_address: ModernTreasury::AddressRequest,
          party_identifier: String,
          party_name: String,
          party_type: ModernTreasury::Models::PaymentOrderUpdateParams::ReceivingAccount::party_type?,
          plaid_processor_token: String,
          routing_details: ::Array[ModernTreasury::PaymentOrderUpdateParams::ReceivingAccount::RoutingDetail]
        }

      class ReceivingAccount < ModernTreasury::Internal::Type::BaseModel
        attr_reader account_details: ::Array[ModernTreasury::PaymentOrderUpdateParams::ReceivingAccount::AccountDetail]?

        def account_details=: (
          ::Array[ModernTreasury::PaymentOrderUpdateParams::ReceivingAccount::AccountDetail]
        ) -> ::Array[ModernTreasury::PaymentOrderUpdateParams::ReceivingAccount::AccountDetail]

        attr_reader account_type: ModernTreasury::Models::external_account_type?

        def account_type=: (
          ModernTreasury::Models::external_account_type
        ) -> ModernTreasury::Models::external_account_type

        attr_reader contact_details: ::Array[ModernTreasury::ContactDetailCreateRequest]?

        def contact_details=: (
          ::Array[ModernTreasury::ContactDetailCreateRequest]
        ) -> ::Array[ModernTreasury::ContactDetailCreateRequest]

        attr_accessor external_id: String?

        attr_reader ledger_account: ModernTreasury::LedgerAccountCreateRequest?

        def ledger_account=: (
          ModernTreasury::LedgerAccountCreateRequest
        ) -> ModernTreasury::LedgerAccountCreateRequest

        attr_reader metadata: ::Hash[Symbol, String]?

        def metadata=: (::Hash[Symbol, String]) -> ::Hash[Symbol, String]

        attr_accessor name: String?

        attr_reader party_address: ModernTreasury::AddressRequest?

        def party_address=: (
          ModernTreasury::AddressRequest
        ) -> ModernTreasury::AddressRequest

        attr_reader party_identifier: String?

        def party_identifier=: (String) -> String

        attr_reader party_name: String?

        def party_name=: (String) -> String

        attr_accessor party_type: ModernTreasury::Models::PaymentOrderUpdateParams::ReceivingAccount::party_type?

        attr_reader plaid_processor_token: String?

        def plaid_processor_token=: (String) -> String

        attr_reader routing_details: ::Array[ModernTreasury::PaymentOrderUpdateParams::ReceivingAccount::RoutingDetail]?

        def routing_details=: (
          ::Array[ModernTreasury::PaymentOrderUpdateParams::ReceivingAccount::RoutingDetail]
        ) -> ::Array[ModernTreasury::PaymentOrderUpdateParams::ReceivingAccount::RoutingDetail]

        def initialize: (
          ?account_details: ::Array[ModernTreasury::PaymentOrderUpdateParams::ReceivingAccount::AccountDetail],
          ?account_type: ModernTreasury::Models::external_account_type,
          ?contact_details: ::Array[ModernTreasury::ContactDetailCreateRequest],
          ?external_id: String?,
          ?ledger_account: ModernTreasury::LedgerAccountCreateRequest,
          ?metadata: ::Hash[Symbol, String],
          ?name: String?,
          ?party_address: ModernTreasury::AddressRequest,
          ?party_identifier: String,
          ?party_name: String,
          ?party_type: ModernTreasury::Models::PaymentOrderUpdateParams::ReceivingAccount::party_type?,
          ?plaid_processor_token: String,
          ?routing_details: ::Array[ModernTreasury::PaymentOrderUpdateParams::ReceivingAccount::RoutingDetail]
        ) -> void

        def to_hash: -> {
          account_details: ::Array[ModernTreasury::PaymentOrderUpdateParams::ReceivingAccount::AccountDetail],
          account_type: ModernTreasury::Models::external_account_type,
          contact_details: ::Array[ModernTreasury::ContactDetailCreateRequest],
          external_id: String?,
          ledger_account: ModernTreasury::LedgerAccountCreateRequest,
          metadata: ::Hash[Symbol, String],
          name: String?,
          party_address: ModernTreasury::AddressRequest,
          party_identifier: String,
          party_name: String,
          party_type: ModernTreasury::Models::PaymentOrderUpdateParams::ReceivingAccount::party_type?,
          plaid_processor_token: String,
          routing_details: ::Array[ModernTreasury::PaymentOrderUpdateParams::ReceivingAccount::RoutingDetail]
        }

        type account_detail =
          {
            account_number: String,
            account_number_type: ModernTreasury::Models::PaymentOrderUpdateParams::ReceivingAccount::AccountDetail::account_number_type
          }

        class AccountDetail < ModernTreasury::Internal::Type::BaseModel
          attr_accessor account_number: String

          attr_reader account_number_type: ModernTreasury::Models::PaymentOrderUpdateParams::ReceivingAccount::AccountDetail::account_number_type?

          def account_number_type=: (
            ModernTreasury::Models::PaymentOrderUpdateParams::ReceivingAccount::AccountDetail::account_number_type
          ) -> ModernTreasury::Models::PaymentOrderUpdateParams::ReceivingAccount::AccountDetail::account_number_type

          def initialize: (
            account_number: String,
            ?account_number_type: ModernTreasury::Models::PaymentOrderUpdateParams::ReceivingAccount::AccountDetail::account_number_type
          ) -> void

          def to_hash: -> {
            account_number: String,
            account_number_type: ModernTreasury::Models::PaymentOrderUpdateParams::ReceivingAccount::AccountDetail::account_number_type
          }

          type account_number_type =
            :au_number
            | :base_address
            | :card_token
            | :clabe
            | :ethereum_address
            | :hk_number
            | :iban
            | :id_number
            | :nz_number
            | :other
            | :pan
            | :polygon_address
            | :sg_number
            | :solana_address
            | :wallet_address

          module AccountNumberType
            extend ModernTreasury::Internal::Type::Enum

            AU_NUMBER: :au_number
            BASE_ADDRESS: :base_address
            CARD_TOKEN: :card_token
            CLABE: :clabe
            ETHEREUM_ADDRESS: :ethereum_address
            HK_NUMBER: :hk_number
            IBAN: :iban
            ID_NUMBER: :id_number
            NZ_NUMBER: :nz_number
            OTHER: :other
            PAN: :pan
            POLYGON_ADDRESS: :polygon_address
            SG_NUMBER: :sg_number
            SOLANA_ADDRESS: :solana_address
            WALLET_ADDRESS: :wallet_address

            def self?.values: -> ::Array[ModernTreasury::Models::PaymentOrderUpdateParams::ReceivingAccount::AccountDetail::account_number_type]
          end
        end

        type party_type = :business | :individual

        module PartyType
          extend ModernTreasury::Internal::Type::Enum

          BUSINESS: :business
          INDIVIDUAL: :individual

          def self?.values: -> ::Array[ModernTreasury::Models::PaymentOrderUpdateParams::ReceivingAccount::party_type]
        end

        type routing_detail =
          {
            routing_number: String,
            routing_number_type: ModernTreasury::Models::PaymentOrderUpdateParams::ReceivingAccount::RoutingDetail::routing_number_type,
            payment_type: ModernTreasury::Models::PaymentOrderUpdateParams::ReceivingAccount::RoutingDetail::payment_type
          }

        class RoutingDetail < ModernTreasury::Internal::Type::BaseModel
          attr_accessor routing_number: String

          attr_accessor routing_number_type: ModernTreasury::Models::PaymentOrderUpdateParams::ReceivingAccount::RoutingDetail::routing_number_type

          attr_reader payment_type: ModernTreasury::Models::PaymentOrderUpdateParams::ReceivingAccount::RoutingDetail::payment_type?

          def payment_type=: (
            ModernTreasury::Models::PaymentOrderUpdateParams::ReceivingAccount::RoutingDetail::payment_type
          ) -> ModernTreasury::Models::PaymentOrderUpdateParams::ReceivingAccount::RoutingDetail::payment_type

          def initialize: (
            routing_number: String,
            routing_number_type: ModernTreasury::Models::PaymentOrderUpdateParams::ReceivingAccount::RoutingDetail::routing_number_type,
            ?payment_type: ModernTreasury::Models::PaymentOrderUpdateParams::ReceivingAccount::RoutingDetail::payment_type
          ) -> void

          def to_hash: -> {
            routing_number: String,
            routing_number_type: ModernTreasury::Models::PaymentOrderUpdateParams::ReceivingAccount::RoutingDetail::routing_number_type,
            payment_type: ModernTreasury::Models::PaymentOrderUpdateParams::ReceivingAccount::RoutingDetail::payment_type
          }

          type routing_number_type =
            :aba
            | :au_bsb
            | :br_codigo
            | :ca_cpa
            | :chips
            | :cnaps
            | :dk_interbank_clearing_code
            | :gb_sort_code
            | :hk_interbank_clearing_code
            | :hu_interbank_clearing_code
            | :id_sknbi_code
            | :il_bank_code
            | :in_ifsc
            | :jp_zengin_code
            | :my_branch_code
            | :mx_bank_identifier
            | :nz_national_clearing_code
            | :pl_national_clearing_code
            | :se_bankgiro_clearing_code
            | :sg_interbank_clearing_code
            | :swift
            | :za_national_clearing_code

          module RoutingNumberType
            extend ModernTreasury::Internal::Type::Enum

            ABA: :aba
            AU_BSB: :au_bsb
            BR_CODIGO: :br_codigo
            CA_CPA: :ca_cpa
            CHIPS: :chips
            CNAPS: :cnaps
            DK_INTERBANK_CLEARING_CODE: :dk_interbank_clearing_code
            GB_SORT_CODE: :gb_sort_code
            HK_INTERBANK_CLEARING_CODE: :hk_interbank_clearing_code
            HU_INTERBANK_CLEARING_CODE: :hu_interbank_clearing_code
            ID_SKNBI_CODE: :id_sknbi_code
            IL_BANK_CODE: :il_bank_code
            IN_IFSC: :in_ifsc
            JP_ZENGIN_CODE: :jp_zengin_code
            MY_BRANCH_CODE: :my_branch_code
            MX_BANK_IDENTIFIER: :mx_bank_identifier
            NZ_NATIONAL_CLEARING_CODE: :nz_national_clearing_code
            PL_NATIONAL_CLEARING_CODE: :pl_national_clearing_code
            SE_BANKGIRO_CLEARING_CODE: :se_bankgiro_clearing_code
            SG_INTERBANK_CLEARING_CODE: :sg_interbank_clearing_code
            SWIFT: :swift
            ZA_NATIONAL_CLEARING_CODE: :za_national_clearing_code

            def self?.values: -> ::Array[ModernTreasury::Models::PaymentOrderUpdateParams::ReceivingAccount::RoutingDetail::routing_number_type]
          end

          type payment_type =
            :ach
            | :au_becs
            | :bacs
            | :base
            | :book
            | :card
            | :chats
            | :check
            | :cross_border
            | :dk_nets
            | :eft
            | :ethereum
            | :gb_fps
            | :hu_ics
            | :interac
            | :masav
            | :mx_ccen
            | :neft
            | :nics
            | :nz_becs
            | :pl_elixir
            | :polygon
            | :provxchange
            | :ro_sent
            | :rtp
            | :se_bankgirot
            | :sen
            | :sepa
            | :sg_giro
            | :sic
            | :signet
            | :sknbi
            | :solana
            | :wire
            | :zengin

          module PaymentType
            extend ModernTreasury::Internal::Type::Enum

            ACH: :ach
            AU_BECS: :au_becs
            BACS: :bacs
            BASE: :base
            BOOK: :book
            CARD: :card
            CHATS: :chats
            CHECK: :check
            CROSS_BORDER: :cross_border
            DK_NETS: :dk_nets
            EFT: :eft
            ETHEREUM: :ethereum
            GB_FPS: :gb_fps
            HU_ICS: :hu_ics
            INTERAC: :interac
            MASAV: :masav
            MX_CCEN: :mx_ccen
            NEFT: :neft
            NICS: :nics
            NZ_BECS: :nz_becs
            PL_ELIXIR: :pl_elixir
            POLYGON: :polygon
            PROVXCHANGE: :provxchange
            RO_SENT: :ro_sent
            RTP: :rtp
            SE_BANKGIROT: :se_bankgirot
            SEN: :sen
            SEPA: :sepa
            SG_GIRO: :sg_giro
            SIC: :sic
            SIGNET: :signet
            SKNBI: :sknbi
            SOLANA: :solana
            WIRE: :wire
            ZENGIN: :zengin

            def self?.values: -> ::Array[ModernTreasury::Models::PaymentOrderUpdateParams::ReceivingAccount::RoutingDetail::payment_type]
          end
        end
      end

      type reconciliation_status =
        :unreconciled | :tentatively_reconciled | :reconciled

      module ReconciliationStatus
        extend ModernTreasury::Internal::Type::Enum

        UNRECONCILED: :unreconciled
        TENTATIVELY_RECONCILED: :tentatively_reconciled
        RECONCILED: :reconciled

        def self?.values: -> ::Array[ModernTreasury::Models::PaymentOrderUpdateParams::reconciliation_status]
      end

      type status =
        :approved
        | :cancelled
        | :completed
        | :denied
        | :failed
        | :held
        | :needs_approval
        | :pending
        | :processing
        | :returned
        | :reversed
        | :sent
        | :stopped

      module Status
        extend ModernTreasury::Internal::Type::Enum

        APPROVED: :approved
        CANCELLED: :cancelled
        COMPLETED: :completed
        DENIED: :denied
        FAILED: :failed
        HELD: :held
        NEEDS_APPROVAL: :needs_approval
        PENDING: :pending
        PROCESSING: :processing
        RETURNED: :returned
        REVERSED: :reversed
        SENT: :sent
        STOPPED: :stopped

        def self?.values: -> ::Array[ModernTreasury::Models::PaymentOrderUpdateParams::status]
      end
    end
  end
end
