module ModernTreasury
  module Models
    type ping_response = { ping: String }

    class PingResponse < ModernTreasury::Internal::Type::BaseModel
      attr_accessor ping: String

      def initialize: (ping: String) -> void

      def to_hash: -> { ping: String }
    end
  end
end
