module ModernTreasury
  module Models
    type return_create_params =
      {
        returnable_id: String?,
        returnable_type: ModernTreasury::Models::ReturnCreateParams::returnable_type,
        additional_information: String?,
        code: ModernTreasury::Models::ReturnCreateParams::code?,
        corrections: ModernTreasury::ReturnCreateParams::Corrections?,
        data: top?,
        date_of_death: Date?,
        reason: String?,
        reconciliation_status: ModernTreasury::Models::ReturnCreateParams::reconciliation_status
      }
      & ModernTreasury::Internal::Type::request_parameters

    class ReturnCreateParams < ModernTreasury::Internal::Type::BaseModel
      extend ModernTreasury::Internal::Type::RequestParameters::Converter
      include ModernTreasury::Internal::Type::RequestParameters

      attr_accessor returnable_id: String?

      attr_accessor returnable_type: ModernTreasury::Models::ReturnCreateParams::returnable_type

      attr_accessor additional_information: String?

      attr_accessor code: ModernTreasury::Models::ReturnCreateParams::code?

      attr_accessor corrections: ModernTreasury::ReturnCreateParams::Corrections?

      attr_accessor data: top?

      attr_accessor date_of_death: Date?

      attr_accessor reason: String?

      attr_reader reconciliation_status: ModernTreasury::Models::ReturnCreateParams::reconciliation_status?

      def reconciliation_status=: (
        ModernTreasury::Models::ReturnCreateParams::reconciliation_status
      ) -> ModernTreasury::Models::ReturnCreateParams::reconciliation_status

      def initialize: (
        returnable_id: String?,
        returnable_type: ModernTreasury::Models::ReturnCreateParams::returnable_type,
        ?additional_information: String?,
        ?code: ModernTreasury::Models::ReturnCreateParams::code?,
        ?corrections: ModernTreasury::ReturnCreateParams::Corrections?,
        ?data: top?,
        ?date_of_death: Date?,
        ?reason: String?,
        ?reconciliation_status: ModernTreasury::Models::ReturnCreateParams::reconciliation_status,
        ?request_options: ModernTreasury::request_opts
      ) -> void

      def to_hash: -> {
        returnable_id: String?,
        returnable_type: ModernTreasury::Models::ReturnCreateParams::returnable_type,
        additional_information: String?,
        code: ModernTreasury::Models::ReturnCreateParams::code?,
        corrections: ModernTreasury::ReturnCreateParams::Corrections?,
        data: top?,
        date_of_death: Date?,
        reason: String?,
        reconciliation_status: ModernTreasury::Models::ReturnCreateParams::reconciliation_status,
        request_options: ModernTreasury::RequestOptions
      }

      type returnable_type = :incoming_payment_detail

      module ReturnableType
        extend ModernTreasury::Internal::Type::Enum

        INCOMING_PAYMENT_DETAIL: :incoming_payment_detail

        def self?.values: -> ::Array[ModernTreasury::Models::ReturnCreateParams::returnable_type]
      end

      type code =
        :"901"
        | :"902"
        | :"903"
        | :"904"
        | :"905"
        | :"907"
        | :"908"
        | :"909"
        | :"910"
        | :"911"
        | :"912"
        | :"914"
        | :C01
        | :C02
        | :C03
        | :C05
        | :C06
        | :C07
        | :C08
        | :C09
        | :C13
        | :C14
        | :R01
        | :R02
        | :R03
        | :R04
        | :R05
        | :R06
        | :R07
        | :R08
        | :R09
        | :R10
        | :R11
        | :R12
        | :R13
        | :R14
        | :R15
        | :R16
        | :R17
        | :R18
        | :R19
        | :R20
        | :R21
        | :R22
        | :R23
        | :R24
        | :R25
        | :R26
        | :R27
        | :R28
        | :R29
        | :R30
        | :R31
        | :R32
        | :R33
        | :R34
        | :R35
        | :R36
        | :R37
        | :R38
        | :R39
        | :R40
        | :R41
        | :R42
        | :R43
        | :R44
        | :R45
        | :R46
        | :R47
        | :R50
        | :R51
        | :R52
        | :R53
        | :R61
        | :R62
        | :R67
        | :R68
        | :R69
        | :R70
        | :R71
        | :R72
        | :R73
        | :R74
        | :R75
        | :R76
        | :R77
        | :R80
        | :R81
        | :R82
        | :R83
        | :R84
        | :R85
        | :currencycloud

      module Code
        extend ModernTreasury::Internal::Type::Enum

        CODE_901: :"901"
        CODE_902: :"902"
        CODE_903: :"903"
        CODE_904: :"904"
        CODE_905: :"905"
        CODE_907: :"907"
        CODE_908: :"908"
        CODE_909: :"909"
        CODE_910: :"910"
        CODE_911: :"911"
        CODE_912: :"912"
        CODE_914: :"914"
        C01: :C01
        C02: :C02
        C03: :C03
        C05: :C05
        C06: :C06
        C07: :C07
        C08: :C08
        C09: :C09
        C13: :C13
        C14: :C14
        R01: :R01
        R02: :R02
        R03: :R03
        R04: :R04
        R05: :R05
        R06: :R06
        R07: :R07
        R08: :R08
        R09: :R09
        R10: :R10
        R11: :R11
        R12: :R12
        R13: :R13
        R14: :R14
        R15: :R15
        R16: :R16
        R17: :R17
        R18: :R18
        R19: :R19
        R20: :R20
        R21: :R21
        R22: :R22
        R23: :R23
        R24: :R24
        R25: :R25
        R26: :R26
        R27: :R27
        R28: :R28
        R29: :R29
        R30: :R30
        R31: :R31
        R32: :R32
        R33: :R33
        R34: :R34
        R35: :R35
        R36: :R36
        R37: :R37
        R38: :R38
        R39: :R39
        R40: :R40
        R41: :R41
        R42: :R42
        R43: :R43
        R44: :R44
        R45: :R45
        R46: :R46
        R47: :R47
        R50: :R50
        R51: :R51
        R52: :R52
        R53: :R53
        R61: :R61
        R62: :R62
        R67: :R67
        R68: :R68
        R69: :R69
        R70: :R70
        R71: :R71
        R72: :R72
        R73: :R73
        R74: :R74
        R75: :R75
        R76: :R76
        R77: :R77
        R80: :R80
        R81: :R81
        R82: :R82
        R83: :R83
        R84: :R84
        R85: :R85
        CURRENCYCLOUD: :currencycloud

        def self?.values: -> ::Array[ModernTreasury::Models::ReturnCreateParams::code]
      end

      type corrections =
        {
          account_number: String?,
          company_id: String?,
          company_name: String?,
          individual_identification_number: String?,
          routing_number: String?,
          transaction_code: String?
        }

      class Corrections < ModernTreasury::Internal::Type::BaseModel
        attr_accessor account_number: String?

        attr_accessor company_id: String?

        attr_accessor company_name: String?

        attr_accessor individual_identification_number: String?

        attr_accessor routing_number: String?

        attr_accessor transaction_code: String?

        def initialize: (
          ?account_number: String?,
          ?company_id: String?,
          ?company_name: String?,
          ?individual_identification_number: String?,
          ?routing_number: String?,
          ?transaction_code: String?
        ) -> void

        def to_hash: -> {
          account_number: String?,
          company_id: String?,
          company_name: String?,
          individual_identification_number: String?,
          routing_number: String?,
          transaction_code: String?
        }
      end

      type reconciliation_status =
        :unreconciled | :tentatively_reconciled | :reconciled

      module ReconciliationStatus
        extend ModernTreasury::Internal::Type::Enum

        UNRECONCILED: :unreconciled
        TENTATIVELY_RECONCILED: :tentatively_reconciled
        RECONCILED: :reconciled

        def self?.values: -> ::Array[ModernTreasury::Models::ReturnCreateParams::reconciliation_status]
      end
    end
  end
end
