module ModernTreasury
  module Models
    type routing_detail_create_params =
      {
        accounts_type: ModernTreasury::Models::RoutingDetailCreateParams::accounts_type
      }
      & ModernTreasury::Internal::Type::request_parameters

    class RoutingDetailCreateParams < ModernTreasury::Models::RoutingDetailCreate
      extend ModernTreasury::Internal::Type::RequestParameters::Converter
      include ModernTreasury::Internal::Type::RequestParameters

      def accounts_type: -> ModernTreasury::Models::RoutingDetailCreateParams::accounts_type

      def accounts_type=: (
        ModernTreasury::Models::RoutingDetailCreateParams::accounts_type _
      ) -> ModernTreasury::Models::RoutingDetailCreateParams::accounts_type

      def initialize: (
        accounts_type: ModernTreasury::Models::RoutingDetailCreateParams::accounts_type,
        ?request_options: ModernTreasury::request_opts
      ) -> void

      def to_hash: -> {
        accounts_type: ModernTreasury::Models::RoutingDetailCreateParams::accounts_type,
        request_options: ModernTreasury::RequestOptions
      }

      type accounts_type = :external_accounts

      module AccountsType
        extend ModernTreasury::Internal::Type::Enum

        EXTERNAL_ACCOUNTS: :external_accounts

        def self?.values: -> ::Array[ModernTreasury::Models::RoutingDetailCreateParams::accounts_type]
      end
    end
  end
end
