module ModernTreasury
  module Models
    type routing_detail_delete_params =
      {
        accounts_type: ModernTreasury::Models::RoutingDetailDeleteParams::accounts_type,
        account_id: String
      }
      & ModernTreasury::Internal::Type::request_parameters

    class RoutingDetailDeleteParams < ModernTreasury::Internal::Type::BaseModel
      extend ModernTreasury::Internal::Type::RequestParameters::Converter
      include ModernTreasury::Internal::Type::RequestParameters

      attr_accessor accounts_type: ModernTreasury::Models::RoutingDetailDeleteParams::accounts_type

      attr_accessor account_id: String

      def initialize: (
        accounts_type: ModernTreasury::Models::RoutingDetailDeleteParams::accounts_type,
        account_id: String,
        ?request_options: ModernTreasury::request_opts
      ) -> void

      def to_hash: -> ModernTreasury::Models::routing_detail_delete_params

      type accounts_type = :external_accounts

      module AccountsType
        extend ModernTreasury::Internal::Type::Enum

        EXTERNAL_ACCOUNTS: :external_accounts

        def self?.values: -> ::Array[ModernTreasury::Models::RoutingDetailDeleteParams::accounts_type]
      end
    end
  end
end
