module ModernTreasury
  module Models
    type third_party_verification =
      {
        outcome: ModernTreasury::Models::ThirdPartyVerification::outcome,
        vendor: ModernTreasury::Models::ThirdPartyVerification::vendor,
        vendor_verification_id: String,
        verification_category: ModernTreasury::Models::ThirdPartyVerification::verification_category,
        verification_method: String,
        verification_time: Time,
        comment: String?
      }

    class ThirdPartyVerification < ModernTreasury::Internal::Type::BaseModel
      attr_accessor outcome: ModernTreasury::Models::ThirdPartyVerification::outcome

      attr_accessor vendor: ModernTreasury::Models::ThirdPartyVerification::vendor

      attr_accessor vendor_verification_id: String

      attr_accessor verification_category: ModernTreasury::Models::ThirdPartyVerification::verification_category

      attr_accessor verification_method: String

      attr_accessor verification_time: Time

      attr_accessor comment: String?

      def initialize: (
        outcome: ModernTreasury::Models::ThirdPartyVerification::outcome,
        vendor: ModernTreasury::Models::ThirdPartyVerification::vendor,
        vendor_verification_id: String,
        verification_category: ModernTreasury::Models::ThirdPartyVerification::verification_category,
        verification_method: String,
        verification_time: Time,
        ?comment: String?
      ) -> void

      def to_hash: -> {
        outcome: ModernTreasury::Models::ThirdPartyVerification::outcome,
        vendor: ModernTreasury::Models::ThirdPartyVerification::vendor,
        vendor_verification_id: String,
        verification_category: ModernTreasury::Models::ThirdPartyVerification::verification_category,
        verification_method: String,
        verification_time: Time,
        comment: String?
      }

      type outcome = :passed | :failed

      module Outcome
        extend ModernTreasury::Internal::Type::Enum

        PASSED: :passed
        FAILED: :failed

        def self?.values: -> ::Array[ModernTreasury::Models::ThirdPartyVerification::outcome]
      end

      type vendor = :persona | :middesk | :alloy | :sumsub | :veriff

      module Vendor
        extend ModernTreasury::Internal::Type::Enum

        PERSONA: :persona
        MIDDESK: :middesk
        ALLOY: :alloy
        SUMSUB: :sumsub
        VERIFF: :veriff

        def self?.values: -> ::Array[ModernTreasury::Models::ThirdPartyVerification::vendor]
      end

      type verification_category =
        :legal_name
        | :date_of_birth
        | :address
        | :government_id_number
        | :adverse_media

      module VerificationCategory
        extend ModernTreasury::Internal::Type::Enum

        LEGAL_NAME: :legal_name
        DATE_OF_BIRTH: :date_of_birth
        ADDRESS: :address
        GOVERNMENT_ID_NUMBER: :government_id_number
        ADVERSE_MEDIA: :adverse_media

        def self?.values: -> ::Array[ModernTreasury::Models::ThirdPartyVerification::verification_category]
      end
    end
  end
end
