module ModernTreasury
  module Models
    type transaction_delete_params =
      {  } & ModernTreasury::Internal::Type::request_parameters

    class TransactionDeleteParams < ModernTreasury::BaseModel
      extend ModernTreasury::Internal::Type::RequestParameters::Converter
      include ModernTreasury::Internal::Type::RequestParameters

      def initialize: (?request_options: ModernTreasury::request_opts) -> void

      def to_hash: -> ModernTreasury::Models::transaction_delete_params
    end
  end
end
