module ModernTreasury
  module Models
    type transaction_list_params =
      {
        after_cursor: String?,
        as_of_date_end: Date,
        as_of_date_start: Date,
        counterparty_id: String,
        description: String,
        direction: String,
        internal_account_id: String,
        metadata: ::Hash[Symbol, String],
        payment_type: String,
        per_page: Integer,
        posted: bool,
        transactable_type: String,
        vendor_id: String,
        virtual_account_id: String
      }
      & ModernTreasury::Internal::Type::request_parameters

    class TransactionListParams < ModernTreasury::BaseModel
      extend ModernTreasury::Internal::Type::RequestParameters::Converter
      include ModernTreasury::Internal::Type::RequestParameters

      attr_accessor after_cursor: String?

      attr_reader as_of_date_end: Date?

      def as_of_date_end=: (Date) -> Date

      attr_reader as_of_date_start: Date?

      def as_of_date_start=: (Date) -> Date

      attr_reader counterparty_id: String?

      def counterparty_id=: (String) -> String

      attr_reader description: String?

      def description=: (String) -> String

      attr_reader direction: String?

      def direction=: (String) -> String

      attr_reader internal_account_id: String?

      def internal_account_id=: (String) -> String

      attr_reader metadata: ::Hash[Symbol, String]?

      def metadata=: (::Hash[Symbol, String]) -> ::Hash[Symbol, String]

      attr_reader payment_type: String?

      def payment_type=: (String) -> String

      attr_reader per_page: Integer?

      def per_page=: (Integer) -> Integer

      attr_reader posted: bool?

      def posted=: (bool) -> bool

      attr_reader transactable_type: String?

      def transactable_type=: (String) -> String

      attr_reader vendor_id: String?

      def vendor_id=: (String) -> String

      attr_reader virtual_account_id: String?

      def virtual_account_id=: (String) -> String

      def initialize: (
        ?after_cursor: String?,
        ?as_of_date_end: Date,
        ?as_of_date_start: Date,
        ?counterparty_id: String,
        ?description: String,
        ?direction: String,
        ?internal_account_id: String,
        ?metadata: ::Hash[Symbol, String],
        ?payment_type: String,
        ?per_page: Integer,
        ?posted: bool,
        ?transactable_type: String,
        ?vendor_id: String,
        ?virtual_account_id: String,
        ?request_options: ModernTreasury::request_opts
      ) -> void

      def to_hash: -> ModernTreasury::Models::transaction_list_params
    end
  end
end
