module ModernTreasury
  module Models
    type transaction_direction = :credit | :debit

    module TransactionDirection
      extend ModernTreasury::Enum

      CREDIT: :credit
      DEBIT: :debit

      def self.values: -> ::Array[ModernTreasury::Models::transaction_direction]
    end
  end
end
