module ModernTreasury
  module Models
    type transaction_retrieve_params = {  } & ModernTreasury::request_parameters

    class TransactionRetrieveParams < ModernTreasury::BaseModel
      extend ModernTreasury::RequestParameters::Converter
      include ModernTreasury::RequestParameters

      def initialize: (?request_options: ModernTreasury::request_opts) -> void

      def to_hash: -> ModernTreasury::Models::transaction_retrieve_params
    end
  end
end
