module ModernTreasury
  module Models
    type transaction_update = { metadata: ::Hash[Symbol, String] }

    class TransactionUpdate < ModernTreasury::Internal::Type::BaseModel
      attr_reader metadata: ::Hash[Symbol, String]?

      def metadata=: (::Hash[Symbol, String]) -> ::Hash[Symbol, String]

      def initialize: (?metadata: ::Hash[Symbol, String]) -> void

      def to_hash: -> { metadata: ::Hash[Symbol, String] }
    end
  end
end
