module ModernTreasury
  module Models
    type virtual_account_create_params =
      {
        internal_account_id: String,
        name: String,
        account_details: ::Array[ModernTreasury::AccountDetailCreate],
        counterparty_id: String,
        credit_ledger_account_id: String,
        debit_ledger_account_id: String,
        description: String,
        ledger_account: ModernTreasury::LedgerAccountCreateRequest,
        metadata: ::Hash[Symbol, String],
        routing_details: ::Array[ModernTreasury::RoutingDetailCreate]
      }
      & ModernTreasury::Internal::Type::request_parameters

    class VirtualAccountCreateParams < ModernTreasury::Internal::Type::BaseModel
      extend ModernTreasury::Internal::Type::RequestParameters::Converter
      include ModernTreasury::Internal::Type::RequestParameters

      attr_accessor internal_account_id: String

      attr_accessor name: String

      attr_reader account_details: ::Array[ModernTreasury::AccountDetailCreate]?

      def account_details=: (
        ::Array[ModernTreasury::AccountDetailCreate]
      ) -> ::Array[ModernTreasury::AccountDetailCreate]

      attr_reader counterparty_id: String?

      def counterparty_id=: (String) -> String

      attr_reader credit_ledger_account_id: String?

      def credit_ledger_account_id=: (String) -> String

      attr_reader debit_ledger_account_id: String?

      def debit_ledger_account_id=: (String) -> String

      attr_reader description: String?

      def description=: (String) -> String

      attr_reader ledger_account: ModernTreasury::LedgerAccountCreateRequest?

      def ledger_account=: (
        ModernTreasury::LedgerAccountCreateRequest
      ) -> ModernTreasury::LedgerAccountCreateRequest

      attr_reader metadata: ::Hash[Symbol, String]?

      def metadata=: (::Hash[Symbol, String]) -> ::Hash[Symbol, String]

      attr_reader routing_details: ::Array[ModernTreasury::RoutingDetailCreate]?

      def routing_details=: (
        ::Array[ModernTreasury::RoutingDetailCreate]
      ) -> ::Array[ModernTreasury::RoutingDetailCreate]

      def initialize: (
        internal_account_id: String,
        name: String,
        ?account_details: ::Array[ModernTreasury::AccountDetailCreate],
        ?counterparty_id: String,
        ?credit_ledger_account_id: String,
        ?debit_ledger_account_id: String,
        ?description: String,
        ?ledger_account: ModernTreasury::LedgerAccountCreateRequest,
        ?metadata: ::Hash[Symbol, String],
        ?routing_details: ::Array[ModernTreasury::RoutingDetailCreate],
        ?request_options: ModernTreasury::request_opts
      ) -> void

      def to_hash: -> {
        internal_account_id: String,
        name: String,
        account_details: ::Array[ModernTreasury::AccountDetailCreate],
        counterparty_id: String,
        credit_ledger_account_id: String,
        debit_ledger_account_id: String,
        description: String,
        ledger_account: ModernTreasury::LedgerAccountCreateRequest,
        metadata: ::Hash[Symbol, String],
        routing_details: ::Array[ModernTreasury::RoutingDetailCreate],
        request_options: ModernTreasury::RequestOptions
      }
    end
  end
end
