module ModernTreasury
  module Models
    type virtual_account_delete_params =
      {  } & ModernTreasury::request_parameters

    class VirtualAccountDeleteParams < ModernTreasury::BaseModel
      extend ModernTreasury::Type::RequestParameters::Converter
      include ModernTreasury::RequestParameters

      def initialize: (?request_options: ModernTreasury::request_opts) -> void

      def to_hash: -> ModernTreasury::Models::virtual_account_delete_params
    end
  end
end
