module ModernTreasury
  module Models
    type virtual_account_delete_params =
      {  } & ModernTreasury::Internal::Type::request_parameters

    class VirtualAccountDeleteParams < ModernTreasury::Internal::Type::BaseModel
      extend ModernTreasury::Internal::Type::RequestParameters::Converter
      include ModernTreasury::Internal::Type::RequestParameters

      def initialize: (?request_options: ModernTreasury::request_opts) -> void
    end
  end
end
