module ModernTreasury
  module Models
    type virtual_account_setting_create_params =
      {
        allocation_type: String,
        internal_account_id: String,
        allocation_identifier: String?,
        allocation_length: Integer?,
        allocation_range_end: String?,
        allocation_range_start: String?,
        external_id: String?,
        generated_allocation_identifier_length: Integer?
      }
      & ModernTreasury::Internal::Type::request_parameters

    class VirtualAccountSettingCreateParams < ModernTreasury::Internal::Type::BaseModel
      extend ModernTreasury::Internal::Type::RequestParameters::Converter
      include ModernTreasury::Internal::Type::RequestParameters

      attr_accessor allocation_type: String

      attr_accessor internal_account_id: String

      attr_accessor allocation_identifier: String?

      attr_accessor allocation_length: Integer?

      attr_accessor allocation_range_end: String?

      attr_accessor allocation_range_start: String?

      attr_accessor external_id: String?

      attr_accessor generated_allocation_identifier_length: Integer?

      def initialize: (
        allocation_type: String,
        internal_account_id: String,
        ?allocation_identifier: String?,
        ?allocation_length: Integer?,
        ?allocation_range_end: String?,
        ?allocation_range_start: String?,
        ?external_id: String?,
        ?generated_allocation_identifier_length: Integer?,
        ?request_options: ModernTreasury::request_opts
      ) -> void

      def to_hash: -> {
        allocation_type: String,
        internal_account_id: String,
        allocation_identifier: String?,
        allocation_length: Integer?,
        allocation_range_end: String?,
        allocation_range_start: String?,
        external_id: String?,
        generated_allocation_identifier_length: Integer?,
        request_options: ModernTreasury::RequestOptions
      }
    end
  end
end
