module ModernTreasury
  module Resources
    class LedgerAccountSettlements
      class AccountEntries
        def update: (
          String id,
          ledger_entry_ids: ::Array[String]?,
          ?request_options: ModernTreasury::request_opts
        ) -> nil

        def delete: (
          String id,
          ledger_entry_ids: ::Array[String]?,
          ?request_options: ModernTreasury::request_opts
        ) -> nil

        def initialize: (client: ModernTreasury::Client) -> void
      end
    end
  end
end
