module ModernTreasury
  module Models
    module InternalAccounts
      type balance_report_delete_params =
        { internal_account_id: String }
        & ModernTreasury::Internal::Type::request_parameters

      class BalanceReportDeleteParams < ModernTreasury::Internal::Type::BaseModel
        extend ModernTreasury::Internal::Type::RequestParameters::Converter
        include ModernTreasury::Internal::Type::RequestParameters

        attr_accessor internal_account_id: String

        def initialize: (
          internal_account_id: String,
          ?request_options: ModernTreasury::request_opts
        ) -> void

        def to_hash: -> {
          internal_account_id: String,
          request_options: ModernTreasury::RequestOptions
        }
      end
    end
  end
end
