module ModernTreasury
  module Models
    module InternalAccounts
      type balance_report_list_params =
        {
          after_cursor: String?,
          as_of_date: Date,
          balance_report_type: ModernTreasury::Models::InternalAccounts::BalanceReportListParams::balance_report_type,
          per_page: Integer
        }
        & ModernTreasury::request_parameters

      class BalanceReportListParams < ModernTreasury::BaseModel
        extend ModernTreasury::RequestParameters::Converter
        include ModernTreasury::RequestParameters

        attr_accessor after_cursor: String?

        attr_reader as_of_date: Date?

        def as_of_date=: (Date) -> Date

        attr_reader balance_report_type: ModernTreasury::Models::InternalAccounts::BalanceReportListParams::balance_report_type?

        def balance_report_type=: (
          ModernTreasury::Models::InternalAccounts::BalanceReportListParams::balance_report_type
        ) -> ModernTreasury::Models::InternalAccounts::BalanceReportListParams::balance_report_type

        attr_reader per_page: Integer?

        def per_page=: (Integer) -> Integer

        def initialize:
          (
            after_cursor: String?,
            as_of_date: Date,
            balance_report_type: ModernTreasury::Models::InternalAccounts::BalanceReportListParams::balance_report_type,
            per_page: Integer,
            request_options: ModernTreasury::request_opts
          ) -> void
          | (
            ?ModernTreasury::Models::InternalAccounts::balance_report_list_params
            | ModernTreasury::BaseModel data
          ) -> void

        def to_hash: -> ModernTreasury::Models::InternalAccounts::balance_report_list_params

        type balance_report_type =
          :intraday | :other | :previous_day | :real_time

        class BalanceReportType < ModernTreasury::Enum
          INTRADAY: :intraday
          OTHER: :other
          PREVIOUS_DAY: :previous_day
          REAL_TIME: :real_time

          def self.values: -> ::Array[ModernTreasury::Models::InternalAccounts::BalanceReportListParams::balance_report_type]
        end
      end
    end
  end
end
