module ModernTreasury
  module Models
    module InternalAccounts
      type balance_report_retrieve_params =
        { internal_account_id: String }
        & ModernTreasury::Internal::Type::request_parameters

      class BalanceReportRetrieveParams < ModernTreasury::Internal::Type::BaseModel
        extend ModernTreasury::Internal::Type::RequestParameters::Converter
        include ModernTreasury::Internal::Type::RequestParameters

        attr_accessor internal_account_id: String

        def initialize: (
          internal_account_id: String,
          ?request_options: ModernTreasury::request_opts
        ) -> void

        def to_hash: -> {
          internal_account_id: String,
          request_options: ModernTreasury::RequestOptions
        }

        type id = String | :latest

        module ID
          extend ModernTreasury::Internal::Type::Union

          def self?.variants: -> ::Array[ModernTreasury::Models::InternalAccounts::BalanceReportRetrieveParams::id]

          LATEST: :latest
        end
      end
    end
  end
end
