module ModernTreasury
  module Models
    module InternalAccounts
      type balance_report_create_params =
        {
          as_of_date: Date,
          as_of_time: String,
          balance_report_type: ModernTreasury::Models::InternalAccounts::BalanceReportCreateParams::balance_report_type,
          balances: ::Array[ModernTreasury::Models::InternalAccounts::BalanceReportCreateParams::Balance]
        }
        & ModernTreasury::request_parameters

      class BalanceReportCreateParams < ModernTreasury::BaseModel
        extend ModernTreasury::RequestParameters::Converter
        include ModernTreasury::RequestParameters

        attr_accessor as_of_date: Date

        attr_accessor as_of_time: String

        attr_accessor balance_report_type: ModernTreasury::Models::InternalAccounts::BalanceReportCreateParams::balance_report_type

        attr_accessor balances: ::Array[ModernTreasury::Models::InternalAccounts::BalanceReportCreateParams::Balance]

        def initialize:
          (
            as_of_date: Date,
            as_of_time: String,
            balance_report_type: ModernTreasury::Models::InternalAccounts::BalanceReportCreateParams::balance_report_type,
            balances: ::Array[ModernTreasury::Models::InternalAccounts::BalanceReportCreateParams::Balance],
            ?request_options: ModernTreasury::request_opts
          ) -> void
          | (
            ?ModernTreasury::Models::InternalAccounts::balance_report_create_params
            | ModernTreasury::BaseModel data
          ) -> void

        def to_hash: -> ModernTreasury::Models::InternalAccounts::balance_report_create_params

        type balance_report_type =
          :intraday | :other | :previous_day | :real_time

        class BalanceReportType < ModernTreasury::Enum
          INTRADAY: :intraday
          OTHER: :other
          PREVIOUS_DAY: :previous_day
          REAL_TIME: :real_time

          def self.values: -> ::Array[ModernTreasury::Models::InternalAccounts::BalanceReportCreateParams::balance_report_type]
        end

        type balance =
          {
            amount: Integer,
            balance_type: ModernTreasury::Models::InternalAccounts::BalanceReportCreateParams::Balance::balance_type,
            vendor_code: String,
            vendor_code_type: String?
          }

        class Balance < ModernTreasury::BaseModel
          attr_accessor amount: Integer

          attr_accessor balance_type: ModernTreasury::Models::InternalAccounts::BalanceReportCreateParams::Balance::balance_type

          attr_accessor vendor_code: String

          attr_accessor vendor_code_type: String?

          def initialize:
            (
              amount: Integer,
              balance_type: ModernTreasury::Models::InternalAccounts::BalanceReportCreateParams::Balance::balance_type,
              vendor_code: String,
              vendor_code_type: String?
            ) -> void
            | (
              ?ModernTreasury::Models::InternalAccounts::BalanceReportCreateParams::balance
              | ModernTreasury::BaseModel data
            ) -> void

          def to_hash: -> ModernTreasury::Models::InternalAccounts::BalanceReportCreateParams::balance

          type balance_type =
            :closing_available
            | :closing_ledger
            | :current_available
            | :current_ledger
            | :opening_available
            | :opening_available_next_business_day
            | :opening_ledger
            | :other
            | :previously_closed_book

          class BalanceType < ModernTreasury::Enum
            CLOSING_AVAILABLE: :closing_available
            CLOSING_LEDGER: :closing_ledger
            CURRENT_AVAILABLE: :current_available
            CURRENT_LEDGER: :current_ledger
            OPENING_AVAILABLE: :opening_available
            OPENING_AVAILABLE_NEXT_BUSINESS_DAY: :opening_available_next_business_day
            OPENING_LEDGER: :opening_ledger
            OTHER: :other
            PREVIOUSLY_CLOSED_BOOK: :previously_closed_book

            def self.values: -> ::Array[ModernTreasury::Models::InternalAccounts::BalanceReportCreateParams::Balance::balance_type]
          end
        end
      end
    end
  end
end
