module ModernTreasury
  module Models
    module InternalAccounts
      type balance_report_delete_params =
        { internal_account_id: String } & ModernTreasury::request_parameters

      class BalanceReportDeleteParams < ModernTreasury::BaseModel
        extend ModernTreasury::RequestParameters::Converter
        include ModernTreasury::RequestParameters

        attr_accessor internal_account_id: String

        def initialize:
          (
            internal_account_id: String,
            request_options: ModernTreasury::request_opts
          ) -> void
          | (
            ?ModernTreasury::Models::InternalAccounts::balance_report_delete_params
            | ModernTreasury::BaseModel data
          ) -> void

        def to_hash: -> ModernTreasury::Models::InternalAccounts::balance_report_delete_params
      end
    end
  end
end
