# frozen_string_literal: true

module ModernTreasury
  module Models
    class PaymentOrderCreateAsyncParams < ModernTreasury::BaseModel
      # @!attribute amount
      #   Value in specified currency's smallest unit. e.g. $10 would be represented as 1000 (cents). For RTP, the maximum amount allowed by the network is $100,000.
      #   @return [Integer]
      required :amount, Integer

      # @!attribute direction
      #   One of `credit`, `debit`. Describes the direction money is flowing in the transaction. A `credit` moves money from your account to someone else's. A `debit` pulls money from someone else's account to your own. Note that wire, rtp, and check payments will always be `credit`.
      #   @return [Symbol, ModernTreasury::Models::PaymentOrderCreateAsyncParams::Direction]
      required :direction, enum: -> { ModernTreasury::Models::PaymentOrderCreateAsyncParams::Direction }

      # @!attribute originating_account_id
      #   The ID of one of your organization's internal accounts.
      #   @return [String]
      required :originating_account_id, String

      # @!attribute type
      #   One of `ach`, `se_bankgirot`, `eft`, `wire`, `check`, `sen`, `book`, `rtp`, `sepa`, `bacs`, `au_becs`, `interac`, `neft`, `nics`, `nz_national_clearing_code`, `sic`, `signet`, `provexchange`, `zengin`.
      #   @return [Symbol, ModernTreasury::Models::PaymentOrderType]
      required :type, enum: -> { ModernTreasury::Models::PaymentOrderType }

      # @!attribute accounting
      #   @return [ModernTreasury::Models::PaymentOrderCreateAsyncParams::Accounting]
      optional :accounting, -> { ModernTreasury::Models::PaymentOrderCreateAsyncParams::Accounting }

      # @!attribute accounting_category_id
      #   The ID of one of your accounting categories. Note that these will only be accessible if your accounting system has been connected.
      #   @return [String]
      optional :accounting_category_id, String

      # @!attribute accounting_ledger_class_id
      #   The ID of one of your accounting ledger classes. Note that these will only be accessible if your accounting system has been connected.
      #   @return [String]
      optional :accounting_ledger_class_id, String

      # @!attribute charge_bearer
      #   The party that will pay the fees for the payment order. Only applies to wire payment orders. Can be one of shared, sender, or receiver, which correspond respectively with the SWIFT 71A values `SHA`, `OUR`, `BEN`.
      #   @return [Symbol, ModernTreasury::Models::PaymentOrderCreateAsyncParams::ChargeBearer]
      optional :charge_bearer,
               enum: -> {
                 ModernTreasury::Models::PaymentOrderCreateAsyncParams::ChargeBearer
               }

      # @!attribute currency
      #   Defaults to the currency of the originating account.
      #   @return [Symbol, ModernTreasury::Models::Currency]
      optional :currency, enum: -> { ModernTreasury::Models::Currency }

      # @!attribute description
      #   An optional description for internal use.
      #   @return [String]
      optional :description, String

      # @!attribute effective_date
      #   Date transactions are to be posted to the participants' account. Defaults to the current business day or the next business day if the current day is a bank holiday or weekend. Format: yyyy-mm-dd.
      #   @return [Date]
      optional :effective_date, Date

      # @!attribute expires_at
      #   RFP payments require an expires_at. This value must be past the effective_date.
      #   @return [Time]
      optional :expires_at, Time

      # @!attribute fallback_type
      #   A payment type to fallback to if the original type is not valid for the receiving account. Currently, this only supports falling back from RTP to ACH (type=rtp and fallback_type=ach)
      #   @return [Symbol, ModernTreasury::Models::PaymentOrderCreateAsyncParams::FallbackType]
      optional :fallback_type,
               enum: -> {
                 ModernTreasury::Models::PaymentOrderCreateAsyncParams::FallbackType
               }

      # @!attribute foreign_exchange_contract
      #   If present, indicates a specific foreign exchange contract number that has been generated by your financial institution.
      #   @return [String]
      optional :foreign_exchange_contract, String

      # @!attribute foreign_exchange_indicator
      #   Indicates the type of FX transfer to initiate, can be either `variable_to_fixed`, `fixed_to_variable`, or `null` if the payment order currency matches the originating account currency.
      #   @return [Symbol, ModernTreasury::Models::PaymentOrderCreateAsyncParams::ForeignExchangeIndicator]
      optional :foreign_exchange_indicator,
               enum: -> { ModernTreasury::Models::PaymentOrderCreateAsyncParams::ForeignExchangeIndicator }

      # @!attribute ledger_transaction
      #   Specifies a ledger transaction object that will be created with the payment order. If the ledger transaction cannot be created, then the payment order creation will fail. The resulting ledger transaction will mirror the status of the payment order.
      #   @return [ModernTreasury::Models::PaymentOrderCreateAsyncParams::LedgerTransaction]
      optional :ledger_transaction,
               -> { ModernTreasury::Models::PaymentOrderCreateAsyncParams::LedgerTransaction }

      # @!attribute ledger_transaction_id
      #   Either ledger_transaction or ledger_transaction_id can be provided. Only a pending ledger transaction can be attached upon payment order creation. Once the payment order is created, the status of the ledger transaction tracks the payment order automatically.
      #   @return [String]
      optional :ledger_transaction_id, String

      # @!attribute line_items
      #   An array of line items that must sum up to the amount of the payment order.
      #   @return [Array<ModernTreasury::Models::PaymentOrderCreateAsyncParams::LineItem>]
      optional :line_items,
               ModernTreasury::ArrayOf.new(
                 -> {
                   ModernTreasury::Models::PaymentOrderCreateAsyncParams::LineItem
                 }
               )

      # @!attribute metadata
      #   Additional data represented as key-value pairs. Both the key and value must be strings.
      #   @return [Hash]
      optional :metadata, Hash

      # @!attribute nsf_protected
      #   A boolean to determine if NSF Protection is enabled for this payment order. Note that this setting must also be turned on in your organization settings page.
      #   @return [Boolean]
      optional :nsf_protected, ModernTreasury::BooleanModel

      # @!attribute originating_party_name
      #   If present, this will replace your default company name on receiver's bank statement. This field can only be used for ACH payments currently. For ACH, only the first 16 characters of this string will be used. Any additional characters will be truncated.
      #   @return [String]
      optional :originating_party_name, String

      # @!attribute priority
      #   Either `normal` or `high`. For ACH and EFT payments, `high` represents a same-day ACH or EFT transfer, respectively. For check payments, `high` can mean an overnight check rather than standard mail.
      #   @return [Symbol, ModernTreasury::Models::PaymentOrderCreateAsyncParams::Priority]
      optional :priority, enum: -> { ModernTreasury::Models::PaymentOrderCreateAsyncParams::Priority }

      # @!attribute process_after
      #   If present, Modern Treasury will not process the payment until after this time. If `process_after` is past the cutoff for `effective_date`, `process_after` will take precedence and `effective_date` will automatically update to reflect the earliest possible sending date after `process_after`. Format is ISO8601 timestamp.
      #   @return [Time]
      optional :process_after, Time

      # @!attribute purpose
      #   For `wire`, this is usually the purpose which is transmitted via the "InstrForDbtrAgt" field in the ISO20022 file. For `eft`, this field is the 3 digit CPA Code that will be attached to the payment.
      #   @return [String]
      optional :purpose, String

      # @!attribute receiving_account
      #   Either `receiving_account` or `receiving_account_id` must be present. When using `receiving_account_id`, you may pass the id of an external account or an internal account.
      #   @return [ModernTreasury::Models::PaymentOrderCreateAsyncParams::ReceivingAccount]
      optional :receiving_account,
               -> { ModernTreasury::Models::PaymentOrderCreateAsyncParams::ReceivingAccount }

      # @!attribute receiving_account_id
      #   Either `receiving_account` or `receiving_account_id` must be present. When using `receiving_account_id`, you may pass the id of an external account or an internal account.
      #   @return [String]
      optional :receiving_account_id, String

      # @!attribute remittance_information
      #   For `ach`, this field will be passed through on an addenda record. For `wire` payments the field will be passed through as the "Originator to Beneficiary Information", also known as OBI or Fedwire tag 6000.
      #   @return [String]
      optional :remittance_information, String

      # @!attribute send_remittance_advice
      #   Send an email to the counterparty when the payment order is sent to the bank. If `null`, `send_remittance_advice` on the Counterparty is used.
      #   @return [Boolean]
      optional :send_remittance_advice, ModernTreasury::BooleanModel

      # @!attribute statement_descriptor
      #   An optional descriptor which will appear in the receiver's statement. For `check` payments this field will be used as the memo line. For `ach` the maximum length is 10 characters. Note that for ACH payments, the name on your bank account will be included automatically by the bank, so you can use the characters for other useful information. For `eft` the maximum length is 15 characters.
      #   @return [String]
      optional :statement_descriptor, String

      # @!attribute subtype
      #   An additional layer of classification for the type of payment order you are doing. This field is only used for `ach` payment orders currently. For `ach`  payment orders, the `subtype`  represents the SEC code. We currently support `CCD`, `PPD`, `IAT`, `CTX`, `WEB`, `CIE`, and `TEL`.
      #   @return [Symbol, ModernTreasury::Models::PaymentOrderSubtype]
      optional :subtype, enum: -> { ModernTreasury::Models::PaymentOrderSubtype }

      # @!attribute transaction_monitoring_enabled
      #   A flag that determines whether a payment order should go through transaction monitoring.
      #   @return [Boolean]
      optional :transaction_monitoring_enabled, ModernTreasury::BooleanModel

      # @!attribute ultimate_originating_party_identifier
      #   Identifier of the ultimate originator of the payment order.
      #   @return [String]
      optional :ultimate_originating_party_identifier, String

      # @!attribute ultimate_originating_party_name
      #   Name of the ultimate originator of the payment order.
      #   @return [String]
      optional :ultimate_originating_party_name, String

      # @!attribute ultimate_receiving_party_identifier
      #   Identifier of the ultimate funds recipient.
      #   @return [String]
      optional :ultimate_receiving_party_identifier, String

      # @!attribute ultimate_receiving_party_name
      #   Name of the ultimate funds recipient.
      #   @return [String]
      optional :ultimate_receiving_party_name, String

      # One of `credit`, `debit`. Describes the direction money is flowing in the transaction. A `credit` moves money from your account to someone else's. A `debit` pulls money from someone else's account to your own. Note that wire, rtp, and check payments will always be `credit`.
      class Direction < ModernTreasury::Enum
        CREDIT = :credit
        DEBIT = :debit
      end

      class Accounting < ModernTreasury::BaseModel
        # @!attribute account_id
        #   The ID of one of your accounting categories. Note that these will only be accessible if your accounting system has been connected.
        #   @return [String]
        optional :account_id, String

        # @!attribute class_id
        #   The ID of one of the class objects in your accounting system. Class objects track segments of your business independent of client or project. Note that these will only be accessible if your accounting system has been connected.
        #   @return [String]
        optional :class_id, String

        # @!parse
        #   # Create a new instance of Accounting from a Hash of raw data.
        #   #
        #   # @param data [Hash{Symbol => Object}] .
        #   #   @option data [String, nil] :account_id The ID of one of your accounting categories. Note that these will only be
        #   #     accessible if your accounting system has been connected.
        #   #   @option data [String, nil] :class_id The ID of one of the class objects in your accounting system. Class objects
        #   #     track segments of your business independent of client or project. Note that
        #   #     these will only be accessible if your accounting system has been connected.
        #   def initialize(data = {}) = super
      end

      # The party that will pay the fees for the payment order. Only applies to wire payment orders. Can be one of shared, sender, or receiver, which correspond respectively with the SWIFT 71A values `SHA`, `OUR`, `BEN`.
      class ChargeBearer < ModernTreasury::Enum
        SHARED = :shared
        SENDER = :sender
        RECEIVER = :receiver
      end

      # A payment type to fallback to if the original type is not valid for the receiving account. Currently, this only supports falling back from RTP to ACH (type=rtp and fallback_type=ach)
      class FallbackType < ModernTreasury::Enum
        ACH = :ach
      end

      # Indicates the type of FX transfer to initiate, can be either `variable_to_fixed`, `fixed_to_variable`, or `null` if the payment order currency matches the originating account currency.
      class ForeignExchangeIndicator < ModernTreasury::Enum
        FIXED_TO_VARIABLE = :fixed_to_variable
        VARIABLE_TO_FIXED = :variable_to_fixed
      end

      class LedgerTransaction < ModernTreasury::BaseModel
        # @!attribute ledger_entries
        #   An array of ledger entry objects.
        #   @return [Array<ModernTreasury::Models::PaymentOrderCreateAsyncParams::LedgerTransaction::LedgerEntry>]
        required :ledger_entries,
                 ModernTreasury::ArrayOf.new(
                   -> {
                     ModernTreasury::Models::PaymentOrderCreateAsyncParams::LedgerTransaction::LedgerEntry
                   }
                 )

        # @!attribute description
        #   An optional description for internal use.
        #   @return [String]
        optional :description, String

        # @!attribute effective_at
        #   The timestamp (ISO8601 format) at which the ledger transaction happened for reporting purposes.
        #   @return [Time]
        optional :effective_at, Time

        # @!attribute effective_date
        #   The date (YYYY-MM-DD) on which the ledger transaction happened for reporting purposes.
        #   @return [Date]
        optional :effective_date, Date

        # @!attribute external_id
        #   A unique string to represent the ledger transaction. Only one pending or posted ledger transaction may have this ID in the ledger.
        #   @return [String]
        optional :external_id, String

        # @!attribute ledgerable_id
        #   If the ledger transaction can be reconciled to another object in Modern Treasury, the id will be populated here, otherwise null.
        #   @return [String]
        optional :ledgerable_id, String

        # @!attribute ledgerable_type
        #   If the ledger transaction can be reconciled to another object in Modern Treasury, the type will be populated here, otherwise null. This can be one of payment_order, incoming_payment_detail, expected_payment, return, paper_item, or reversal.
        #   @return [Symbol, ModernTreasury::Models::PaymentOrderCreateAsyncParams::LedgerTransaction::LedgerableType]
        optional :ledgerable_type,
                 enum: -> {
                   ModernTreasury::Models::PaymentOrderCreateAsyncParams::LedgerTransaction::LedgerableType
                 }

        # @!attribute metadata
        #   Additional data represented as key-value pairs. Both the key and value must be strings.
        #   @return [Hash]
        optional :metadata, Hash

        # @!attribute status
        #   To post a ledger transaction at creation, use `posted`.
        #   @return [Symbol, ModernTreasury::Models::PaymentOrderCreateAsyncParams::LedgerTransaction::Status]
        optional :status,
                 enum: -> { ModernTreasury::Models::PaymentOrderCreateAsyncParams::LedgerTransaction::Status }

        class LedgerEntry < ModernTreasury::BaseModel
          # @!attribute amount
          #   Value in specified currency's smallest unit. e.g. $10 would be represented as 1000. Can be any integer up to 36 digits.
          #   @return [Integer]
          required :amount, Integer

          # @!attribute direction
          #   One of `credit`, `debit`. Describes the direction money is flowing in the transaction. A `credit` moves money from your account to someone else's. A `debit` pulls money from someone else's account to your own. Note that wire, rtp, and check payments will always be `credit`.
          #   @return [Symbol, ModernTreasury::Models::TransactionDirection]
          required :direction, enum: -> { ModernTreasury::Models::TransactionDirection }

          # @!attribute ledger_account_id
          #   The ledger account that this ledger entry is associated with.
          #   @return [String]
          required :ledger_account_id, String

          # @!attribute available_balance_amount
          #   Use `gt` (>), `gte` (>=), `lt` (<), `lte` (<=), or `eq` (=) to lock on the account’s available balance. If any of these conditions would be false after the transaction is created, the entire call will fail with error code 422.
          #   @return [Hash]
          optional :available_balance_amount, Hash

          # @!attribute lock_version
          #   Lock version of the ledger account. This can be passed when creating a ledger transaction to only succeed if no ledger transactions have posted since the given version. See our post about Designing the Ledgers API with Optimistic Locking for more details.
          #   @return [Integer]
          optional :lock_version, Integer

          # @!attribute metadata
          #   Additional data represented as key-value pairs. Both the key and value must be strings.
          #   @return [Hash]
          optional :metadata, Hash

          # @!attribute pending_balance_amount
          #   Use `gt` (>), `gte` (>=), `lt` (<), `lte` (<=), or `eq` (=) to lock on the account’s pending balance. If any of these conditions would be false after the transaction is created, the entire call will fail with error code 422.
          #   @return [Hash]
          optional :pending_balance_amount, Hash

          # @!attribute posted_balance_amount
          #   Use `gt` (>), `gte` (>=), `lt` (<), `lte` (<=), or `eq` (=) to lock on the account’s posted balance. If any of these conditions would be false after the transaction is created, the entire call will fail with error code 422.
          #   @return [Hash]
          optional :posted_balance_amount, Hash

          # @!attribute show_resulting_ledger_account_balances
          #   If true, response will include the balance of the associated ledger account for the entry.
          #   @return [Boolean]
          optional :show_resulting_ledger_account_balances, ModernTreasury::BooleanModel

          # @!parse
          #   # Create a new instance of LedgerEntry from a Hash of raw data.
          #   #
          #   # @param data [Hash{Symbol => Object}] .
          #   #   @option data [Integer] :amount Value in specified currency's smallest unit. e.g. $10 would be represented
          #   #     as 1000. Can be any integer up to 36 digits.
          #   #   @option data [String] :direction One of `credit`, `debit`. Describes the direction money is flowing in the
          #   #     transaction. A `credit` moves money from your account to someone else's. A
          #   #     `debit` pulls money from someone else's account to your own. Note that wire,
          #   #     rtp, and check payments will always be `credit`.
          #   #   @option data [String] :ledger_account_id The ledger account that this ledger entry is associated with.
          #   #   @option data [Hash, nil] :available_balance_amount Use `gt` (>), `gte` (>=), `lt` (<), `lte` (<=), or `eq` (=) to lock on the
          #   #     account’s available balance. If any of these conditions would be false after the
          #   #     transaction is created, the entire call will fail with error code 422.
          #   #   @option data [Integer, nil] :lock_version Lock version of the ledger account. This can be passed when creating a ledger
          #   #     transaction to only succeed if no ledger transactions have posted since the
          #   #     given version. See our post about Designing the Ledgers API with Optimistic
          #   #     Locking for more details.
          #   #   @option data [Hash, nil] :metadata Additional data represented as key-value pairs. Both the key and value must be
          #   #     strings.
          #   #   @option data [Hash, nil] :pending_balance_amount Use `gt` (>), `gte` (>=), `lt` (<), `lte` (<=), or `eq` (=) to lock on the
          #   #     account’s pending balance. If any of these conditions would be false after the
          #   #     transaction is created, the entire call will fail with error code 422.
          #   #   @option data [Hash, nil] :posted_balance_amount Use `gt` (>), `gte` (>=), `lt` (<), `lte` (<=), or `eq` (=) to lock on the
          #   #     account’s posted balance. If any of these conditions would be false after the
          #   #     transaction is created, the entire call will fail with error code 422.
          #   #   @option data [Hash, nil] :show_resulting_ledger_account_balances If true, response will include the balance of the associated ledger account for
          #   #     the entry.
          #   def initialize(data = {}) = super
        end

        # If the ledger transaction can be reconciled to another object in Modern Treasury, the type will be populated here, otherwise null. This can be one of payment_order, incoming_payment_detail, expected_payment, return, paper_item, or reversal.
        class LedgerableType < ModernTreasury::Enum
          EXPECTED_PAYMENT = :expected_payment
          INCOMING_PAYMENT_DETAIL = :incoming_payment_detail
          PAPER_ITEM = :paper_item
          PAYMENT_ORDER = :payment_order
          RETURN = :return
          REVERSAL = :reversal
        end

        # To post a ledger transaction at creation, use `posted`.
        class Status < ModernTreasury::Enum
          ARCHIVED = :archived
          PENDING = :pending
          POSTED = :posted
        end

        # @!parse
        #   # Create a new instance of LedgerTransaction from a Hash of raw data.
        #   #
        #   # @param data [Hash{Symbol => Object}] .
        #   #   @option data [Array<Object>] :ledger_entries An array of ledger entry objects.
        #   #   @option data [String, nil] :description An optional description for internal use.
        #   #   @option data [String, nil] :effective_at The timestamp (ISO8601 format) at which the ledger transaction happened for
        #   #     reporting purposes.
        #   #   @option data [String, nil] :effective_date The date (YYYY-MM-DD) on which the ledger transaction happened for reporting
        #   #     purposes.
        #   #   @option data [String, nil] :external_id A unique string to represent the ledger transaction. Only one pending or posted
        #   #     ledger transaction may have this ID in the ledger.
        #   #   @option data [String, nil] :ledgerable_id If the ledger transaction can be reconciled to another object in Modern
        #   #     Treasury, the id will be populated here, otherwise null.
        #   #   @option data [String, nil] :ledgerable_type If the ledger transaction can be reconciled to another object in Modern
        #   #     Treasury, the type will be populated here, otherwise null. This can be one of
        #   #     payment_order, incoming_payment_detail, expected_payment, return, paper_item, or
        #   #     reversal.
        #   #   @option data [Hash, nil] :metadata Additional data represented as key-value pairs. Both the key and value must be
        #   #     strings.
        #   #   @option data [String, nil] :status To post a ledger transaction at creation, use `posted`.
        #   def initialize(data = {}) = super
      end

      class LineItem < ModernTreasury::BaseModel
        # @!attribute amount
        #   Value in specified currency's smallest unit. e.g. $10 would be represented as 1000.
        #   @return [Integer]
        required :amount, Integer

        # @!attribute accounting_category_id
        #   The ID of one of your accounting categories. Note that these will only be accessible if your accounting system has been connected.
        #   @return [String]
        optional :accounting_category_id, String

        # @!attribute description
        #   A free-form description of the line item.
        #   @return [String]
        optional :description, String

        # @!attribute metadata
        #   Additional data represented as key-value pairs. Both the key and value must be strings.
        #   @return [Hash]
        optional :metadata, Hash

        # @!parse
        #   # Create a new instance of LineItem from a Hash of raw data.
        #   #
        #   # @param data [Hash{Symbol => Object}] .
        #   #   @option data [Integer] :amount Value in specified currency's smallest unit. e.g. $10 would be represented
        #   #     as 1000.
        #   #   @option data [String, nil] :accounting_category_id The ID of one of your accounting categories. Note that these will only be
        #   #     accessible if your accounting system has been connected.
        #   #   @option data [String, nil] :description A free-form description of the line item.
        #   #   @option data [Hash, nil] :metadata Additional data represented as key-value pairs. Both the key and value must be
        #   #     strings.
        #   def initialize(data = {}) = super
      end

      # Either `normal` or `high`. For ACH and EFT payments, `high` represents a same-day ACH or EFT transfer, respectively. For check payments, `high` can mean an overnight check rather than standard mail.
      class Priority < ModernTreasury::Enum
        HIGH = :high
        NORMAL = :normal
      end

      class ReceivingAccount < ModernTreasury::BaseModel
        # @!attribute account_details
        #   @return [Array<ModernTreasury::Models::PaymentOrderCreateAsyncParams::ReceivingAccount::AccountDetail>]
        optional :account_details,
                 ModernTreasury::ArrayOf.new(
                   -> {
                     ModernTreasury::Models::PaymentOrderCreateAsyncParams::ReceivingAccount::AccountDetail
                   }
                 )

        # @!attribute account_type
        #   Can be `checking`, `savings` or `other`.
        #   @return [Symbol, ModernTreasury::Models::ExternalAccountType]
        optional :account_type, enum: -> { ModernTreasury::Models::ExternalAccountType }

        # @!attribute contact_details
        #   @return [Array<ModernTreasury::Models::PaymentOrderCreateAsyncParams::ReceivingAccount::ContactDetail>]
        optional :contact_details,
                 ModernTreasury::ArrayOf.new(
                   -> {
                     ModernTreasury::Models::PaymentOrderCreateAsyncParams::ReceivingAccount::ContactDetail
                   }
                 )

        # @!attribute ledger_account
        #   Specifies a ledger account object that will be created with the external account. The resulting ledger account is linked to the external account for auto-ledgering Payment objects. See https://docs.moderntreasury.com/docs/linking-to-other-modern-treasury-objects for more details.
        #   @return [ModernTreasury::Models::PaymentOrderCreateAsyncParams::ReceivingAccount::LedgerAccount]
        optional :ledger_account,
                 -> { ModernTreasury::Models::PaymentOrderCreateAsyncParams::ReceivingAccount::LedgerAccount }

        # @!attribute metadata
        #   Additional data represented as key-value pairs. Both the key and value must be strings.
        #   @return [Hash]
        optional :metadata, Hash

        # @!attribute name
        #   A nickname for the external account. This is only for internal usage and won't affect any payments
        #   @return [String]
        optional :name, String

        # @!attribute party_address
        #   Required if receiving wire payments.
        #   @return [ModernTreasury::Models::PaymentOrderCreateAsyncParams::ReceivingAccount::PartyAddress]
        optional :party_address,
                 -> { ModernTreasury::Models::PaymentOrderCreateAsyncParams::ReceivingAccount::PartyAddress }

        # @!attribute party_identifier
        #   @return [String]
        optional :party_identifier, String

        # @!attribute party_name
        #   If this value isn't provided, it will be inherited from the counterparty's name.
        #   @return [String]
        optional :party_name, String

        # @!attribute party_type
        #   Either `individual` or `business`.
        #   @return [Symbol, ModernTreasury::Models::PaymentOrderCreateAsyncParams::ReceivingAccount::PartyType]
        optional :party_type,
                 enum: -> {
                   ModernTreasury::Models::PaymentOrderCreateAsyncParams::ReceivingAccount::PartyType
                 }

        # @!attribute plaid_processor_token
        #   If you've enabled the Modern Treasury + Plaid integration in your Plaid account, you can pass the processor token in this field.
        #   @return [String]
        optional :plaid_processor_token, String

        # @!attribute routing_details
        #   @return [Array<ModernTreasury::Models::PaymentOrderCreateAsyncParams::ReceivingAccount::RoutingDetail>]
        optional :routing_details,
                 ModernTreasury::ArrayOf.new(
                   -> {
                     ModernTreasury::Models::PaymentOrderCreateAsyncParams::ReceivingAccount::RoutingDetail
                   }
                 )

        class AccountDetail < ModernTreasury::BaseModel
          # @!attribute account_number
          #   @return [String]
          required :account_number, String

          # @!attribute account_number_type
          #   @return [Symbol, ModernTreasury::Models::PaymentOrderCreateAsyncParams::ReceivingAccount::AccountDetail::AccountNumberType]
          optional :account_number_type,
                   enum: -> {
                     ModernTreasury::Models::PaymentOrderCreateAsyncParams::ReceivingAccount::AccountDetail::AccountNumberType
                   }

          class AccountNumberType < ModernTreasury::Enum
            AU_NUMBER = :au_number
            CLABE = :clabe
            HK_NUMBER = :hk_number
            IBAN = :iban
            ID_NUMBER = :id_number
            NZ_NUMBER = :nz_number
            OTHER = :other
            PAN = :pan
            SG_NUMBER = :sg_number
            WALLET_ADDRESS = :wallet_address
          end

          # @!parse
          #   # Create a new instance of AccountDetail from a Hash of raw data.
          #   #
          #   # @param data [Hash{Symbol => Object}] .
          #   #   @option data [String] :account_number
          #   #   @option data [String, nil] :account_number_type
          #   def initialize(data = {}) = super
        end

        class ContactDetail < ModernTreasury::BaseModel
          # @!attribute contact_identifier
          #   @return [String]
          optional :contact_identifier, String

          # @!attribute contact_identifier_type
          #   @return [Symbol, ModernTreasury::Models::PaymentOrderCreateAsyncParams::ReceivingAccount::ContactDetail::ContactIdentifierType]
          optional :contact_identifier_type,
                   enum: -> {
                     ModernTreasury::Models::PaymentOrderCreateAsyncParams::ReceivingAccount::ContactDetail::ContactIdentifierType
                   }

          class ContactIdentifierType < ModernTreasury::Enum
            EMAIL = :email
            PHONE_NUMBER = :phone_number
            WEBSITE = :website
          end

          # @!parse
          #   # Create a new instance of ContactDetail from a Hash of raw data.
          #   #
          #   # @param data [Hash{Symbol => Object}] .
          #   #   @option data [String, nil] :contact_identifier
          #   #   @option data [String, nil] :contact_identifier_type
          #   def initialize(data = {}) = super
        end

        class LedgerAccount < ModernTreasury::BaseModel
          # @!attribute currency
          #   The currency of the ledger account.
          #   @return [String]
          required :currency, String

          # @!attribute ledger_id
          #   The id of the ledger that this account belongs to.
          #   @return [String]
          required :ledger_id, String

          # @!attribute name
          #   The name of the ledger account.
          #   @return [String]
          required :name, String

          # @!attribute normal_balance
          #   The normal balance of the ledger account.
          #   @return [Symbol, ModernTreasury::Models::TransactionDirection]
          required :normal_balance, enum: -> { ModernTreasury::Models::TransactionDirection }

          # @!attribute currency_exponent
          #   The currency exponent of the ledger account.
          #   @return [Integer]
          optional :currency_exponent, Integer

          # @!attribute description
          #   The description of the ledger account.
          #   @return [String]
          optional :description, String

          # @!attribute ledger_account_category_ids
          #   The array of ledger account category ids that this ledger account should be a child of.
          #   @return [Array<String>]
          optional :ledger_account_category_ids, ModernTreasury::ArrayOf.new(String)

          # @!attribute ledgerable_id
          #   If the ledger account links to another object in Modern Treasury, the id will be populated here, otherwise null.
          #   @return [String]
          optional :ledgerable_id, String

          # @!attribute ledgerable_type
          #   If the ledger account links to another object in Modern Treasury, the type will be populated here, otherwise null. The value is one of internal_account or external_account.
          #   @return [Symbol, ModernTreasury::Models::PaymentOrderCreateAsyncParams::ReceivingAccount::LedgerAccount::LedgerableType]
          optional :ledgerable_type,
                   enum: -> {
                     ModernTreasury::Models::PaymentOrderCreateAsyncParams::ReceivingAccount::LedgerAccount::LedgerableType
                   }

          # @!attribute metadata
          #   Additional data represented as key-value pairs. Both the key and value must be strings.
          #   @return [Hash]
          optional :metadata, Hash

          # If the ledger account links to another object in Modern Treasury, the type will be populated here, otherwise null. The value is one of internal_account or external_account.
          class LedgerableType < ModernTreasury::Enum
            COUNTERPARTY = :counterparty
            EXTERNAL_ACCOUNT = :external_account
            INTERNAL_ACCOUNT = :internal_account
            VIRTUAL_ACCOUNT = :virtual_account
          end

          # @!parse
          #   # Create a new instance of LedgerAccount from a Hash of raw data.
          #   #
          #   # @param data [Hash{Symbol => Object}] .
          #   #   @option data [String] :currency The currency of the ledger account.
          #   #   @option data [String] :ledger_id The id of the ledger that this account belongs to.
          #   #   @option data [String] :name The name of the ledger account.
          #   #   @option data [String] :normal_balance The normal balance of the ledger account.
          #   #   @option data [Integer, nil] :currency_exponent The currency exponent of the ledger account.
          #   #   @option data [String, nil] :description The description of the ledger account.
          #   #   @option data [Array<String>, nil] :ledger_account_category_ids The array of ledger account category ids that this ledger account should be a
          #   #     child of.
          #   #   @option data [String, nil] :ledgerable_id If the ledger account links to another object in Modern Treasury, the id will be
          #   #     populated here, otherwise null.
          #   #   @option data [String, nil] :ledgerable_type If the ledger account links to another object in Modern Treasury, the type will
          #   #     be populated here, otherwise null. The value is one of internal_account or
          #   #     external_account.
          #   #   @option data [Hash, nil] :metadata Additional data represented as key-value pairs. Both the key and value must be
          #   #     strings.
          #   def initialize(data = {}) = super
        end

        class PartyAddress < ModernTreasury::BaseModel
          # @!attribute country
          #   Country code conforms to [ISO 3166-1 alpha-2]
          #   @return [String]
          optional :country, String

          # @!attribute line1
          #   @return [String]
          optional :line1, String

          # @!attribute line2
          #   @return [String]
          optional :line2, String

          # @!attribute locality
          #   Locality or City.
          #   @return [String]
          optional :locality, String

          # @!attribute postal_code
          #   The postal code of the address.
          #   @return [String]
          optional :postal_code, String

          # @!attribute region
          #   Region or State.
          #   @return [String]
          optional :region, String

          # @!parse
          #   # Create a new instance of PartyAddress from a Hash of raw data.
          #   #
          #   # @param data [Hash{Symbol => Object}] .
          #   #   @option data [String, nil] :country Country code conforms to [ISO 3166-1 alpha-2]
          #   #   @option data [String, nil] :line1
          #   #   @option data [String, nil] :line2
          #   #   @option data [String, nil] :locality Locality or City.
          #   #   @option data [String, nil] :postal_code The postal code of the address.
          #   #   @option data [String, nil] :region Region or State.
          #   def initialize(data = {}) = super
        end

        # Either `individual` or `business`.
        class PartyType < ModernTreasury::Enum
          BUSINESS = :business
          INDIVIDUAL = :individual
        end

        class RoutingDetail < ModernTreasury::BaseModel
          # @!attribute routing_number
          #   @return [String]
          required :routing_number, String

          # @!attribute routing_number_type
          #   @return [Symbol, ModernTreasury::Models::PaymentOrderCreateAsyncParams::ReceivingAccount::RoutingDetail::RoutingNumberType]
          required :routing_number_type,
                   enum: -> {
                     ModernTreasury::Models::PaymentOrderCreateAsyncParams::ReceivingAccount::RoutingDetail::RoutingNumberType
                   }

          # @!attribute payment_type
          #   @return [Symbol, ModernTreasury::Models::PaymentOrderCreateAsyncParams::ReceivingAccount::RoutingDetail::PaymentType]
          optional :payment_type,
                   enum: -> {
                     ModernTreasury::Models::PaymentOrderCreateAsyncParams::ReceivingAccount::RoutingDetail::PaymentType
                   }

          class RoutingNumberType < ModernTreasury::Enum
            ABA = :aba
            AU_BSB = :au_bsb
            BR_CODIGO = :br_codigo
            CA_CPA = :ca_cpa
            CHIPS = :chips
            CNAPS = :cnaps
            DK_INTERBANK_CLEARING_CODE = :dk_interbank_clearing_code
            GB_SORT_CODE = :gb_sort_code
            HK_INTERBANK_CLEARING_CODE = :hk_interbank_clearing_code
            HU_INTERBANK_CLEARING_CODE = :hu_interbank_clearing_code
            ID_SKNBI_CODE = :id_sknbi_code
            IN_IFSC = :in_ifsc
            JP_ZENGIN_CODE = :jp_zengin_code
            MY_BRANCH_CODE = :my_branch_code
            MX_BANK_IDENTIFIER = :mx_bank_identifier
            NZ_NATIONAL_CLEARING_CODE = :nz_national_clearing_code
            PL_NATIONAL_CLEARING_CODE = :pl_national_clearing_code
            SE_BANKGIRO_CLEARING_CODE = :se_bankgiro_clearing_code
            SWIFT = :swift
            ZA_NATIONAL_CLEARING_CODE = :za_national_clearing_code
          end

          class PaymentType < ModernTreasury::Enum
            ACH = :ach
            AU_BECS = :au_becs
            BACS = :bacs
            BOOK = :book
            CARD = :card
            CHATS = :chats
            CHECK = :check
            CROSS_BORDER = :cross_border
            DK_NETS = :dk_nets
            EFT = :eft
            HU_ICS = :hu_ics
            INTERAC = :interac
            MASAV = :masav
            MX_CCEN = :mx_ccen
            NEFT = :neft
            NICS = :nics
            NZ_BECS = :nz_becs
            PL_ELIXIR = :pl_elixir
            PROVXCHANGE = :provxchange
            RO_SENT = :ro_sent
            RTP = :rtp
            SE_BANKGIROT = :se_bankgirot
            SEN = :sen
            SEPA = :sepa
            SG_GIRO = :sg_giro
            SIC = :sic
            SIGNET = :signet
            SKNBI = :sknbi
            WIRE = :wire
            ZENGIN = :zengin
          end

          # @!parse
          #   # Create a new instance of RoutingDetail from a Hash of raw data.
          #   #
          #   # @param data [Hash{Symbol => Object}] .
          #   #   @option data [String] :routing_number
          #   #   @option data [String] :routing_number_type
          #   #   @option data [String, nil] :payment_type
          #   def initialize(data = {}) = super
        end

        # @!parse
        #   # Create a new instance of ReceivingAccount from a Hash of raw data.
        #   #
        #   # @param data [Hash{Symbol => Object}] .
        #   #   @option data [Array<Object>, nil] :account_details
        #   #   @option data [String, nil] :account_type Can be `checking`, `savings` or `other`.
        #   #   @option data [Array<Object>, nil] :contact_details
        #   #   @option data [Object, nil] :ledger_account Specifies a ledger account object that will be created with the external
        #   #     account. The resulting ledger account is linked to the external account for
        #   #     auto-ledgering Payment objects. See
        #   #     https://docs.moderntreasury.com/docs/linking-to-other-modern-treasury-objects
        #   #     for more details.
        #   #   @option data [Hash, nil] :metadata Additional data represented as key-value pairs. Both the key and value must be
        #   #     strings.
        #   #   @option data [String, nil] :name A nickname for the external account. This is only for internal usage and won't
        #   #     affect any payments
        #   #   @option data [Object, nil] :party_address Required if receiving wire payments.
        #   #   @option data [String, nil] :party_identifier
        #   #   @option data [String, nil] :party_name If this value isn't provided, it will be inherited from the counterparty's name.
        #   #   @option data [String, nil] :party_type Either `individual` or `business`.
        #   #   @option data [String, nil] :plaid_processor_token If you've enabled the Modern Treasury + Plaid integration in your Plaid account,
        #   #     you can pass the processor token in this field.
        #   #   @option data [Array<Object>, nil] :routing_details
        #   def initialize(data = {}) = super
      end
    end
  end
end
