module ModernTreasury
  module Resources
    class Transactions
      class LineItems
        def create: (
          amount: Integer,
          expected_payment_id: String,
          transaction_id: String,
          ?request_options: ModernTreasury::request_opts
        ) -> ModernTreasury::Models::Transactions::TransactionLineItem

        def retrieve: (
          String id,
          ?request_options: ModernTreasury::request_opts
        ) -> ModernTreasury::Models::Transactions::TransactionLineItem

        def list: (
          ?id: ::Hash[Symbol, String],
          ?after_cursor: String?,
          ?per_page: Integer,
          ?transaction_id: String,
          ?type: ModernTreasury::Models::Transactions::LineItemListParams::type_?,
          ?request_options: ModernTreasury::request_opts
        ) -> ModernTreasury::Page[ModernTreasury::Models::Transactions::TransactionLineItem]

        def delete: (
          String id,
          ?request_options: ModernTreasury::request_opts
        ) -> nil

        def initialize: (client: ModernTreasury::Client) -> void
      end
    end
  end
end
