#!/usr/bin/env bash

set -e

cd "$(dirname "$0")/.."

echo "==> Detecting breaking changes"

TEST_PATHS=(
	test/modern_treasury/resources/shared_test.rb
	test/modern_treasury/resources/connections_test.rb
	test/modern_treasury/resources/counterparties_test.rb
	test/modern_treasury/resources/events_test.rb
	test/modern_treasury/resources/expected_payments_test.rb
	test/modern_treasury/resources/external_accounts_test.rb
	test/modern_treasury/resources/incoming_payment_details_test.rb
	test/modern_treasury/resources/invoices_test.rb
	test/modern_treasury/resources/invoices/line_items_test.rb
	test/modern_treasury/resources/documents_test.rb
	test/modern_treasury/resources/account_collection_flows_test.rb
	test/modern_treasury/resources/account_details_test.rb
	test/modern_treasury/resources/routing_details_test.rb
	test/modern_treasury/resources/internal_accounts_test.rb
	test/modern_treasury/resources/internal_accounts/balance_reports_test.rb
	test/modern_treasury/resources/ledgers_test.rb
	test/modern_treasury/resources/ledger_account_categories_test.rb
	test/modern_treasury/resources/ledger_accounts_test.rb
	test/modern_treasury/resources/ledger_account_balance_monitors_test.rb
	test/modern_treasury/resources/ledger_account_statements_test.rb
	test/modern_treasury/resources/ledger_entries_test.rb
	test/modern_treasury/resources/ledger_transactions_test.rb
	test/modern_treasury/resources/ledger_transactions/versions_test.rb
	test/modern_treasury/resources/line_items_test.rb
	test/modern_treasury/resources/payment_flows_test.rb
	test/modern_treasury/resources/payment_orders_test.rb
	test/modern_treasury/resources/payment_orders/reversals_test.rb
	test/modern_treasury/resources/payment_references_test.rb
	test/modern_treasury/resources/returns_test.rb
	test/modern_treasury/resources/transactions_test.rb
	test/modern_treasury/resources/transactions/line_items_test.rb
	test/modern_treasury/resources/validations_test.rb
	test/modern_treasury/resources/virtual_accounts_test.rb
	test/modern_treasury/resources/bulk_requests_test.rb
	test/modern_treasury/resources/bulk_results_test.rb
	test/modern_treasury/resources/ledger_account_settlements_test.rb
	test/modern_treasury/resources/ledger_account_settlements/account_entries_test.rb
	test/modern_treasury/resources/foreign_exchange_quotes_test.rb
	test/modern_treasury/resources/connection_legal_entities_test.rb
	test/modern_treasury/resources/legal_entities_test.rb
	test/modern_treasury/resources/legal_entity_associations_test.rb
	test/modern_treasury/resources/payment_actions_test.rb
	test/modern_treasury/resources/journal_entries_test.rb
	test/modern_treasury/resources/journal_reports_test.rb
	test/modern_treasury/resources/holds_test.rb
	test/modern_treasury/client_test.rb
)

for PATHSPEC in "${TEST_PATHS[@]}"; do
    # Try to check out previous versions of the test files
    # with the current SDK.
    git checkout "$1" -- "${PATHSPEC}" 2>/dev/null || true
done

# Instead of running the tests, use the linter to check if an
# older test is no longer compatible with the latest SDK.
./scripts/lint
