module ModernTreasury
  module Resources
    class PaymentOrders
      class Reversals
        def create: (
          String payment_order_id,
          reason: ModernTreasury::Models::PaymentOrders::ReversalCreateParams::reason,
          ?ledger_transaction: ModernTreasury::LedgerTransactionCreateRequest,
          ?metadata: ::Hash[Symbol, String],
          ?request_options: ModernTreasury::request_opts
        ) -> ModernTreasury::PaymentOrders::Reversal

        def retrieve: (
          String reversal_id,
          payment_order_id: String,
          ?request_options: ModernTreasury::request_opts
        ) -> ModernTreasury::PaymentOrders::Reversal

        def list: (
          String payment_order_id,
          ?after_cursor: String?,
          ?per_page: Integer,
          ?request_options: ModernTreasury::request_opts
        ) -> ModernTreasury::Internal::Page[ModernTreasury::PaymentOrders::Reversal]

        def initialize: (client: ModernTreasury::Client) -> void
      end
    end
  end
end
