module ModernTreasury
  module Type
    module Converter
      type input = ModernTreasury::Type::Converter | Class

      type state =
        {
          strictness: bool | :strong,
          exactness: { yes: Integer, no: Integer, maybe: Integer },
          branched: Integer
        }

      def coerce: (
        top value,
        state: ModernTreasury::Type::Converter::state
      ) -> top

      def dump: (top value) -> top

      def self.type_info: (
        {
          const: (nil | bool | Integer | Float | Symbol)?,
          enum: ^-> ModernTreasury::Type::Converter::input?,
          union: ^-> ModernTreasury::Type::Converter::input?
        }
        | ^-> ModernTreasury::Type::Converter::input
        | ModernTreasury::Type::Converter::input spec
      ) -> (^-> top)

      def self.coerce: (
        ModernTreasury::Type::Converter::input target,
        top value,
        ?state: ModernTreasury::Type::Converter::state
      ) -> top

      def self.dump: (
        ModernTreasury::Type::Converter::input target,
        top value
      ) -> top
    end
  end
end
