module ModernTreasury
  module Models
    class InvoiceLineItemCreate = Invoices::InvoiceLineItemCreate

    module Invoices
      type invoice_line_item_create =
        {
          name: String,
          unit_amount: Integer,
          description: String,
          direction: String,
          metadata: ::Hash[Symbol, String],
          quantity: Integer,
          unit_amount_decimal: String
        }

      class InvoiceLineItemCreate < ModernTreasury::Internal::Type::BaseModel
        attr_accessor name: String

        attr_accessor unit_amount: Integer

        attr_reader description: String?

        def description=: (String) -> String

        attr_reader direction: String?

        def direction=: (String) -> String

        attr_reader metadata: ::Hash[Symbol, String]?

        def metadata=: (::Hash[Symbol, String]) -> ::Hash[Symbol, String]

        attr_reader quantity: Integer?

        def quantity=: (Integer) -> Integer

        attr_reader unit_amount_decimal: String?

        def unit_amount_decimal=: (String) -> String

        def initialize: (
          name: String,
          unit_amount: Integer,
          ?description: String,
          ?direction: String,
          ?metadata: ::Hash[Symbol, String],
          ?quantity: Integer,
          ?unit_amount_decimal: String
        ) -> void

        def to_hash: -> {
          name: String,
          unit_amount: Integer,
          description: String,
          direction: String,
          metadata: ::Hash[Symbol, String],
          quantity: Integer,
          unit_amount_decimal: String
        }
      end
    end
  end
end
