module ModernTreasury
  module Models
    module Invoices
      type line_item_create_params =
        {  } & ModernTreasury::Internal::Type::request_parameters

      class LineItemCreateParams < ModernTreasury::Models::Invoices::InvoiceLineItemCreate
        extend ModernTreasury::Internal::Type::RequestParameters::Converter
        include ModernTreasury::Internal::Type::RequestParameters

        def initialize: (?request_options: ModernTreasury::request_opts) -> void

        def to_hash: -> { request_options: ModernTreasury::RequestOptions }
      end
    end
  end
end
