module ModernTreasury
  module Models
    module Invoices
      type line_item_update_params =
        {
          invoice_id: String,
          description: String,
          direction: String,
          metadata: ::Hash[Symbol, String],
          name: String,
          quantity: Integer,
          unit_amount: Integer,
          unit_amount_decimal: String
        }
        & ModernTreasury::request_parameters

      class LineItemUpdateParams < ModernTreasury::BaseModel
        extend ModernTreasury::RequestParameters::Converter
        include ModernTreasury::RequestParameters

        attr_accessor invoice_id: String

        attr_reader description: String?

        def description=: (String) -> String

        attr_reader direction: String?

        def direction=: (String) -> String

        attr_reader metadata: ::Hash[Symbol, String]?

        def metadata=: (::Hash[Symbol, String]) -> ::Hash[Symbol, String]

        attr_reader name: String?

        def name=: (String) -> String

        attr_reader quantity: Integer?

        def quantity=: (Integer) -> Integer

        attr_reader unit_amount: Integer?

        def unit_amount=: (Integer) -> Integer

        attr_reader unit_amount_decimal: String?

        def unit_amount_decimal=: (String) -> String

        def initialize:
          (
            invoice_id: String,
            description: String,
            direction: String,
            metadata: ::Hash[Symbol, String],
            name: String,
            quantity: Integer,
            unit_amount: Integer,
            unit_amount_decimal: String,
            request_options: ModernTreasury::request_opts
          ) -> void
          | (
            ?ModernTreasury::Models::Invoices::line_item_update_params
            | ModernTreasury::BaseModel data
          ) -> void

        def to_hash: -> ModernTreasury::Models::Invoices::line_item_update_params
      end
    end
  end
end
