module ModernTreasury
  module Models
    module Invoices
      type line_item_list_params =
        { after_cursor: String?, per_page: Integer }
        & ModernTreasury::Internal::Type::request_parameters

      class LineItemListParams < ModernTreasury::Internal::Type::BaseModel
        extend ModernTreasury::Internal::Type::RequestParameters::Converter
        include ModernTreasury::Internal::Type::RequestParameters

        attr_accessor after_cursor: String?

        attr_reader per_page: Integer?

        def per_page=: (Integer) -> Integer

        def initialize: (
          ?after_cursor: String?,
          ?per_page: Integer,
          ?request_options: ModernTreasury::request_opts
        ) -> void

        def to_hash: -> ModernTreasury::Models::Invoices::line_item_list_params
      end
    end
  end
end
